### ISSUE TITLE
How to flatten part of the json?

### ISSUE THREAD

**Issue by soapsign** [paularmstrong/normalizr#108]
```json
{
  "data": {
    "feed": [
      {
        "id": "12",
        "comments": {
          "count": 1,
          "data": [
            {
              "createdAt": "1453885534",
              "id": "1",
              "from": {
                "username": "alex",
                "id": "3",
                "fullName": "",
                "avatar": "https://igcdnhd.net/5042.jpg"
              },
              "text": "<3"
            }
          ]
        }
      }
    ]
  }
}
```
In the above simplified json, `Feed` is an array of `Post`. `Post` have an array of `Comment`. `Comment` has `User`. The `comments` part of the json is composite from `count` and `data`.
How can I flatten it so that it becomes `bag['posts']['12']['commentsCount'] = 1` and `bag['posts']['12']['comments'] = [1]`?

**Comment by paularmstrong** [comment]
This looks like almost exactly what you want to do: https://github.com/paularmstrong/normalizr/blob/d19833351100ee8abab878b447fea95b3d9237e5/test/index.js#L389-L445 (`assignEntity` option on `Schema` objects is new in v2.1.0)

**Comment by soapsign** [comment]
Great. I will try it in v2.1.0. Thanks!
