### ISSUE TITLE
deNormalize

### ISSUE THREAD

**Issue by reharik** [paularmstrong/normalizr#111]
It would be great if there were a function that would take the normalized entity and build it back out so you could take that and display it on the page.

**Comment by paularmstrong** [comment]
This has been brought up a [few times](https://github.com/paularmstrong/normalizr/search?q=denormalize&type=Issues&utf8=%E2%9C%93). It will not be handled by normalizr.

**Comment by paularmstrong** [comment]
So, I'm going to eat my hat. #214
