### ISSUE TITLE
docs incorrectly identify assignEntities as an option to new Schema

### ISSUE THREAD

**Issue by outofculture** [paularmstrong/normalizr#112]
That's an option that only works when passed to `normalize(`.

**Comment by paularmstrong** [comment]
You're probably using 2.0.x. Update to 2.1.0 and you should get the option.

Relevant [commit](https://github.com/paularmstrong/normalizr/commit/08c8825d7f906a112d5fc2749031686bd8f2e3c0) and PR #104]
