### ISSUE TITLE
Error TS2307: Cannot find module 'normalizr'

### ISSUE THREAD

**Issue by biesbjerg** [paularmstrong/normalizr#113]
I'm trying to use 'normalizr' with Angular 2 RC1 (Using Ionic Framework 2)

I installed as instructed in the README:
`npm install --save normalizr`

And when I try to import using:
`import {normalize, Schema, arrayOf} from 'normalizr';`

I get an error from the Visual Studio and the TypeScript compiler in the terminal:
`app/store/products/products.model.ts(5,42): Error TS2307: Cannot find module 'normalizr'.`

I tried re-installing, manually removing node_modules dir and doing a fresh npm install without success.

Sorry if it's me that are making a mistake, and not normalizr's fault, but I believe I have done everything according to the README.

**Comment by paularmstrong** [comment]
This sounds like a typescript issue. I've never used typescript, but you probably need type definitions: http://stackoverflow.com/questions/35102441/typescript-compiler-error-ts2307-cannot-find-module-jquery

There's a PR that's been open for a while, but needs tests added: #84

**Comment by paularmstrong** [comment]
Added #119 to address this. Community help from someone with Typescript experience would be greatly appreciated!

**Comment by jlsuarezs** [comment]
Have you solved this issue?
