### ISSUE TITLE
Possibility to provide default values to a model

### ISSUE THREAD

**Issue by smashercosmo** [paularmstrong/normalizr#114]
# Problem

Sometimes it is useful to hydrate data with default values, when they are not provided in the server response. 

**Input**

It could look like this:

``` js
const item = new Schema('items', {defaults: {hello: 1}});
normalize([{id: 1, foo: 'bar'}, {id: 2, fuz: 'baz'}], arrayOf(item));
```

**Output**

Here's what I expect to see when I run the above:

``` js
{
  result: [1, 2],
  entities: {
    items: {
      1: {id: 1, foo: 'bar', hello: 1},
      1: {id: 2, fuz: 'baz', hello: 1}
    }
  }
}
```

**Comment by paularmstrong** [comment]
How prevalent is this amongst APIs? We've done this in one place, but did it in our redux reducer when adding the items to the state.

You could currently accomplish this in normalizr with a custom `assignEntity` function:

```js
const item = new Schema('items', { assignEntity: (output, key, value, input) => {
  if (!('hello' in input) && !('hello' in output)) {
    output.hello = 1;
  }
  output[key] = value;
});
```

**Comment by smashercosmo** [comment]
Hmm.. but ```assignEntity``` is invoked on every key. Isn't it a bit of overhead to make all this checks multiple times. Seems like it is much easier to just merge defaults into model before all other transformations. Reducer is not the right place for that, because we want to do that only once, when the responce is received. I think, that providing default values is a part of data normalization process.

**Comment by paularmstrong** [comment]
Sounds good to me. I'd accept a PR that handles this. I assume it's only for Entity Schema and not union/arrays?

**Comment by smashercosmo** [comment]
Yes, only for Entity Schema

**Comment by smashercosmo** [comment]
Closed by https://github.com/paularmstrong/normalizr/commit/b880e4c88de79355a11dc0f321e78817fcd510d3

**Comment by pavel06081991** [comment]
@smashercosmo, Please add description of this feature to documentation

**Comment by smashercosmo** [comment]
@pavel06081991 this feature was removed in v3.0 https://github.com/paularmstrong/normalizr/releases/tag/v3.0.0

**Comment by pavel06081991** [comment]
@smashercosmo, thanks
