### ISSUE TITLE
Different attribute values for same entity

### ISSUE THREAD

**Issue by lmuntaner** [paularmstrong/normalizr#116]
# Problem

We have a situation where the same entity has different values of a specific attribute depending on where that entity comes from.

**Input**

Following your example with articles, this would be the input:

```js
var article = new Schema('articles'),
        tutorial = new Schema('tutorials'),
        magazine = new Schema('magazine'),
        articleOrTutorial = { articles: article, tutorials: tutorial },
        input;

magazine.define({
  contents: arrayOf(articleOrTutorial, { schemaAttribute: 'type' } )
});

input = [
  {
    id: 1,
    name: 'my magazine',
    contents: [{
        id: 1,
        type: 'articles',
        title: 'Some Article',
        releaseDate: '01/01/2016'
      }, {
        id: 2,
        type: 'articles',
        title: 'Another Article',
        releaseDate: '10/01/2016'
      }, {
        id: 1,
        type: 'tutorials',
        title: 'Some tutorial',
        releaseDate: '10/01/2016'
      }]
    },
    {
      id: 2,
      name: 'your magazine',
      contents: [{
        id: 1,
        type: 'articles',
        title: 'Some Article',
        releaseDate: '15/01/2016'
      }, {
        id: 2,
        type: 'articles',
        title: 'Another Article',
        releaseDate: '25/01/2016'
      }, {
        id: 1,
        type: 'tutorials',
        title: 'Some tutorial',
        releaseDate: '25/01/2016'
      }]
    }
  };

output = normalize(input, arrayOf(magazine);
```

**Output**

When we normalize the input, we get merge conflict with the `releaseDate`. We lose the information regarding the specifics of that article or tutorial related to its magazine. The articles are the same and I want to keep them as the same entity. But I'd like to also keep the value that is specific of that article related with the magazine.

I'd like to get maybe something like this:
```js
output = {
  magazines: {
    1:  {
      id: 1,
      name: 'my magazine',
      contents: [{
          id: 1,
          schema: 'articles',
          releaseDate: '01/01/2016'
        }, {
          id: 2,
          schema: 'articles',
          releaseDate: '10/01/2016'
        }, {
          id: 1,
          schema: 'tutorials',
          releaseDate: '10/01/2016'
        }
      ]
    },
    2: {
      id: 2,
      name: 'your magazine',
      contents: [{
          id: 1,
          schema: 'articles',
          releaseDate: '15/01/2016'
        }, {
          id: 2,
          schema: 'articles',
          releaseDate: '25/01/2016'
        }, {
          id: 1,
          schema: 'tutorials',
          releaseDate: '25/01/2016'
        }
      ]
    }
  },
  articles: {
    ...
  },
  tutorials: {
    ...
  }
};
```

# Conclusion

I hope this explanation is clear enough.

Have you ever encountered a situation like this? How did you solve it? We thought about keeping another array with just the `releaseDate` in our magazine object. But it's not very clean.

I'd like to do something like this:
```js
  ...
  function polymorphicItem(item) {
    return { releaseDate: item.releaseDate };
  }

  magazine.define({
    contents: arrayOf(articleOrTutorial, { schemaAttribute: 'type', polymorphicItem: polymorphicItem } )
  });
  ...
  output = normalize(input, arrayOf(magazine);
```

Thank you very much!

**Comment by paularmstrong** [comment]
We've solved this by giving each item a globally unique ID/key instead.

```js
const listSchema = new Schema('list', { idAttribute: (list) => `${list.user.id}-${list.id}` });
```

Would you be able to do something like that instead?

**Comment by eth0lo** [comment]
IMHO that would defeat the porpuse of normalizing in the first place

**Comment by paularmstrong** [comment]
Why is that? The way I see it, your API isn't giving unique IDs for entities that are of the same type. So, by normalizing the IDs, you won't have to run extra merging processes manually to figure out the `releaseDate` for a given `article` or `tutorial`. You can also reference each one individually without needing to directly know the `magazine`.

**Comment by lmuntaner** [comment]
The ids are unique for that resource. They just happen to have one specific different property depending on the context. If we create different IDs for the same resource depending on the contenxt, we will end up having a lot of repetitions.

Moreover, our API gives restricted information about a resource when requested in chunks and all the information when asked independently. It makes a lot of sense to merge both resources to have only one resource with all the information.

**Example**
We ask for the list of magazines, we get an array of contents with the release date but not whether that article has been read by the user. When I ask for that specific article, I get the information abut whether it has been read or not.

Let's say that when I hover the article in the list, I want to see whether it has been read or not. Which means requesting the individual article. When things are normalized, the same article ID will have the information about whether it was read or not. Whereas if I save the article form the list in another ID than the article when I request it individually, it will create a dissonance and information gap. Which I will have the handle.

I hope that this is clear enough.

For us it would simplify a lot our code to have this feature. I think it's a pretty useful feature. I don't see why the polymorphic items only have to bring `id` and `schema` and not other properties.

**Comment by HriBB** [comment]
I have a similar problem. My data looks roughly like this:

Constraints:
Parent location slug is unique.
Child locations slug is unique to parent.
Image slug is unique to location.
Parent location with child locations cannot have images.

```
{
  locations: [{
    id: 1,
    name: 'First location',
    slug: 'first-location',
    locations: [{
      id: 2,
      name: 'First child',
      slug: 'first-child',
      images: [{
         id: 1,
         name: 'First image',
         slug: 'first-image',
      },{
         id: 2,
         name: 'Second image',
         slug: 'second-image',
      }]
    },{
      id: 3,
      name: 'Second child',
      slug: 'second-child',
      images: [{
         id: 3,
         name: 'First image',
         slug: 'first-image',
      },{
         id: 4,
         name: 'Second image',
         slug: 'second-image',
      }]
    }]
  },
    id: 4,
    name: 'Second location',
    slug: 'second-location',
    images: [{
       id: 5,
       name: 'First image',
       slug: 'first-image',
    },{
       id: 6,
       name: 'Second image',
       slug: 'second-image',
    }]
  }]
}
```

With this data, I can build the following urls from slugs.

```
/first-location
/first-location/first-child
/first-location/first-child/first-image
/first-location/first-child/second-image
/first-location/second-child/first-image
/first-location/second-child/second-image
/second-location
/second-location/first-image
/second-location/second-image
```

I am using React Router v2 and my selectors are smart enough to return the right object from state.
It works perfectly. Of course there are problems when I try to mutate the non-normalized state.

So that is why I am trying out normalizr :) This is my schema with default ´idAttribute: 'id'´:

```
const location = new Schema('locations')
const image = new Schema('images')

location.define({
  locations: arrayOf(location),
  images: arrayOf(image),
})
```

The above data normalizes as expected with this schema. But if I change either location or image to `idAttribute: 'slug'`, of course I get merge errors.

After analyzing the tests, I think finally understand how normalizr works, and I guess that there is no way to normalize with `idAttribute: 'slug'` in my case, because it is not globally unique.

I was thinking about possible solutions ... one would be to use the full url as the key. Not sure about the possible drawback of this approach. Maybe in this case, a custom "normalize" function would be the best way forward?

Are there any official recommendations or guidelines for such edge cases.

**Comment by paularmstrong** [comment]
@lmuntaner:

> The ids are unique for that resource.

This still sounds like an edge-case to me. I'm not convinced that the functionality is that useful for enough other people to justify further complicating normalizr. I'd like to hear from more people in the community.

@HriBB 

> I was thinking about possible solutions ... one would be to use the full url as the key. Not sure about the possible drawback of this approach. Maybe in this case, a custom "normalize" function would be the best way forward?

Why not just use the `id` that you've already got? I'm not sure I understand why you'd want to make your unique `id` be something else.

However, if you really need to, using a custom `idAttribute` function to create a unique ID of the slug would make sense.

**Comment by HriBB** [comment]
@paularmstrong I was thinking the same thing :)

Basically I am just playing with normalizr ATM, trying to understand how to integrate it into my data-flow without destroying my app. I was hoping I could use slug as a key, then I could easily select the right data based on router params, instead of iterating over a collection to find the object that matches the slug.

I use reselect to create memoized selectors and this ...

```
export const locationSelector = createSelector(
  locationsBySlugSelector,
  locationParamSelector,
  (locations, slug) => locations[slug] || null // parent slug is always unique in my case
)
```

Is much shorter than this ...

```
export const normalizedLocationSelector = createSelector(
  normalizedLocationsBySlugSelector,
  locationParamSelector,
  (normalized, slug) => {
    let location = null
    if (normalized && normalized.entities && normalized.entities.locations) {
      const locations = normalized.entities.locations;
      for (let key in locations) {
        if (locations[key].slug === slug) {
          location = locations[key]
          break
        }
      }
    }
    return location
  }
)
```

Maybe I could create a slug => id mapping after each normalization, then I could do something like

```
export const normalizedLocationSelector = createSelector(
  normalizedLocationsBySlugSelector,
  normalizedLocationsSlugMapSelector,
  locationParamSelector,
  (normalized, map, slug) => normalized.locations[map[slug]]
)
```
What do you think?

Again, just playing with normalizr ATM, but I will definitely implement it sooner or later, because of the state merging problems. And sorry for spamming github issues, I realize that this should go on stackoverflow ...

Anyway, thanks for your help, really appreciate it ;)

**Comment by lmuntaner** [comment]
@HriBB I think that your issue is pretty similar to ours. Since when you normalize by id, you will lose the `slug` data related to that parent.

As @paularmstrong says there are turnarounds to it like using dynamic ids. However, what I was proposing is to save those properties in the normlized array. Right now, when you do the arrayOf you just save the id as a string or `{id: 'someId', schema: 'locations' }` when polymorphic arrays.

For our own purposes it would be nicer to change what is saved in the normlized array to `{id: 'someId', schema: 'locations', slug: 'someSlug' }`. So that when we denormlize the content we could merge the slug info back to the location resource information.

I have created a [PR](https://github.com/paularmstrong/normalizr/pull/118) that solves it for polymorphic arrays. I could try to add it for nonPolymorphic arrays as well.

@paularmstrong I understand your concerns on keeping normlizr simple. But I think that this is an issue that many people can encounter. The solution proposed in the PR is not complicated compared to the feature it provides, IMHO. Maybe it could also be added for non polymorphic contents, though.

Let me know what you think and whether you'd like to see some new change in the PR.

**Comment by HriBB** [comment]
@lmuntaner will take a look at your PR when I find some spare time ;)

It would be cool if there was a simple and clear way to extend default normalizr behavior to cover these edge cases. But if there is none, I agree with @paularmstrong, we should keep normalizr simple. Maybe just write some documentation on how to handle these edge cases.

Personally I don't mind doing some extra work after normalize() or event writing my own customNormalize() function. Need to do some more testing before I can give my final answer on this matter, though.

**Comment by ranyefet** [comment]
Hi, I have the exact same problem as @HriBB, I need to query my entities by their ```id``` and by ```slug```

With default normalizr behaviour I need to choose one of those which is not ideal for all use cases.
The only solution I can think of is to store my entities by ids, and have another mapping between ```slug -> id```

This will require to run over all entities after normalizr has ran and create that map. 
Is there a way to let us hook into normalizr and define that before so we could avoid the additional loop?

**Comment by HriBB** [comment]
@ranyefet I was thinking the same thing. Create additional indexes during normalization. It would be cool if normalizr would allow that.

**Comment by paularmstrong** [comment]
@ranyefet, @HriBB:  I think what you're looking for is different from the issue noted by @lmuntaner. 

If you don't already have a `slug` in your data, you can create it with a custom [`assignEntity`](https://github.com/paularmstrong/normalizr/blob/f80b831fb53a7607d873e113c542a4365673a323/README.md#normalizeobj-schema-options) function. 

I think it'd be too complicated to actually *create* additional indexes and output them with normalizr. We've done this in some places like for users, that have a unique `id` and unique `screenName` by creating a custom mapping in our redux state:

```js
const byScreenName = Object.values(users).reduce((hash, user) => {
  hash[user.screenName] = user.id;
  return hash;
}, {});
return {
  byScreenName,
  users
};
/* =>
{
  byScreenName: { paul: '123'},
  users: { '123': { screenName: 'paul', ... } }
}
*/
```

If you have further questions, you might get more support or ideas at StackOverflow.

**Comment by ranyefet** [comment]
Thanks @paularmstrong I did exactly the same thing after calling normalizr.
I was thinking how to add it as part of normalizr but I understand that it's too specific use case. So I guess I keep using my solution :)

**Comment by eth0lo** [comment]
Hi,

instead of assigning other id, effectively duplicating the shared info, what I found that it worked was:

```js
var zipWith = require('lodash.zipwith');
      article = new Schema('articles'),
      tutorial = new Schema('tutorials'),
      articleOrTutorial = { articles: article, tutorials: tutorial },
      magazine, input;

function handleAssosiations(output, key, value, input) {
  let processedValue = value;

  if (key === 'contents') {
    processedValue = zipWith(output.contents, input.contents, (outputElement, inputElement) => {
      outputElement.releaseDate = inputElement.releaseDate;
      return outputElement;
    });
  }

  output[key] = processedValue;
}

magazine = new Schema('magazine', {assignEntity: handleAssosiations});

magazine.define({
  contents: arrayOf(articleOrTutorial, { schemaAttribute: 'type' } )
});

input = [
  {
    id: 1,
    name: 'my magazine',
    contents: [{
        id: 1,
        type: 'articles',
        title: 'Some Article',
        releaseDate: '01/01/2016'
      }, {
        id: 2,
        type: 'articles',
        title: 'Another Article',
        releaseDate: '10/01/2016'
      }, {
        id: 1,
        type: 'tutorials',
        title: 'Some tutorial',
        releaseDate: '10/01/2016'
      }]
    },
    {
      id: 2,
      name: 'your magazine',
      contents: [{
        id: 1,
        type: 'articles',
        title: 'Some Article',
        releaseDate: '15/01/2016'
      }, {
        id: 2,
        type: 'articles',
        title: 'Another Article',
        releaseDate: '25/01/2016'
      }, {
        id: 1,
        type: 'tutorials',
        title: 'Some tutorial',
        releaseDate: '25/01/2016'
      }]
    }
  };

output = normalize(input, arrayOf(magazine);
```

this will effectively output:

```js
output = {
  magazines: {
    1:  {
      id: 1,
      name: 'my magazine',
      contents: [{
          id: 1,
          schema: 'articles',
          releaseDate: '01/01/2016'
        }, {
          id: 2,
          schema: 'articles',
          releaseDate: '10/01/2016'
        }, {
          id: 1,
          schema: 'tutorials',
          releaseDate: '10/01/2016'
        }
      ]
    },
    2: {
      id: 2,
      name: 'your magazine',
      contents: [{
          id: 1,
          schema: 'articles',
          releaseDate: '15/01/2016'
        }, {
          id: 2,
          schema: 'articles',
          releaseDate: '25/01/2016'
        }, {
          id: 1,
          schema: 'tutorials',
          releaseDate: '25/01/2016'
        }
      ]
    }
  },
  articles: {
    ...
  },
  tutorials: {
    ...
  }
};
```

PS: You still need to handle the ``releaseDate`` inside each content type (tutorial, article) in order to avoid  the warning while merging

**Comment by eth0lo** [comment]
@lmuntaner I think we can close this issue, @paularmstrong maybe adding this to a recipe would be better, what do you think?.

**Comment by lmuntaner** [comment]
I agree, that seems like a nice solution.

**Comment by paularmstrong** [comment]
Great solution, @eth0lo. I'm still trying to find time to put a set of examples #107 into the repo. If anyone wants to jump start that with this solution, that'd be great!
