### ISSUE TITLE
Add Typescript definitions

### ISSUE THREAD

**Issue by paularmstrong** [paularmstrong/normalizr#119]
# Problem

From #113:

> Error TS2307: Cannot find module 'normalizr'

Typescript users are likely to have issues using normalizr.

# Solution

Add Typescript definitions. This was started in #84, but needs tests added (and likely needs to be updated for any changes we've made). 

I have never used Typescript before and don't plan on taking the time to learn it right now, so community help would be greatly appreciated.

**Comment by jimitndiaye** [comment]
There's a pretty good set of typings on definitelytyped. Would be be great it it was included in the distributable. That said, it was a simple matter to just install the typings via **"typings install dt~normalizr"**

**Comment by paularmstrong** [comment]
Closed by #84
