### ISSUE TITLE
Question about the idAttribute

### ISSUE THREAD

**Issue by jnatherley** [paularmstrong/normalizr#122]
Does the nestedSchema only except an Object or ObjectArray?
Currently we're working with an API that exposes different nestedSchemas either in string or object format. I'm not sure if it makes sense, but it seems the inferring the idAttribute doesn't work with strings and it only works on strings.

**Input**

I would ideally like to just return the string if it's a string or an id if it's an object. It seems normalizr doesn't pass strings to be normalized.

```js
const users                       = new Schema('users', { schemaAttribute: (entity) => {
  if (isObject(entity) {
    return entity.id
  }
  return entity // should be a string
}})
const posts                       =  new Schema('posts')

const posts.define({
  user_id: users,
})

```

Here's how I'm using normalizr:
When it's a not an object
```js
const post = {
  id: 1,
  user_id: 1
}
```

**Output**

Here's what I expect to see when I run the above:

```js
{
  entities: {
    posts: {
      1: {
        users: {/*...*/}
      }
    },
    users: {
     1: {
       posts: {/*...*/}
     }
    }
  }
}
```

It would also be nice to see more in-depth examples on the received data, exact setup of the schemas and options, output and best practices.

**Comment by paularmstrong** [comment]
What's your actual input that's being passed to `normalize`? 

> It would also be nice to see more in-depth examples on the received data, exact setup of the schemas and options, output and best practices.

You can browse through the [test cases](https://github.com/paularmstrong/normalizr/blob/f80b831fb53a7607d873e113c542a4365673a323/test/index.js) for more examples.

**Comment by jnatherley** [comment]
```js
normalize({
  id: 1,
  user_id: 1
}, posts)
```

I think this as an input, but perhaps the user will be an object in a different API call. Also thanks for the heads up, i'll check out the test cases. @paularmstrong

**Comment by jnatherley** [comment]
Nevermind, it seems that the normalize only accepts an Object or Array.

I think i'll just find a way to transform the response before handing it to normalize.

**Comment by paularmstrong** [comment]
Ah, sorry I was a little lost before. I see what's happening now. Normalizr doesn't have a way to say "this is either an entity or not an entity (and potentially already normalized)".

I think this type of output has been seen before, and I'd be open to considering a PR that checks if a value for a nested `Schema` is already normalized. The only problem is that there isn't an entity available to put into the `entities` output object. I am concerned that this might cause extra confusion.

**Comment by jnatherley** [comment]
Seems like it could be quite a common use case.

**Comment by kristojorg** [comment]
+1

**Comment by paularmstrong** [comment]
Closing due to lack of pull requests / interest. If anyone needs this, feel free to resurface by creating a pull request.
