### ISSUE TITLE
Ignoring keys in responses

### ISSUE THREAD

**Issue by andrewmclagan** [paularmstrong/normalizr#123]
# Problem

Say we have an API response as follows *(pseudo code)*:
````
{
	settings: { billing: {}, dates: {}, general: {} },
	people: [{Person}, {Person}, {Person}],
	countries: [{Country}, {Country}, {country}]
}
````
How can we *"ignore"* a particular key in the response? Using the above example we may want to tell normalizr to ignore the `settings` key as its not a id => keyed entity rather a dictionary. I don't feel I want to run normalizr over such an object when its not needed.

**How can we tell normalizr to pass an original key from the response and not modify it** 

The above would become, as we *ignore* the `settings`  key:

````
{
	settings: { billing: {}, dates: {}, general: {} },
	result: {
		people: [1,2,3],
		countries: [1,2,3],
	},
	entities: {
		people: { 1: {Person}, 2: {Person}, 3: {Person} },
		countries: { 1: {Country}, 2: {Country}, 3: {country} },
	}
}
````

**Comment by paularmstrong** [comment]
Don't define it. Anything that isn't a schema is passed right through.

```js
normalize(input, { people: arrayOf(peopleSchema), countries: arrayOf(countrySchema) });
// =>
// {
//   result: {
//     people: [1, 2, 3],
//     countries: [1, 2, 3],
//     settings: { billing: {}, ... }
//   },
//   entities: { people: { ... }, countries: { ... } }
// }

```
