### ISSUE TITLE
Schema use null value for entites key

### ISSUE THREAD

**Issue by lemt93** [paularmstrong/normalizr#124]
# Problem
My response from API have structure like this: 
```js
[
  {
     id: 1,
     name: 'John Doe',
     manager: {
       id: null,
       name: null
     }
  },
  {
     id: 2,
     name: 'Jane Doe',
     manager: {
       id: 'lemt93',
       name: 'lemt93'
     }
  }
]
```

**Input**

And I define schema like this:

```js
const employee = new Schema('employees')
const manager = new Schema('manager')

employee.define({ manager })

normalize(response, arrayOf(employee))
```

**Output**

It's work as expected, but the `manager` entity also use `null` value for key in entities.
So in `entities.manager`

```js
manager: {
  lemt93: {
    id: 'lemt93',
    name: 'lemt93'
  },
  null: {
    id: null,
    name: null
  }    
}
```

My question is how should I define a schema so that it won't use `null` value of `id` attribute, therefore it won't create an entity with key `null` like example above

**Comment by gvandyk-r7** [comment]
+1

**Comment by paularmstrong** [comment]
This is normalizr working as intended. Normalizr doesn't care what your `id` values are, and in this case, you have a defined `id` as `null`, so it's respecting that. My recommendation would be to strip it out after normalization.
