### ISSUE TITLE
Collections that are always keyed.

### ISSUE THREAD

**Issue by andrewmclagan** [paularmstrong/normalizr#129]
# Problem

As per JSON-API specs we often recieve repsonses that are keyed e.g.

````
{
	data: [
		{ id: 1, title: 'My Book' },
		{ id: 2, title: 'Your Book' },
		{ id: 3, title: 'Their Book' },
		// ...
	]
}
````
Even nested entity relationships are keyed this way in proper JSON-API specs:

````
{
	data: [
		{ 
			id: 1, 
			title: 'My Book' 
			chapters: {
				data: [
					{ id: 1, pages: 23 },
					{ id: 2, pages: 45 },
					{ id: 3, pages: 86 },
					{ id: 4, pages: 13 },
				]
			},
			paragraphs: {
				data: [
					{ id: 1, words: 223 },
					{ id: 2, words: 655 },
					{ id: 3, words: 6543 },
					{ id: 4, words: 733 },
				]
			}
		},
		// ...
	]
}
````

**Outcome**

Any ideas around setting a *global key* on schemas? Something like:

````
const book = new Schema('books', { key: 'data' });

const page = new Schema('pages', { key: 'data' });

const paragraph = new Schema('paragraphs', { key: 'data' });
````
That way we don't have to do any of the following boilerplate:
````
// Definitions
book.define({
  pages: {
    data: arrayOf(page),
  },
  paragraphs: {
    data: arrayOf(paragraph),
  },
});

//  Responses

fetch('/books').then(response => normalize(response, {
      data: arrayOf(book),
})
````

**Comment by paularmstrong** [comment]
I think that specific use-cases for JSON-API come up fairly often, but require a lot of changes that other (more crazy) formats don't really need. A fork of normalizr that's specific for JSON-API sounds like a good way to go. 

Consider this my blessing for normalizr-json-api 🎉 👍

**Comment by andrewmclagan** [comment]
Is there currently anyway of doing this with assignEntity or similar?

**Comment by paularmstrong** [comment]
Nope. Your schemas must be pre-defined.
