### ISSUE TITLE
Allow dynamic schemaAttribute for children by checking a key on the parent-level

### ISSUE THREAD

**Issue by jgutta** [paularmstrong/normalizr#130]
In this example from your read me:

``` js
const group = new Schema('groups');
const user = new Schema('users');

// a member can be either a user or a group
const member = {
  users: user,
  groups: group
};

// You can specify the name of the attribute that determines the schema
group.define({
  owner: unionOf(member, { schemaAttribute: 'type' })
});
```

is normalizr looking for the schemaAttribute in the "member" object, or the "group" object? If it is looking at the "member"  object, is there a way to make it check "group"  instead?

EDIT: To answer half of my own question, Normalizr looks for the schemaAttribute in the "member" object. I am still working on a way to check the parent, any advice in that direction would be appreciated!

**Comment by fxck** [comment]
I've got the exact same problem.

**Comment by fxck** [comment]
@paularmstrong @gaearon any advice? basically my by data structure looks like this 

```
{
  // ...
  schema: 'foo',
  data: { /* ... */ }
}
```

and I want `data` to be a schema of something depending on what's inside the `schema`, the closest I got was by using `unionOf`(which doesn't even make that much sense here I think), but what get's passed to `schemaAttribute` is what's inside of `data`, not its parent..

ideal would be if this worked

```typescript

const somethingSchema = new Schema('something');
const fooSchema = new Schema('foo');

const schemaMap = {
  foo: fooSchema
};
something.define({
  data: (entity) => schemaMap[entity.schema]
});
```

**Comment by paularmstrong** [comment]
This is not available yet. I'm not sure how easy it'd be, either... at a cursory glance, that looks like a pretty big overhaul. If you'd like to try it out and open a PR, I'd be happy to look.

**Comment by fxck** [comment]
Damn that's too bad @paularmstrong I tried looking into the source code to see if there was a simple way to implement it prior to writing down the comment, and I couldn't quite figure out where to even begin..

**Comment by fxck** [comment]
So I gave it a shot, I think the only change in the end was at this line https://github.com/paularmstrong/normalizr/blob/master/src/index.js#L18

where instead of just passing it `schema[key]`, I do `const resolvedSchema = typeof schema[key] === 'function' ? schema[key].call(null, obj) : schema[key];` instead.. it seems to work, what do you think? 

I'll try to write some tests

**Comment by fxck** [comment]
https://github.com/paularmstrong/normalizr/pull/132

**Comment by jgutta** [comment]
@fxck I haven't been able to find a way to read the entry from the parent. As a work around, I defined a function for schemaAttribute that (to relate it to this example) looks for fields that are unique to "user" or "group". If that field isn't null, then I know which of the two schemas to apply. The code looks something like this:

`function inferSuppressionConditionSchema(entity) {
    if(entity.field_exclusive_to_user){
        return 'users'
    } else {
        return 'groups'
    }
}`

In my case, I am switching between 3 potential objects, but the idea is the same. If your solution works, Id be happy to do this in a less hacky way!

**Comment by joewestcott** [comment]
Is this still possible in v3?

**Comment by fxck** [comment]
I don't think so.

**Comment by joewestcott** [comment]
Can you put it back? 😛

**Comment by fxck** [comment]
Dunno, @paularmstrong ?

**Comment by joewestcott** [comment]
Can this breaking change at least be notified on the v3 changelog?

**Comment by paularmstrong** [comment]
PRs accepted
