### ISSUE TITLE
Normalize when some data is pre-flattened...

### ISSUE THREAD

**Issue by kristojorg** [paularmstrong/normalizr#133]
# Problem

I have an api response for posting a new comment that looks like this:

**Input**
```
comment: {
  ...
  id: 0,
  topic_id: 91,         //the id of the parent topic
  ...
}
```

**Schemas.js** (simplified)
I normalize it with :

```
//schemas.js
export const topic = new Schema('topics');
export const comment = new Schema('comments');

topic.define({
  comments: arrayOf(comment),
});
comment.define({
  topic_id: post,
});
```
**Desired Result**
I want my normalized result to look like this:
```
entities : {
  topic: { 
    id: 91,
    comments: [0],
  },
  comment: { 
    id: 0,
    topic: 91,
  },
},
```

Instead it looks like this: 
```
entities : {
  comment: { 
    id: 0,
    topic_id: 91,
  },
},
```

The reason I need this is so that when i merge these entities with the entities in my Redux store, the topic is given this new comment and the appropriate connected topic component updates its comment list in the UI. 

Is there currently a way to update my `schemas.js` to accurately reflect that this is just the `id` of a topic, not the actual nested topic itself?

Thank you!!

**Comment by paularmstrong** [comment]
You can use the `assignEntity` function for this.

There's a close example to what you want at the bottom of the first code block [in the docs under new Schema](https://github.com/paularmstrong/normalizr#api-reference), there's a [test case](https://github.com/paularmstrong/normalizr/blob/acd3ad0b507c8d768b1953e5c8ba157c68706b7c/test/index.js#L89-L135), and [docs](https://github.com/paularmstrong/normalizr#normalizeobj-schema-options)

**Comment by kristojorg** [comment]
Okay, I've looked into that and I'm really sorry if this is a dumb question - have only been coding for a few months... 

When I normalize a comment, it calls `assignEntity` for every property. I can check to see if there is a `topic_id`, and then transform the output to have it in the correct format to be processed:
```
function assignCommentEntity(output, key, value, input) {
  if (key === 'topic_id') {
    output.topic = { id: value };
  }
}
```

That however, never get's processed again, so I'm left with an output that looks like this:
```
entities : {
  comment: { 
    id: 0,
    topic: {id: 91},
  },
},
```

How would I force the creation and processing of a new entity (topic)? Should I call one of the internal functions from this method like visit? 

Thank you so much and again a apologize for the dumb question.
