### ISSUE TITLE
typings missing when getting via NPM

### ISSUE THREAD

**Issue by akomm** [paularmstrong/normalizr#136]
When I install normalizr 2.2.0 via npm, the index.d.ts with typings is missing.

package.json contains the entry:

```json
  "typings": "index.d.ts",
```

but it is missing in the package root. 

First I thought the file was recently added and is only in master, but I have the right version and source-wise it is already there in 2.2.0.

I'v also checked if the build process is generating output which is provided as package (and miss the typings), but the only thing the build does is outputing resulting js files into lib folder, which is part of the npm package I receive. The npm package contents are quite what is on github plus npm run build output, minus index.d.ts.

**Comment by paularmstrong** [comment]
Fixed in [v2.2.1](https://github.com/paularmstrong/normalizr/commit/bd0c7b2a06a348e776df967bf112d80803f5bd1f) (available now)
