### ISSUE TITLE
Q: How to re-normalize a flattened record (as coming back from SQL)?

### ISSUE THREAD

**Issue by jimbolla** [paularmstrong/normalizr#137]
Given a SQL query that looks like:
```sql
select
    foo.Id as fooId,
    bar.Id as barId, bar.Name as barName,
    fizz.Id as fizzId, fizz.Name as fizzName,
    buzz.Id as buzzId, buzz.Name as buzzName
  from foo
  inner join bar on foo.BarId = bar.Id
  inner join fizz on foo.FizzId = fizz.Id
  inner join buzz on foo.BuzzId = buzz.Id
  where ...
```
If I have an array of those records, can I use normalizr to renormalize back to my 4 entity types?

**Comment by paularmstrong** [comment]
I have no idea what you're actually asking here. Please follow he [issue template](https://github.com/paularmstrong/normalizr/blob/master/ISSUE_TEMPLATE.md) or post this to [stackoverflow](http://stackoverflow.com/questions/tagged/normalizr)

**Comment by jimbolla** [comment]
My apologies. I saw that there were other open questions here that do not follow the issue template and so I thought this was an acceptable place to ask.
