### ISSUE TITLE
Mixed Schema

### ISSUE THREAD

**Issue by Phyks** [paularmstrong/normalizr#142]
Hi,

# Problem

I have some API which returns me responses (typically artists, albums and songs) I'd like to normalize. However, the API is not really consistent and depending on the calls I make, it can return either something like
```javascript
{
    "artists": [
        {
            "name": "foobar",
            […]
            "albums": 2
         }
    }
}
```
or something like 
```javascript
{
    "artists": [
        {
            "name": "foobar",
            […]
            "albums": [
                {
                    "name": "foobarAlbum",
                    […]
                },
                […]
             ]
         }
    }
}
```

That is an `artist` object may either contain an int value for the `albums` field (the number of associated albums) or an array of such `albums`.

In terms of normalizr schemas, it would be either nothing or an `arrayOf(album)`.

What is the proper way to handle such a thing with Normalizr? Should I just have two different Schema and handle the selection of one or the other myself?

Or is there a way to add a test function and write something like (pseudo-code):
```javascript
const artist = new Schema('artists');
const album = new Schema('albums')

artist.define({
  albums: function (item) {
    (typeof item === "array" ? arrayOf(albums) : null;
  }
});
```

Thanks

**Comment by paularmstrong** [comment]
This is not possible right now. At the very least, normalizr expects your responses to be consistent (which I'm finding is not the case often enough). For now, you'll have to go with separate schema.

**Comment by Phyks** [comment]
Ok. Actually, I gave it a try and it appears that something like
```
artist.define({
    albums: arrayOf(album),
    songs: arrayOf(track)
});
```
work even if `albums` key is not an array.

I mean, if `albums` is a number of albums, it stays as a single value, and if `albums` is an array of albums, it gets normalized.

Though, there is no doc about this behavior in the normalizr docs, so I am not sure I can actually use it and expect this to be stable?

Thanks
