### ISSUE TITLE
index.d.ts should be in the same directory as index.js

### ISSUE THREAD

**Issue by akomm** [paularmstrong/normalizr#146]
Currently the `index.d.ts` is located in the package root. This is a problem, because it does not define an interface which is attached to a global object, but an interface which is exported. This cause for example problems in situation where imports for `Schema` & co. are auto-generated and the index.js file with the actual source is located in a different location.

**Comment by paularmstrong** [comment]
Can you open a pull request?

**Comment by whistlerbrk** [comment]
I'm guessing this is the actual root of my problem in #176

**Comment by akomm** [comment]
Solved it via - as always - amazing webpack magic. This still need a fix. Going to look into it. Might be a bc-break is required though. Will see when I check the code again it's a while back now.
