### ISSUE TITLE
Reverse relations

### ISSUE THREAD

**Issue by laurentvd** [paularmstrong/normalizr#147]
# Problem

When I'm defining a two-way one-on-one relation, I'm running into a Maximum call stack size exceeded Error. There probably is a way to do this, but couldn't find it in the docs.

**Input**

A booking can have a discount code and a discount code must have a booking. Sometimes I'm embedding a booking in discount codes and vice versa.

```js
import { Schema } from 'normalizr';

const booking = new Schema('bookings');
const discountCode = new Schema('discountCodes');

booking.define({discountCode});
discountCode.define({booking});
```

I expected the relations to work both ways. Is there something I'm doing wrong?

**Comment by paularmstrong** [comment]
1. What is your input data? 
2. Are you putting in pure JSON, or are you constructing an object that has circular references?

**Comment by laurentvd** [comment]
Thanks for the swift response. I did some more research and tried to isolate the issue. As often the case, the bug wasn't in normalizr but rather my own code :| 

If anyone else runs into the same error, here's a quick test I used to verify normalizr works properly:

```js
var normalizr = require('normalizr');

// Prepare data
var booking = JSON.parse('{"id": 169, "discountCode": {"id": 7, "code": "ABCDEF"}}');
var discountCode = JSON.parse('{"id": 8, "code": "GHIJKLM", "booking": {"id": 170}}');

// Setup schemas
var bookingSchema = new normalizr.Schema('bookings');
var discountCodeSchema = new normalizr.Schema('discountCodes');
bookingSchema.define({discountCode: discountCodeSchema});
discountCodeSchema.define({booking: bookingSchema});

// Normalize data
var normalizedData = normalizr.normalize(booking, bookingSchema);
var normalizedData2 = normalizr.normalize(discountCode, discountCodeSchema);

console.log(normalizedData, normalizedData2);
```

Sorry for the raising creating the issue, my bad, case closed.
