### ISSUE TITLE
Denormalized data access

### ISSUE THREAD

**Issue by felipellrocha** [paularmstrong/normalizr#148]
Hey guys!

I love all the work being done here, and I thought of a feature that I think could be useful.

Normalizing is great for making sure updates are consistent throughout the entire app, but accessing that data can sometimes be cumbersome. I was wondering if there was a way to just _access_ that data *as if* it was denormalized, while keeping the normalized data in the background.

Maybe we could do that using getters and setters, but ideally, it'd be great to support regular dot notation as well!

Thanks,

Felipe

**Comment by felipellrocha** [comment]
Anything on this idea?

**Comment by paularmstrong** [comment]
This has been asked about [many times before](https://github.com/paularmstrong/normalizr/search?q=denormalize&type=Issues&utf8=✓). Ultimately, it's up to your application/system to determine how you want to handle it. Normalizr will not.

**Comment by paularmstrong** [comment]
So, I'm going to eat my hat. #214
