### ISSUE TITLE
[Question] Should I normalize the date

### ISSUE THREAD

**Issue by cristian-sima** [paularmstrong/normalizr#153]
Hi mates.

I receive from my Golang server an `Array<Row>`
```js
Row:  {
 ID: number;
 Date: string;
}
```
ex:
```js
Row: {
 ID: 4,
 Date: "2016-09-02T00:00:00Z"
}
```

Should I normalize the date to a `Date` object, or keep it as a string? And if so, should I use `assignEntity` ?

**Comment by paularmstrong** [comment]
That's really up to you and your application's needs. If you were going to do it, yes, `assignEntity` would work.

Personally, I wouldn't, as it's ever so slightly less memory as a string and has more options for reusing.

**Comment by cristian-sima** [comment]
Yes that's true, but every time I have to do `new Date(InvoiceDate)` and I feel this consumes too much speed
