### ISSUE TITLE
Will arrayOf support a parameter that not a schema?

### ISSUE THREAD

**Issue by lqzerogg** [paularmstrong/normalizr#154]
# Problem

After normalizr process, I want something like this

```
{result: [{a: 'xxx', b: 'xxx', c: 'ccc'}]}
```

But I don't want to defined a schema like:

```
const dSchema = new Schema('d')
dSchema.define({a: aSchema, b: bSchema, c: cSchema})
```

Is there any way to achieve this? If there is, please tell me. If not, will it possible to support it?
I do feel sick of defining an extra schema.

**Input**

```
let input = [{a: {id: 'aid', name: 'object a'}, b: {id: 'bid', name: 'object b'}]
```

**schema**

```
const aSchema = new Schema('as');
const bSchema = new Schema('bs');
normalize(input, arrayOf({a: aSchema, b: bSchema}));
```

**Output**

Here's what I expect to see when I run the above:

```
{
 result: [{a: 'aid', b: 'bid'}],
 entities: {
  as: { aid: {id: 'aid', name: 'object a'}}
  bs: { bid: {id: 'bid', name: 'object b'}}
 }
}
```

**Comment by paularmstrong** [comment]
Are `a`, `b`, and `c` actually different types? Are you always going to be getting an array of a single object?

**Comment by lqzerogg** [comment]
Yes, they are. Not always, but because of this, I have to define lots of extra schema, and most of them are just a union of ids. I just feel that it's not very good.

**Comment by paularmstrong** [comment]
Sorry for the incredibly late reply. This fell off my radar :(

[v3.0.0](https://github.com/paularmstrong/normalizr/tree/normalizr3) will support this. It should work similarly in v2, but I am past the point of verifying :)

```js
const aSchema = new schema.Entity('as');
const bSchema = new schema.Entity('bs');
const valueObject = new schema.Values({
  as: aSchema,
  bs: bSchema,
  // ...
}, (value, parent, key) => key + 's');
normalize(input, [ valueObject ]);
```

Documentation for `schema.Values` is here: https://github.com/paularmstrong/normalizr/blob/normalizr3/docs/api.md#valuesdefinition-schemaattribute

**Comment by lqzerogg** [comment]
I'm looking forword to using v3
