### ISSUE TITLE
Sub group result

### ISSUE THREAD

**Issue by ferllings** [paularmstrong/normalizr#157]
Hello,

I'm trying to group my result by the key 'sampleId'.

**Input**

```js
[{
"title":  "xxx" ,
"id":  "d1" ,
"sampleId":  "s1" ,
}, {
"title":  "yyy" ,
"id":  "d2" ,
"sampleId":  "s1" ,
}, {
"title":  "zzz" ,
"id":  "d3" ,
"sampleId":  "s2" ,
}]
```

**Output**
Is it possible to get the result like that?
What parameters should I use?
```js
     result: { s1: [d1, d2], s2:[d3] },
```

Thanks for your help.

**Comment by paularmstrong** [comment]
normalizr is not capable of this. you could use [lodash/groupBy](https://lodash.com/docs/4.16.4#groupBy) to handle this separately.
