### ISSUE TITLE
Custom mergeIntoEntity in define

### ISSUE THREAD

**Issue by olgabanis** [paularmstrong/normalizr#162]
# Problem / Question

Is it possible to use a custom mergeIntoEntity function when using define? I'm looking through the code and it doesn't seem to be supported. I can use the custom option method in the normalize function as expected, but when trying to use the same schema and options as a property in a definition, it doesn't get called. 

Here's an example where if there are users with the same id, I'm merging any differences they might have in arrays. The code if mostly the same as the default mergeIntoEntity except that instead of logging the warning, it pushes the different items in an array and returns the array. This works as expected when used within the normalize function. 

```
const users = [
{ id: 1, username: 'bob', groupId: 1 },
{ id: 1, username: 'bob', groupId: 2 } 
];

function mergeIntoEntity (entityA, entityB, entityKey) {
    for (let key in entityB) {
      if (!entityB.hasOwnProperty(key)) { continue; }
      if (!entityA.hasOwnProperty(key) || isEqual(entityA[key], entityB[key])) {
        entityA[key] = entityB[key];
        continue;
      }
      if (isObject(entityA[key]) && isObject(entityB[key])) {
        merge(entityA[key], entityB[key]);
        continue;
      }
      // custom code
      if (!Array.isArray(entityA[key])) {
        entityA[key] = [entityA[key], entityB[key]]; 
      } else {
        entityA[key].push(entityB[key]);
        entityA[key] = sortedUniq(entityA[key].sort());
      }
    }
  }

const user = new Schema('users');
const { entities, result } = normalize(users, arrayOf(user), { mergeIntoEntity });

entities is 
{
   1: { 
      id: 1,
      username: 'bob',
      groupId: [1,2]
   }
}
result is [1,1] which is fine, I can turn it into a Set. 
```

I would like to be able to use the same custom mergeIntoEntity function even when the user is part of a defined schema, e.g. 

```
const article = new Schema('articles');
article.define({
   authors: arrayOf(user, { mergeIntoEntity }) 
}); 
```

Is this possible and I'm including it the wrong way? Thank you

**Comment by paularmstrong** [comment]
Nope, not currently possible. The checking for duplicates and merging happens outside of the entity definitions. I'd accept a PR for this if it turns out to be simple, but at quick glance, I think quite a bit of code would need to be moved around.

**Comment by olgabanis** [comment]
Thanks for the quick answer, Paul! 
I'll work around it for now then and maybe put in a PR later. 
Great library, by the way 👍
