### ISSUE TITLE
When and how to enrich response data ?

### ISSUE THREAD

**Issue by zzswang** [paularmstrong/normalizr#163]
# Problem

When and how to enrich response data ?

**Input**

my normalizr schema

const user = new Schema('users');

response: 

```json
{
    "id": "111",
    "first_name": "x",
    "last_name": "y"
}
```

**Output**

Here's what I expect to see when I run the above:

```js
{
   entities: {
      users: {
         "111": {
                 "id": "111",
                 "name": "x.y",
                 "first_name": "x",
                 "last_name": "y"
         }
      }
   }
}
```

Is it good to do it in normalizr step, or leave it to selectors?

If it should be done in normalizr step, how to do it?

**Comment by paularmstrong** [comment]
I'm not sure what you're asking. This seems very specific to your project, so the choices will be yours and yours alone.

**Comment by zzswang** [comment]
I think there are a lot of use cases which is beyond of any specific business logic.

Here I want to caculate "name" property from "first_name" and "last_name".  I want to put this caculated property into store, but didn't find a way to do it in normalizr step.


assignEntity: which will replace or delete a property. not add a new property
