### ISSUE TITLE
id type is string, but change to number

### ISSUE THREAD

**Issue by zzswang** [paularmstrong/normalizr#164]
# Problem

A short explanation of your problem or use-case is helpful!

**Input**

my schema is:

```
const detectorSchema = new Schema('detectors');
```

**Output**

id type is string, but after normalizr, the type of key in entities.detectors is number.

![image](https://cloud.githubusercontent.com/assets/1524745/19812007/60065742-9d66-11e6-975e-e13497801e1c.png)

**Comment by paularmstrong** [comment]
Our tests show that this is not the case. Do you have a repro path for this?

**Comment by zzswang** [comment]
Ha, it works fine. seems it is a display bug of chrome console.
close this issue.
