### ISSUE TITLE
Question: node package for normalised responses

### ISSUE THREAD

**Issue by andrewmclagan** [paularmstrong/normalizr#170]
Normalizr is great, although we control our APIs and would like to have our server normalise the response rather then browsers/clients. 

Does anyone know a node package that can format responses similar to normalizr?

**Comment by BBB** [comment]
@andrewmclagan something that implements the [jsonapi](http://jsonapi.org/) perhaps?

**Comment by BerkeleyTrue** [comment]
Why not just use normalizr in node?

**Comment by andrewmclagan** [comment]
...ah that is a good idea....

**Comment by andrewmclagan** [comment]
Anyone have examples using this package within modems?

**Comment by BerkeleyTrue** [comment]
modems?

**Comment by andrewmclagan** [comment]
*node 
sorry, edited the comment.

**Comment by BerkeleyTrue** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/549cfc305f75d8c6036a3cde65c47b518607b18c/server/utils/map.js#L3

Here we use it to normalize our challenges and challenge blocks. These are then cached and sent to the client.
