### ISSUE TITLE
Normalize different collections with a pre-flatted array

### ISSUE THREAD

**Issue by voidale** [paularmstrong/normalizr#171]
I'm lost while all examples are focused on nested objects what about the following how I can do that?

Posts
`[{ _id: 1, name: 'post text 1', userId: 5, locationId: 8}]`

Locations
`[{ _id: 8, name: 'New York'}]`

Users
`[{ _id: 5, name: 'John Doe', country: 'US'}]`

expected result:
````
{
  results: [1], // posts ids
  entities: {
    posts: {
      1: { name: 'post text 1' }
    },
    users: {
      5: { name: 'John Doe', country: 'US' }
    },
    locations: {
      8: { name: 'New York' },
    }
  }
}
````

Thank you!

**Comment by paularmstrong** [comment]
I'm not sure what you're asking for. What is your actual input? What does your code look like? If you could follow the [issue template](https://github.com/paularmstrong/normalizr/blob/master/.github/ISSUE_TEMPLATE.md), that'd help.
