### ISSUE TITLE
How can I import a schema from another module?

### ISSUE THREAD

**Issue by thuey** [paularmstrong/normalizr#177]
# Problem

I am trying to create a reusable library of schemas that represent my REST API. The difficulty I'm running into is that importing those schemas into another package I'm developing doesn't work correctly. Both the library and the modules I'm developing are independent npm modules, which import their own copies of normalizr.  After digging into normalizr's source code, I believe the problem is here:

```js
  if (schema instanceof EntitySchema) { // <-- This is false because my schema was created from a different "EntitySchema"
    return visitEntity(obj, schema, bag, options, collectionKey);
  } else if (schema instanceof IterableSchema) {
    return visitIterable(obj, schema, bag, options);
  } else if (schema instanceof UnionSchema) {
    return visitUnion(obj, schema, bag, options);
  } else {
    return visitObject(obj, schema, bag, options, collectionKey); // <-- So it falls through to here
  }
```

**Input**

Here's how I'm using normalizr:

library/index.js:
```js
import { Schema } from 'normalizr';

export class Person {
  static schema = new Schema('people');
}
```

dependentModule/index.js:
```js
import { normalize, arrayOf } from 'normalizr';
import { Person } from 'library';

const data = [
  {
    id: 1,
    name: 'John',
  }
];

console.log(normalize(data, arrayOf(Person.schema)));
```

**Output**

Here's what I expect to see when I run the above:

```js
{
  result: [1],
  entities: {
    1: {
      id: 1,
      name: 'John',
    }
  }
}
```

Instead, I'm seeing this:
```js
{
  result: [{
    id: 1,
    name: 'John',
  }],
  entities: {}
}
```

I know this is more of an issue with how javascript works and how I'm creating my schemas. It just seems like a pretty reasonable use case to define schemas in a common place and reuse them in different modules. Is there a better way of doing this that accomplishes the same thing?

**Comment by thuey** [comment]
I have a work-around for this, although it's not ideal. Essentially, I'm exporting normalizr from my library and importing it in my module. This makes sure it's the same normalizr instance. Something like this:

library/index.js:
```js
import { Schema } from 'normalizr';

export * as normalizr from normalizr;

export class Person {
  static schema = new Schema('people');
}
```

dependentModule/index.js:
```js
import { normalizr } from 'library';
import { Person } from 'library';

const { normalize, arrayOf } = normalizr;

const data = [
  {
    id: 1,
    name: 'John',
  }
];

console.log(normalize(data, arrayOf(Person.schema)));
```

The only other alternatives that come to mind involve changing normalizr itself to either do some kind of duck-typing or add a type explicitly to each Schema class that can be checked. Since I have a work-around, I'll close the issue. However, I'd welcome any other suggestions :)

**Comment by paularmstrong** [comment]
@thuey Have you had a chance to look at [v3](https://github.com/paularmstrong/normalizr/tree/normalizr3) (available at the moment as 3.0.0-alpha.5 on npm). It should be possible to use fully custom entity classes, as long as they define methods for `getKey`, `getId`, `merge`, and `normalize`.

**Comment by thuey** [comment]
Thanks! I'll check it out!

**Comment by loschorts** [comment]
@paularmstrong I just ran into this same issue using 3.2.3 because my code was importing a different `normalizr` module than one of my dependencies, causing `denormalize` to fail for the above stated reason. The workaround @thuey gave does work, but I guess I'd also appreciate if the instance checking was removed so that module resolution doesn't affect `denormalize`. thanks!
