### ISSUE TITLE
Renaming the normalized field on parent object

### ISSUE THREAD

**Issue by joshwcomeau** [paularmstrong/normalizr#181]
# Problem

I'm working with a large redux codebase where reducers hold deeply-nested state, and we are going to incrementally normalize different server responses.

Given the following server response:

```js
{
  photos: [
    {
      id: 'photoA',
      user: { id: 'userA' },
    },
  ],
}
```

It can easily be denormalized to something like this:

```js
{
  result: { ... },
  entities: {
    photos: [
      {
        id: 'photoA',
        user: 'userA',
      }
    ],
    users: [ ... ]
  }
}
```

I'm wondering if there's a way I can rename the associated field when denormalizing the "parent" object. In this example, I'd like to receive something like this:

```js
{
  result: { ... },
  entities: {
    photos: [
      {
        id: 'photoA',
        userId: 'userA', // Note that `user` has been renamed to `userId`
      }
    ],
    users: [ ... ]
  }
}
```

This would allow me to clean up my selectors, and keep track of which reducers have been converted to the normalized standard.

Hope this makes sense! Appreciate any guidance that can be provided.

**Comment by paularmstrong** [comment]
You should be able to do this with `assignEntity` ([ref](https://github.com/paularmstrong/normalizr/issues/174#issuecomment-261921833)). Have you tried that?

**Comment by joshwcomeau** [comment]
Hi @paularmstrong,

Thanks for the speedy reply, and your work on normalizr :)

`assignEntity` absolutely works for this! I looked at it briefly yesterday but misunderstood how it worked. After a good night's sleep, it makes a lot more sense.

Sorry for the disruption.

**Comment by seanyu4296** [comment]
Hi @paularmstrong 

Is the ```assignEntity``` API still available for schema.Entity options? I can't seem to find it in the docs

**Comment by philraj** [comment]
@seanyu4296 Looks like you can use the `processStrategy` in the options object you pass to the `schema.Entity` constructor.

**Comment by seanyu4296** [comment]
Yep I decided to use processStrategy!! Thanks for the heads up @philraj
