### ISSUE TITLE
Request: Add a changelog

### ISSUE THREAD

**Issue by BerkeleyTrue** [paularmstrong/normalizr#185]
I'm attempting to debug in a breaking change introduced in 2.3

My first step is usually to run through the changelog, but to my surprise there is none to be found (At least to my eyes, but I have been known to miss things).

Also, want to say thanks for such an awesome project!

**Comment by paularmstrong** [comment]
@BerkeleyTrue development on v2.x is being halted. There is a changelog in the [release notes](https://github.com/paularmstrong/normalizr/releases)

All new development will be done in [v3](https://github.com/paularmstrong/normalizr/tree/normalizr3)
