### ISSUE TITLE
results for arrayOf returns array instead of map as of version 2.3.0

### ISSUE THREAD

**Issue by BerkeleyTrue** [paularmstrong/normalizr#186]
# Problem

Upgrading to 2.3.0 introduces a breaking change to the way `results` are returned.

It looks like results are now normalized when both values are the same. https://github.com/paularmstrong/normalizr/blob/master/src/index.js#L116

This is a breaking change and should result in a major bump and a warning to those who expect a keyed map in return regardless of the values of that map.

**Input**

Here's how I'm using normalizr:

```js
const challenge = new Schema('challenge', { idAttribute: 'dashedName' });
const block = new Schema('block', { idAttribute: 'dashedName' });
const superBlock = new Schema('superBlock', { idAttribute: 'dashedName' });

block.define({
  challenges: arrayOf(challenge)
});

superBlock.define({
  blocks: arrayOf(block)
});

const mapSchema = valuesOf(superBlock);
const map = {
  'getting-started': {
    dashedName: 'getting-started',
    blocks: [
      {
        dashedName: 'some-block',
        challenges: [{
          dashedName: 'some-challenge',
          ...
        },
        ...
       ],
        ...
      },
      ...
    ],
    ...
  },
   ...
};
normalize(map, mapSchema);
```

**Output**
Here is what has been the output up to 2.2.1
```js
 {
   result: {
  'getting-started': 'getting-started',
  'front-end-development-certification': 'front-end-development-certification',
  'data-visualization-certification': 'data-visualization-certification',
  'back-end-development-certification': 'back-end-development-certification',
  'video-challenges': 'video-challenges',
  'full-stack-development-certification': 'full-stack-development-certification',
  'coding-interview-preparation': 'coding-interview-preparation'
},
   entities: { ... }
}
```

Here is what I actually as of 2.3.0

```js
{
  result: [ [ 
  'getting-started',
  'front-end-development-certification',
  'data-visualization-certification',
  'back-end-development-certification',
  'video-challenges',
  'full-stack-development-certification',
  'coding-interview-preparation'
  ],
  entities: { ...}
}
```

**Comment by BerkeleyTrue** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/pull/12167

This breaking change is not fixed in `2.3.1`. Am I correct in assuming that this will not be fixed for the `2.0` branch of normalizr?

**Comment by paularmstrong** [comment]
@BerkeleyTrue correct. Feel free to fork and fix on your own if you don't plan on updating to 3.0 (which is available and stable). However, I highly recommend updating. We just did for mobile.twitter.com.  It was fairly smooth to update, even for an application with very heavy usage of normalizr.

**Comment by BerkeleyTrue** [comment]
> which is available and stable

Why is it still tagged as beta?

**Comment by paularmstrong** [comment]
1. Waiting on Typescript definitions
2. Allow people to report bugs. Stable means the API is not going to change.

**Comment by BerkeleyTrue** [comment]
> Stable means the API is not going to change.

Was 2.X stable?

**Comment by paularmstrong** [comment]
Yes.

**Comment by BerkeleyTrue** [comment]
I see
