### ISSUE TITLE
Wanted: Typescript definitions & tests for v3.0.0

### ISSUE THREAD

**Issue by paularmstrong** [paularmstrong/normalizr#189]
# Problem

@paularmstrong doesn't know typescript and is too lazy to learn

# Solution

Try to get someone from the community donate a little time adding a typescript definition file and tests for the [v3.0.0 branch](https://github.com/paularmstrong/normalizr/tree/normalizr3) before launch

**Comment by unindented** [comment]
@paularmstrong I volunteer for this. Can you give me a quick overview of the changes since `2.x`, to make it easier for me to type properly? I haven't been paying attention lately.

**Comment by paularmstrong** [comment]
I've got a changelog going [here](https://github.com/paularmstrong/normalizr/blob/normalizr3/CHANGELOG.md) and [docs here](https://github.com/paularmstrong/normalizr/blob/normalizr3/docs). Biggest change is that `normalize` doesn't have global options and everything's at the schema level now.

**Comment by unindented** [comment]
@paularmstrong I've started work on this. One thing I've noticed it that the `new schema.Entity()` syntax feels a bit weird, and is not very friendly to tree-shaking. If I want to use any schema, I have to import all of them:

```js
import { schema } from 'normalizr';
```

Why not export schemas directly, and get rid of the `schema` namespace?

**Comment by paularmstrong** [comment]
With such a small library, is tree-shaking really a concern? I always found that I needed to import at least 3 of `Schema`, `unionOf`, `arrayOf`, and `valuesOf` at the same time. The namespace keeps things clearly separated as wel, imo.

**Comment by unindented** [comment]
These days I measure every KB in my projects, but if you feel it helps with the UX then fair enough.

**Comment by paularmstrong** [comment]
Tree-shaking on normalizr v3 is going to save you about 3-100 bytes :) That, and you'll notice that `Array`, `Union`, and `Values` are all dependent on a shared `PolymorphicSchema`. So things utils like Webpack will just combine everything together anyway ¯\_(ツ)_/¯
