### ISSUE TITLE
Union schemaAttribute function not called when process strategy returns immutablejs record

### ISSUE THREAD

**Issue by kolpav** [paularmstrong/normalizr#199]
Does not call `schemaAttribute` function
```javascript
const removalLog = new schema.Entity(
  'removalLogs',
  {
    item: new schema.Union({
      post,
      comment
    }, (value, parent) => parent.itemType) // not called
  },
  {
    idAttribute: 'id',
    processStrategy: entity => new RemovalLogRecord(entity)
  }
)
```
Calls `schemaAttribute` function
```javascript
const removalLog = new schema.Entity(
  'removalLogs',
  {
    item: new schema.Union({
      post,
      comment
    }, (value, parent) => parent.itemType) // called
  },
  {
    idAttribute: 'id',
    processStrategy: entity => entity
  }
)
```

I would like to hold all my entites as immutable js records but it is not possible when using `schemaAttribute` function as it is never called for some reason.

**Comment by paularmstrong** [comment]
I suspect this is a problem with your `processStrategy` for you `removalLogs` Entity. As described in the docs, this is done before visiting the properties as defined by the schema. If `RemovalLogRecord` process strategy removes that value from the Entity, then it won't be visited or normalized.

> Strategy to use when pre-processing the entity. Use this method to add extra data, defaults, and/or completely change the entity before normalization is complete.

**Comment by kolpav** [comment]
What a quick response.
If you are faimiliar with `immutablejs` you propably know what I am trying to achieve basically conversion from js object to Records at the time of normalization. Previously I had ugly middleware for that. So I guess I am using `processStrategy` for something that it was not intended to, because if I convert it to `Record` there normalization logic then works with `Record` and not js object right? Do you think there could be similar callback as `processStrategy` but called after normalization? That would be a perfect place to convert to `Record` and I assume it would be very common use case.
Bellow is something that I also tried.
```javascript
const removalLog = new schema.Entity(
  'removalLogs',
  {
    item: new schema.Union({
      post,
      comment
    }, (value, parent, key) => { // not called
      console.log('schemaAttribute called')
      return parent.itemType
    }),
    createdBy: user,
    forTab: tab
  },
  {
    idAttribute: 'id',
    mergeStrategy: (entityA, entityB) => { // not called
      console.log('mergeStrategy called')
      const merged = entityA.merge(entityB)
      return merged
    },
    processStrategy: entity => {
      const normalized = new RemovalLogRecord(entity)
      console.log('normalized.itemType', normalized.itemType) // called, logs itemType 'comment' or 'post'
      return normalized
    }
  }
)
```

**Comment by paularmstrong** [comment]
Ah, you can't convert to ImmutableJS objects in `processEntity`. Normalizr only runs over plain JS objects. You'll have to do your conversion separately.

The argument passed to `processEntity` is not a normalized object. It is the `value` that *will* be normalized. Please re-read the documentation for [`processStrategy`](https://github.com/paularmstrong/normalizr/blob/master/docs/api.md#entitykey-definition---options--) carefully. There is no post-processing in Normalizr, so if you want something like that, you'll have to implement it separately.

**Comment by kolpav** [comment]
@paularmstrong Don't you think it would be a good idea to add post-processing when we already have pre-processing? It would not break anything and made this library more flexible for very common use case. Usually when you are using `normalizer` you should also have `immutablejs` it's recommended in many best practices. Here is very popular one [here](https://tonyhb.gitbooks.io/redux-without-profanity/content/normalizer.html).

> Some quick rules and reasoning for using Normalizr:
> 1. Use it directly within a callback from your API in your actions
> 2. After normalizing data convert entities to Immutable.js records.
> 3. Pass the normalized records to reducers. Reducers should only store these
> 4. When reducers only store normalized records it becomes super easy to query using reselect.

Would you accept PR for that because I would be extending `normalizr` for that anyway even if I have to sacrifice for future updates.

**Comment by paularmstrong** [comment]
There has never been post-processing in Normalizr, so that second point seems a bit ill-informed. If you're using Redux, your reducer should probably be the one converting plain objects to Immutable in whatever ADD_ENTITY-like action you're using.

**Comment by paularmstrong** [comment]
That being said, yes, it would be just another option to pass to `schema.Entity` and an extra line or two of code. However, I'm not convinced that it's necessary yet. You've got one use-case, but I really think it'd be better served, as I mentioned above, in your reducer.

**Comment by kolpav** [comment]
I guess my argument for such functionality is that you should be able to fully describe how each entity should be processed/normalized at both points in time `before` and `after` and I don't see a reason why we have only `before` option.

My use case is that I am using [this](https://github.com/reactjs/redux/blob/master/examples/real-world/src/reducers/index.js#L8-L14) approach from official redux examples for managing my entities state just modified for `immutablejs` and I have seen many people do the same.

If you would like your entities to be records you need to write some very clunky code which will convert each entity to its corresponding `Record` based just on its name and naming convetions in general which is awful IMHO. But I agree its just my use case. Bellow is how I was doing it till now.

```javascript
import { Map } from 'immutable'
import {
  PostRecord as posts,
  UserRecord as users,
  CommentRecord as comments
  /*
    .
    .
    .
    .
    .
    .
    .
    .
    .
    .
    .
  */
} from 'records'
import EntitiesModules from './entitiesModules'
const Records = {
  posts,
  users,
  comments
  /*
    .
    .
    .
    .
    .
    .
    .
    .
    .
    .
    .
    .
    .
    .
  */
}
export const initialState = Map()
export default (state = initialState, action) => {
  let entities
  if (action && Map.isMap(action.payload) && action.payload.has('entities')) {
    entities = action.payload.get('entities')
    entities.keySeq().forEach(x => {
      const Record = Records[x]
      if (Record) {
        const records = entities.get(x).map(x => new Record(x))
        entities = entities.set(x, records)
      } else {
        throw new Error(`Could not find a Record for ${x}`)
      }
    })
  }
  return entities
    ? state.mergeDeep(entities) // merge could be optimized
    : state
}
```
