### ISSUE TITLE
Wanted: Flux example

### ISSUE THREAD

**Issue by paularmstrong** [paularmstrong/normalizr#200]
# Problem

A simple and easy to follow example of using Normalizr with Flux would be a great addition to the [`/examples`](https://github.com/paularmstrong/normalizr/tree/master/examples) available.

# Solution

I haven't used Flux for over a year, so am not a good person to go and try implementing any example using it. This is a good chance for anyone looking to give back to open source to get started!

**Comment by isikfsc** [comment]
It would be great if this includes **many-to-many** relationships besides the more commonly exampled **one-to-many** relationships.

**Comment by wuweiweiwu** [comment]
@paularmstrong I can take this is no one has yet :)

**Comment by paularmstrong** [comment]
@wuweiweiwu Still open!

**Comment by wuweiweiwu** [comment]
@paularmstrong on it!

**Comment by konoufo** [comment]
This can be closed now right ?

**Comment by paularmstrong** [comment]
No, the PR was closed by the contributor before it was able to be merged.

**Comment by paularmstrong** [comment]
Seems like no one uses flux `¯\_(ツ)_/¯`
