### ISSUE TITLE
Docs: Output data

### ISSUE THREAD

**Issue by dehrax** [paularmstrong/normalizr#202]
# Problem

I am trying to wrap my head around what each method does, and it feels like I am hitting a stone wall. I have been sitting for hours just testing how to structure my schema, I have absolutely no clue what each method _actually_ does.

# Solution
Since all examples under the [API](https://github.com/paularmstrong/normalizr/blob/master/docs/api.md) provide input data, I think there should be a comment describing the output data. This enables me to actually see the pattern, rather than trying to understand it by reading. To summarize:

__Each example which has input data should provide a comment which describes the normalized output__

**Comment by paularmstrong** [comment]
Thanks for the report @dehrax. Docs can be pretty hard to write, especially when you already know all the ins-and-outs, you forget that others don't. Output should be added to the docs now!
