### ISSUE TITLE
index.d.ts - processStrategy methodreturns a strign instead of any

### ISSUE THREAD

**Issue by afnpires** [paularmstrong/normalizr#204]
# Problem

According to the documentation the `processStrategy` method should return an object.

processStrategy(value, parent, key): Strategy to use when pre-processing the entity. Use this method to add extra data, defaults, and/or completely change the entity before normalization is complete. Defaults to returning a shallow copy of the input entity.

But in the [index.d.ts](https://github.com/paularmstrong/normalizr/blob/master/index.d.ts#L2) the `processStartegy` is defined as a `SchemaFunction` which is a function that returns string.

Also in the [relationship example](https://github.com/paularmstrong/normalizr/blob/c85dfa0d7924fe2fbcbf526ffd5cbd0a3819f672/examples/relationships/schema.js#L32), `processStrategy` returns an object.

When I try to use normalizr in Typescript, the `processStrategy` is expecting to return a string instead of a object.

**Input**

```json
{
    "data": {
       "number": 1337,
       "components": [
           {
               "identifier": "smthg-smthg" ,
               "productCards": [
                  {
                        "identifier": "anthr-smthg-smthg"
                  }
               ]
           }
      ] 
   }
}
```

Here's how I'm using normalizr:

```Typescript
const components = new schema.Entity("components", {
           productCards: new schema.Array(productCards)
       }, {
               idAttribute: 'identifier',
               processStrategy: (value, parent, key) => {
                   return Object.assign({}, value, { dataId: parent.number}); 
               }
       });
```

**Output**

Here's what I expect to see when I run the above:

```js
{
    //...
   component: [ 
       {
             dataId: 1337,
            productCards: [
                 //...
            ]
       }
   ],
  productCards: [
   // ...
  ]
}
```

Here's what I *actually* see when I run the above:

Can't transpile the Typescript due to error in `processStrategy` return type, which expects a string.

Could the index.d.ts be modified to represent the library usage?

**Comment by paularmstrong** [comment]
Yep. Looks incorrect. Do you have time to fix in a PR? I can cut a build later today if it gets in. (Also, can you make sure this is handled in the typescript test? Thanks!

**Comment by afnpires** [comment]
Created #205.

Thanks!
