### ISSUE TITLE
Array/Polymorphic schema mapping should not require all entity types defined

### ISSUE THREAD

**Issue by Shaxmatist** [paularmstrong/normalizr#207]
The question about the `Array` [example](https://github.com/paularmstrong/normalizr/blob/master/docs/api.md#arraydefinition-schemaattribute):
>If your input data is an array of more than one type of entity, it is necessary to define a schema mapping.

1.  If `data` has a third type of entity, `guest` for example:
    ```js
    const data = [ { id: 1, type: 'admin' }, { id: 2, type: 'user' }, { id: 3, type: 'guest' } ];
    ```

2.  And `myArray` has no mapping for the `guest`:
    ```js
    const myArray = new schema.Array({
      admins: adminSchema,
      users: userSchema,
      // guest: guestSchema
    }, (input, parent, key) => `${input.type}s`);
    ```

Then the output is broken. Is it normal behavior? Do I need to know about all input data?

**Comment by paularmstrong** [comment]
You will need *something* to map unknowns to. See the test [here](https://github.com/paularmstrong/normalizr/blob/master/src/schemas/__tests__/Array.test.js#L44-L61) and output [here](https://github.com/paularmstrong/normalizr/blob/master/src/schemas/__tests__/__snapshots__/Array.test.js.snap#L54)

**Comment by paularmstrong** [comment]
Thinking about this further, I think you're onto a good point... It should be fairly easy to have the Polymorphic schema `normalizeValue` just retain the original input value if there is no schema found.
