### ISSUE TITLE
Recursive schema models

### ISSUE THREAD

**Issue by tutts** [paularmstrong/normalizr#209]
Hey :)

Having a bit of an issue trying to normalise my payload that contains a nested schema of the same type as the parent using

For example I have the initial schema (`Menu`) which has a child (`Sections`) which is an array of objects with `Sections`, which can go n deep.

```json
    {
      "id": 123,
      "sections": [{
        "id": 1,
        "sections": [{
          "id": 4,
          "sections": [{ "id": 5, "sections": [] }]
        }]
      }, {
        "id": 2,
        "sections":[]
      }, {
        "id": 3,
        "sections":[]
      }]
    }

```
I started by creating a `menu` schema, that had sections in the definition that linked to a `sections` schema, that worked for the first pass, but then wouldn't handle children of sections, so I added a subsequent definition within the `section` schema with the same name (was worth a shot) but it didn't work.

```javascript
    const section = new schema.Entity('sections')
    
    const sections = new schema.Entity('sections', {
      sections: section
    })
    
    const menu = new schema.Entity('menu', { 
      sections: [ sections ]
    })

    section.define({ sections })
```

I'm hoping to end up with the object below:

```json
    {
      "entities": {
        "menu": {
          "id": 123,
          "sections": [1, 2, 3]
        },
        "sections": [{
          "1": { "id": 1, "sections": [4] },
          "2": { "id": 2, "sections": [] },
          "3": { "id": 3, "sections": [] },
          "4": { "id": 4, "sections": [5] },
          "5": { "id": 5, "sections": [] },
        }]
      }
    }
```

Any idea or whether this is possible? Its been killing me all day (looked through SO and previously closed issues, and close but no cigar yet :( appreciate the help (and the lib, thanks guys!)

**Comment by paularmstrong** [comment]
Please don't ask for help on Issues. These are reserved for actual bugs or change proposals. I'll respond to your same question on StackOverflow.
