### ISSUE TITLE
Help needed: normalize by key:value

### ISSUE THREAD

**Issue by davecarlson** [paularmstrong/normalizr#212]
# Problem

I want to be able to pull out the category underneath the key  wp:term/0/0, where it's stored in a key:value relationship of taxonomy:category, which might not be the only taxonomy. I can't figure out how to do this using the schema !

Any ideas ?

<img width="374" alt="screen shot 2017-01-09 at 6 44 28 pm" src="https://cloud.githubusercontent.com/assets/299702/21778581/df884016-d69b-11e6-8448-0298f1c5d9f9.png">

The rest of my schema:

```
const articleSchema = new Schema('article', { idAttribute: 'slug' })
const tagSchema = new Schema('tag', { idAttribute: 'ID' })
const typeSchema = new Schema('type', { idAttribute: 'ID' })
const authorSchema = new Schema('author', { idAttribute: 'id' })

articleSchema.define({
  _embedded: {
    author: arrayOf(authorSchema)
  },
  acf: {
    article_type: typeSchema,
    article_tag: arrayOf(tagSchema)
  }
})

```

**Comment by paularmstrong** [comment]
Help questions will not be answered via Issues. These are reserved for bug reports and feature needs. Please ask help questions on [StackOverflow](http://stackoverflow.com/questions/tagged/normalizr)
