### ISSUE TITLE
Request for upgrade guide

### ISSUE THREAD

**Issue by axelson** [paularmstrong/normalizr#215]
Since v3 is a complete re-write with substantial API changes it would be helpful to have an official upgrade guide with side-by-side examples. I see "Please refer to the documentation for all changes." but in the docs I don't see a list of the changes from v2.

**Comment by paularmstrong** [comment]
Does this have enough? https://github.com/paularmstrong/normalizr/blob/master/CHANGELOG.md

**Comment by CrOrc** [comment]
Entity constructor changed. Now it has 3 arguments (key,.definition,options).
In v2 it accepted 2 arguments (key,options).

Previously was
```
import {Schema} from "normalizr";

const nestedSchema = new Schema("badge");
const schema=new Schema("users",{idAttribute:"$id"});
schema.define({badge: nestedSchema});
```

Now it should be
```
import {schema} from "normalizr";

const nestedSchema = new schema.Entity("badge");
const schema=new schema.Entity("users",{badge: nestedSchema},{idAttribute:"$id"});
```

**Comment by paularmstrong** [comment]
Closing, due to lack of activity for 1 month. Please reopen if there's still an issue.
