### ISSUE TITLE
Problem with denormalize method on recursive linked entities

### ISSUE THREAD

**Issue by maxsbelt** [paularmstrong/normalizr#216]
# Problem

Problem occurs when I tried to use `denormalize` method when `entities` object contains recursive keys.

**Input**

Example below describes the problem.

```js
const userEntity = new schema.Entity('users')
const reportEntity = new schema.Entity('reports')

userEntity.define({
  reports: [reportEntity]
})
reportEntity.define({
  user: userEntity
})

const entities = {
  reports: {
    1: {
      title: 'Report 1',
      user: 1
    },
    2: {
      title: 'Report 2',
      user: 2
    }
  },
  users: {
    1: {
      username: 'first',
      reports: [1, 2]
    },
    2: {
      username: 'second',
      reports: []
    }
  }
}

const item = denormalize(entities.reports[1], reportEntity, entities)
```

**Output**

Here's what I expect to see when I run the above:

```js
{
  title: 'Report 1',
  user: {
    username: 'first'
    reports: [
      {
        title: 'Report 1',
        user: 1 // or even without this key
      },
      {
        title: 'Report 2',
        user: 2 // or even without this key
      }
    ]
  }
}
```

Here's what I *actually* see when I run the above:

```js
RangeError: Maximum call stack size exceeded
```

**Comment by paularmstrong** [comment]
O_O You have actual recursive data? If you want your reports to give `user: <userId>`, then don't add the schema definition for `user: userEntity`. Wouldn't that solve the problem?

**Comment by maxsbelt** [comment]
Yes, I works with actual recursive data. It comes then 2 resources return nested entities with cross referenced items:

```js
// api/tasks/1/show
{
  id: 1,
  title: 'Task 1',
  comments: [
    {
      id: 1,
      comment: 'Comment 1 to task 1'
    }
  ]
}
```

and

```js
// api/comments/1/show
{
  id: 1,
  comment: 'Comment 1 to task 1',
  task: {
    id: 1,
    title: 'Task 1'
  }
}
```

Actually, I already solved my problem by creating a class that extends `schema.Entity` and redefined `denormalize` method.

I think you need to update documentation of `denormalize` method to specify that denormalizing of recursive schemas is not supported.

**Comment by paularmstrong** [comment]
@maxsbelt PRs accepted

**Comment by jpstrikesback** [comment]
Also discovered this :) @maxsbelt have a repo we could see? (or a PR?)

**Comment by paularmstrong** [comment]
Reopening, as #220 ended up not quite working as intended. See #233 for more information.
