### ISSUE TITLE
RangeError: The normalization form should be one of NFC, NFD, NFKC, NFKD

### ISSUE THREAD

**Issue by neverfox** [paularmstrong/normalizr#219]
# Problem

Getting `RangeError: The normalization form should be one of NFC, NFD, NFKC, NFKD` in version 3.1.0. The problem appears to be caused by [this line](visit), which is at one point called with `schema` as a string, thereby invoking [`String.prototype.normalize`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize).

**Input**

Here's how I'm using normalizr:

```js
import { normalize, schema } from 'normalizr';

// Add as much relevant code and input as possible.
const myData = [{
  id: 1
}];
const mySchema = new schema.Array('myschema');
normalize(myData, mySchema);
```

**Output**

Here's what I expect to see when I run the above:

```js
{
    result: [1],
    entities: { ... }
}
```

Here's what I *actually* see when I run the above:

```
RangeError: The normalization form should be one of NFC, NFD, NFKC, NFKD.
    at String.normalize (native)
    at visit (webpack:///./~/normalizr/dist/index.js?:437:17)
    at ArraySchema.normalizeValue (webpack:///./~/normalizr/dist/index.js?:275:29)
    at eval (webpack:///./~/normalizr/dist/index.js?:373:23)
    at Array.map (native)
    at ArraySchema.normalize$2 (webpack:///./~/normalizr/dist/index.js?:372:21)
    at visit (webpack:///./~/normalizr/dist/index.js?:437:17)
    at normalize$1 (webpack:///./~/normalizr/dist/index.js?:473:16)
    ...
<anonymous>:23:92)
```

**Comment by maxsbelt** [comment]
Take a look at the [schema.Array](https://github.com/paularmstrong/normalizr/blob/master/docs/api.md#usage-2) documentation carefully. You need to pass an `schema.Entity` object inside `schema.Array` schema constructor instead of `string`.

**Comment by neverfox** [comment]
Ah, thank you. I can't believe I missed that.
