### ISSUE TITLE
denormalize with immutable js

### ISSUE THREAD

**Issue by jchen527** [paularmstrong/normalizr#222]
Will support be added for denormalizing immutable js objects?

**Comment by paularmstrong** [comment]
No. (This is one of the reasons why I hesitated adding it in the first place–everyone's got their own setup and it's too hard to accommodate all.)

**Comment by jcarbo** [comment]
I just put up a PR to add support for this (https://github.com/paularmstrong/normalizr/pull/228) that only adds adds ~70 bytes (compressed) and ~40 bytes (minified + compressed) and doesn't add any external dependencies.

As I mentioned in the description of that PR, it seems that most places I've seen that suggest using `normalizr` also suggest using an immutable store for entities. Given that it's such a common use-case, it would be great if this lib could support it out of the box.

I'm currently using https://github.com/gpbl/denormalizr, which I contributed immutable support to in the same way (https://github.com/gpbl/denormalizr/pull/12). I'd love to drop the dependency though!
