### ISSUE TITLE
getAttributeId instance method

### ISSUE THREAD

**Issue by karlguillotte** [paularmstrong/normalizr#223]
I am upgrading normilzr to latest from 2.x. 

I am using the instance method `getAttributeId` in my code base. However, it seems that this method has been removed. Any plan on bringing back that function? Or making the `_getId` public?

Thanks for the update and the library! 
Karl

**Comment by karlguillotte** [comment]
Ah! Sorry it is public already as `getId`. 

Perhaps, it could be added to the documentation. 

Thanks!

**Comment by paularmstrong** [comment]
It's not in the documentation because it's not really meant to be publicly visible outside of normalizr. Why are you using it? I don't understand the context for this.

**Comment by karlguillotte** [comment]
Here is a bit of my use-case! 

I am using normalizr in my Redux store along with reselect. I have a selector that take entities for a given schema and transform into GeoJSON objects so I can display them on a map (using Mapbox GL). Inside my selector I am using `getId` to make sure that my GeoJSON objects use the same ids. 

Hope it helps. Do not hesitate if you have concerns/questions or it not clear.
