### ISSUE TITLE
Point JSONAPI spec consumers to another package

### ISSUE THREAD

**Issue by paularmstrong** [paularmstrong/normalizr#224]
# Problem

Normalizr is awesome. However, it really isn't very good for [JSONAPI](http://jsonapi.org). JSONAPI is great in theory, but it's incredibly difficult to use with redux/flux style state management.

# Solution

The documentation should, in a very clear manner, point to another package.

@stevenpetryk's [jsonapi-normalizer](https://github.com/stevenpetryk/jsonapi-normalizer) seems like a good candidate.

**Comment by yury-dymov** [comment]
May I also suggest my implementation [json-api-normalizer](https://github.com/yury-dymov/json-api-normalizer)?
