### ISSUE TITLE
denormalize crashes when a nested entity is originally null

### ISSUE THREAD

**Issue by ChenRoth** [paularmstrong/normalizr#225]
# Problem

`denormalize` crashes when a nested entity is originally `null`

**Input**

```js
const child = new schema.Entity('children')

const user = new schema.Entity('users', {
  children: [child],
})

const mySchema = { users: [user] }

const entities = {
  users: {
    1: { id: 1, children: [{ c: 1 }, { c: 2 }] },
    2: { id: 2, children: null }
  }
};
const denormalizedData = denormalize({ users: [1, 2] }, mySchema, entities);
```

**Output**

Here's what I expect to see when I run the above:

```js
{ users: 
   [ { id: 1, children: [ { c: 1 }, { c: 2 } ] },
     { id: 2, children: null } ] }
```

Here's what I *actually* see when I run the above:

```
.../normalizr/dist/src/schemas/Array.js:51
  return input.map(function (entityOrId) {
              ^

TypeError: Cannot read property 'map' of null
```

**Comment by CoinGame** [comment]
I'm running into this problem right now. Is there a suggested workaround other than ensuring all null entity values are empty arrays first?

**Comment by ChenRoth** [comment]
@CoinGame not that i know of.. i replaced the `null` with an empty list too.
If I ever get the time soon, I'll try to submit a fix

**Comment by paularmstrong** [comment]
This should be a simple fix in the ArraySchema denormalize loop. Definitely open to PRs, thought I won't be back until some time next week.

**Comment by CoinGame** [comment]
I'm still a  bit of a javascript noob, so I'm not sure if this is a safe change. I modified Array.js to check that the value was an array before trying to map. It's not breaking for me anymore. 

```javascript
  return typeof(input) === Array ? input.map(function (entityOrId) {
    return unvisit(entityOrId, schema, entities);
  }) : null;
```
https://github.com/paularmstrong/normalizr/blob/master/src/schemas/Array.js#L24-L27

**Comment by paularmstrong** [comment]
I had to overhaul a few things and this was fixed as a result. Will be out in the next release (hopefully this week)

**Comment by CoinGame** [comment]
Fantastic. Thank you for the quick update.
