### ISSUE TITLE
v3 upgrade, how to do getItemSchema() in v3?

### ISSUE THREAD

**Issue by littlehome-eugene** [paularmstrong/normalizr#230]
I think in v2, one could use getItemSchema to get single schema from array schema.

How can I do similar in v3?

**Comment by paularmstrong** [comment]
Please format your issue using the [issue template](https://raw.githubusercontent.com/paularmstrong/normalizr/master/.github/ISSUE_TEMPLATE.md) that was provided. Include sample code on what you were doing and how you expect it to continue working.
