### ISSUE TITLE
Denormalize method replace a key with the entity only the first entry

### ISSUE THREAD

**Issue by Serenya** [paularmstrong/normalizr#233]
I don't know if it's expected behavior or not, but lets take example from the documentation of denormalize method and extend it a little so that user Entity contains reference to a child Entity:
```javascript
import { denormalize, schema } from 'normalizr';

const mentor = new schema.Entity('mentors');
const user = new schema.Entity('users', {
  mentor: mentor
});

const mySchema = { users: [ user ] }
const entities = { users: { '1': { id: 1, mentor: 3 }, '2': { id: 2, mentor: 3 } , mentors: { '3': { id: 3, name: 'John' } } } };
const denormalizedData = denormalize({ users: [ 1, 2 ] }, mySchema, entities);
```

The output is:
```javascript
{ 
  users: [
    { id: 1, mentor: { id: 3, name: 'John' } },
    { id: 2, mentor: 3 }
  ]
}
```
I was expecting something like this:
```javascript
{ 
  users: [
    { id: 1, mentor: { id: 3, name: 'John' } },
    { id: 2, mentor: { id: 3, name: 'John' } }
  ]
}
```
I've found out that in this file https://github.com/paularmstrong/normalizr/blob/master/src/index.js
under method getEntities, you may find the guilty code:
```javascript
const id = schema.getId(entity);
if (visitedEntities[schemaKey][id]) {
  return id;
}
```
Do I understand the concept of denormalization wrong? Is it expected behavior? What is the purpose of having visitedEntities variable?

**Comment by paularmstrong** [comment]
Yep, looks like a bug that appeared in the newest release. We added some recursive-denormalization handling, but it looks like it's not taking into account items seen on multiple paths.

**Comment by paularmstrong** [comment]
PRs appreciated. I don't have time to look into it at the moment. If no one can take this on, I might have to revert it. CC @maxsbelt

**Comment by paularmstrong** [comment]
v3.2.1 is out and reverts the incorrect behavior.

**Comment by Serenya** [comment]
Well done, thanks!
