### ISSUE TITLE
Ids of missing data are removed when denormalizing

### ISSUE THREAD

**Issue by PhilippSpo** [paularmstrong/normalizr#237]
First of all, thanks for improving the `denormalize` function. It is a great help in my application 🎉

# Problem

At the moment when there can't be any data found for a given Id during denormalization, the Id is replaced by `undefined`. This is fine in cases where the date really is missing. But there are cases where you intentionally did not fetch this data and are just interested in the Id that references more data.

**Input**

In the following example, I fetched a user that has some references to his friends. I did not however reference expand his friends because I am just interested in the number of friends.
Here's how I would use normalizr:

```js
const userSchema = new schema.Entity('users');
userSchema.define({
  fiends: [userSchema]
})
const entities = {
  users: {
    'user-id-5': {
      id: 'user-id-5',
      friends: ['user-id-1', 'user-id-2', 'user-id-4'],
    }
  }
}
denormalize(['user-id-5'], [userSchema], entities);
```

**Output**

Here's what I expect to see when I run the above:

```js
{
  id: 'user-id-5',
  friends: ['user-id-1', 'user-id-2', 'user-id-4'],
}
```

Here's what I *actually* see when I run the above:

```js
{
  id: 'user-id-5',
  friends: [undefined, undefined, undefined],
}
```

**Comment by paularmstrong** [comment]
What version are you using? v3.2.1 should have fixed this via #232

**Comment by PhilippSpo** [comment]
Yup, I am using `3.2.1`. Just upgraded a couple of minutes ago.
Before upgrading it would replace the Id with an empty object. Now it replaces it with `undefined`

**Comment by paularmstrong** [comment]
Turns out, this is actually intentional. I think we also expect this in Twitter https://github.com/paularmstrong/normalizr/blob/e1d7066a585581e3c658704fbd5317f435bb82c8/src/schemas/__tests__/Entity.test.js#L138-L158

The reason for this is that, typically, you're denormalizing to pass through to React components. When the components expect an object, `user: React.PropTypes.object` for example, passing a number in would be incorrect.

Could you, instead, pass a schema definition of how you actually expect your data to look? In your example, I'd expect no `{ friends: [ userSchema ] }` to exist.

**Comment by PhilippSpo** [comment]
Yeah true, good point. 👍 

This means that I have to define my schema, again and again, depending on what I am expanding in which scenario, though. A bit tedious, but I guess it will work.

However, I am still not sure I fully understand the use case.

It could even lead to false positives:
You think the user has no friends just because you forgot to reference expand the friends. In this case, it might actually be useful that the react prop type checking tells me that the passed friends are not objects but numbers.

**Comment by MayankLogiciel** [comment]
@PhilippSpo wasn't it due to misspelled word fiends ??

`userSchema.define({
  fiends: [userSchema]
})`

**Comment by PhilippSpo** [comment]
Tbh I don't remember anymore. Maybe you are right @MayankLogiciel 😅.

Anyways, I don't have this issue anymore.
