### ISSUE TITLE
Denormalizing Immutable Lists is different from denormalizing Arrays

### ISSUE THREAD

**Issue by jreut** [paularmstrong/normalizr#240]
# Problem

Keys of `Immutable.Map`s whose values are `Immutable.List`s are not denormalized in the same way as keys of `Object`s whose values are `Array`s.

**Input**

Here's how I'm using normalizr:

```js
const bar = new schema.Entity('bars')
const foo = new schema.Entity('foos', { bars: [ bar ] })
const data = {
  id: 7,
  bars: [
    { id: 1 },
    { id: 2 }
  ]
}
const immutableEntities = fromJS(normalized).get('entities')
const denormalized = denormalize(data.id, foo, immutableEntities).toJS()
```

**Output**

Here's what I expect to see when I run the above:

```js
{
  id: 7,
  bars: [
    { id: 1 },
    { id: 2 }
  ]
}
```

Here's what I *actually* see when I run the above:

```js
{
  id: 7,
  bars: [ 1, 2 ]
}
```

---

I created a [small repository](https://github.com/jreut/normalize-immutable-list/blob/master/index.test.js) with two tests comparing behavior between vanilla objects and Immutable objects.

**Comment by paularmstrong** [comment]
@jreut Can you try against #239?

**Comment by jreut** [comment]
@paularmstrong sure thing! Thanks for such a quick response. I get the same behavior against #239. I'm happy to let this issue sit for a while; I just encountered it while trying out the new `denormalize` feature. Just let me know if there's anything else you'd like me to do.

**Comment by jreut** [comment]
Especially given the related issues that have been opened in the past month, perhaps this is something worth looking in to. @paularmstrong would you like me to open a PR for this?

I wanted to give you some time to get #239 merged, since that was a reasonably large change, and I didn't want to give you the headache of integrating.

**Comment by paularmstrong** [comment]
PR: yes please. Immutable support in Normalizr is a completely community-supported feature. #239 has been merged for a while.

**Comment by jreut** [comment]
I apologize for any confusion, but it looks like v3.2.2 fixes this behavior. Either I didn't correctly test against #239 last month or something else changed since that time. I'll open a PR if I encounter any other issues, but this seems to be all set. Thanks!
