### ISSUE TITLE
Export single schema type?

### ISSUE THREAD

**Issue by roderickhsiao** [paularmstrong/normalizr#242]
# Problem
Currently we will need to do like
```js
import { schema } from 'normalizr';
```
which will brings in all the other type of schema (around `4.8kb` gzip)
https://github.com/paularmstrong/normalizr/blob/master/src/index.js#L36-L42

# Suggestion
will be good if we can export individual file so that we can minimize client side bundle size to require on the needed.

How do you think?

**Comment by paularmstrong** [comment]
Many of the schema are tightly coupled, as they share a base schema. The only benefit you'd get is if you only ever used `Entity` and nothing else. I don't think splitting them apart will be beneficial in the long run.

**Comment by roderickhsiao** [comment]
Thanks for the reply
