### ISSUE TITLE
Normalizing recursive payload doesn't work

### ISSUE THREAD

**Issue by GertjanReynaert** [paularmstrong/normalizr#243]
# Problem

Normalizing recursive payload gives an error instead of normalizing the payload.

(I've seen some work on recursive issues in denormalize, but I wasn't sure if you were aware of this issue when normalizing payload, that's why I created this issue)

**Input**

I created a failing spec to best illustrate the issue:
https://github.com/GertjanReynaert/normalizr/blob/gr-failing-recursive-normalize/src/__tests__/index.test.js#L53

**Output**

Instead of getting a normalized output, I get the following error:
```
 FAIL  src/__tests__/index.test.js
  ● normalize › normalizes recursive payloads

    TypeError: Cannot read property 'normalize' of undefined

      at visit (src/index.js:18:16)
      at src/schemas/Array.js:21:79
      at Array.map (native)
      at normalize (src/schemas/Array.js:21:17)
      at visit (src/index.js:15:12)
      at src/schemas/Entity.js:56:34
      at Array.forEach (native)
      at EntitySchema.normalize (src/schemas/Entity.js:53:32)
      at visit (src/index.js:18:17)
      at src/schemas/Array.js:21:79
      at Array.map (native)
      at normalize (src/schemas/Array.js:21:17)
      at visit (src/index.js:15:12)
      at normalize (src/index.js:52:16)
      at Object.<anonymous> (src/__tests__/index.test.js:81:55)
```

**Comment by paularmstrong** [comment]
#216, #239

**Comment by GertjanReynaert** [comment]
@paularmstrong I was aware of these two issues, but these are related to `DEnormalizing`. I'm not sure if the issue I have with `normalizing` is related to those denormalizing issues.

**Comment by paularmstrong** [comment]
Uh... normalizing recursive? My initial reaction is... don't do that. Normalizr was written for JSON data, which cannot be recursive.

**Comment by GertjanReynaert** [comment]
@paularmstrong I agree with your initial reaction, but I can't change the payload on our api so that's not really an option.

The recursive normalization as shown in my [failing spec](https://github.com/paularmstrong/normalizr/pull/244) worked pre 3.x, but in 3.x it no longer does.

This isn't that big of an issue to me, since I can work around it locally, but I thought you might want to know about this regression.
