### ISSUE TITLE
modify data upon denormalization

### ISSUE THREAD

**Issue by fxck** [paularmstrong/normalizr#245]
Now that recursive normalization / denomalizion is working I have another problem.

Imagine this situation I have people / brands that are recursively linked:

```typescript
peopleEntitySchema.define({
  media: mediaListSchema,
  brands: brandsListSchema
});
```

```typescript
brandsEntitySchema.define({
  media: mediaListSchema,
  people: peopleListSchema
});
```

Now I need to do some additional manipulation with both people in brands and brands in people, say that I have an array of images under `media` key and I want to extract one with particular `context` and put it under `avatar_` key for easy consumption in templates, so I do something like this..

```typescript
function getModifiedPeople(denormalizedData) {
  return denormalizedData.map(entity => ({
     ...entity,
     avatar_: getAvatar(entity.media),
     brands_: getModifiedBrands(entity.brands)
  }));
}

function getModifiedBrands(denormalizedData) {
  return denormalizedData.map(entity => ({
     ...entity,
     avatar_: getAvatar(entity.media),
     people_: getModifiedPeople(entity.people)
  }));
}
```

..and I end obviously end up with maximum call stack exceeded, so I'd either have to implement my own handler of circular references or put a flag inside my functions to simply not do this on the deeper levels, none of which is really ideal.

So what I imagine would be nice would be to have something like `processStrategy` for `denormalize`, which would allow me to modify the data as I need, while utilising whatever way normalizr currently handles circular references.

What do you think @paularmstrong @jcarbo  @andyhite is it something worth exploring and adding?

**Comment by fxck** [comment]
I'm having a little hard time navigating the new codebase, but I managed to put this together https://github.com/fxck/normalizr/commit/68a5094659c476171631f7dc1c56d09d3b66f173 

It works, but it's not *quite* there, given this code

```typescript
    function getAvatar(entity) {
      if (entity && entity.media) {
        return entity.media.find((itm) => itm.context === 'avatar');
      } else {
        return undefined;
      }
    }

    function denormalizeStrategy(entity) {
      return {
        ...entity,
        avatar_: getAvatar(entity)
      };
    }

    const brandsSchema = new schema.Entity('brands', {}, {
      denormalizeStrategy
    });

    const peopleSchema = new schema.Entity('people', {},  {
      denormalizeStrategy
    });

    const mediaSchema = new schema.Entity('media');

    const brandsListSchema = new schema.Array(brandsSchema);
    const peopleListSchema = new schema.Array(peopleSchema);
    const mediaListSchema = new schema.Array(mediaSchema);

    brandsSchema.define({
      media: mediaListSchema,
      people: peopleListSchema
    });

    peopleSchema.define({
      media: mediaListSchema,
      brands: brandsListSchema
    });

    const brands = [{
      id: 1,
      name: 'foo brand',
      media: [{
        id: 1,
        context: 'avatar',
        url: 'brand.jpg'
      }],
      people: [
        {
          id: 1,
          name: 'foo person',
          media: [{
            id: 2,
            context: 'avatar',
            url: 'person.jpg'
          }]
        }
      ]
    }];

    const people = [{
      id: 1,
      name: 'foo person',
      media: [{
        id: 2,
        context: 'avatar',
        url: 'person.jpg'
      }],
      brands: [
        {
          id: 1,
          name: 'foo brand',
          media: [{
            id: 1,
            context: 'avatar',
            url: 'brand.jpg'
          }]
        }
      ]
    }];

    const brandsNormalized = normalize(brands, brandsListSchema);
    const peopleNormalized = normalize(people, peopleListSchema);

    const entities = mergeWith(
      {},
      brandsNormalized.entities,
      peopleNormalized.entities,
      _customizer
    );

    function _customizer(objValue, srcValue) {
      if (isArray(objValue)) {
        return [ ...srcValue ];
      }
    }

    const brandsDenormalized = denormalize(brandsNormalized.result, brandsListSchema, entities);

    console.log(brandsDenormalized);
```


it logs:

```
[{
  id: 1,
  name: 'foo brand',
  media: [ ... ],
  avatar_: { ... }, // first level of brands, avatar_ is there
  people: [{
    id: 1,
    name: 'foo person',
    avatar_: { ... },
    media: [ ... ],
    brands: [{
      id: 1,
      name: 'foo brand',
      media: [ ... ], // second level (and any subsequent level) of brands, avatar_ is missing
      people: [{
        id: 1,
        name: 'foo person',
        avatar_: { ... },
        media: [ ... ],
        brands: [ ... ]
      }]
    }]
  }]
}]

```

it looks as if it's applying the transformation only on the first level of the main entity (brands in this case), but it works fine on all the levels of sub entities (people in this case)

**Comment by paularmstrong** [comment]
I'm very hesitant to go down this path with `denormalize`. The point of Normalizr is to process this information up front and once, not after the fact and potentially multiple times. This kind of processing seems like it is much better suited for 1) up front with `normalize` or 2) in your state manager, like Redux's reducers.

**Comment by fxck** [comment]
I wonder how I could do this up front with `normalize`. As far as I can tell `denormalize` doesn't take in account `processStrategy`, which seems like the only sensible place to do this (this particular use case where I need to take one entity from media, which is a normalized array of media entities and put it under an extra key), so I'd end up with either just an id of media entity and I'd have to put it back together manually in my selectors (and I'd be back to `maximum call stack exceeded` in circular references) or I would leave it as raw, un-normalized, data, but then it wouldn't be reference to media entities and it'd beat the purpose why I normalize media entities (or any entity) in the first place.

As for keeping this in the state.. I guess I could have a map of `entity name -> entity id -> id of media entity with context "avatar"` in my state, which would be similar to how I save my normalizr entities, but it feels like the overhead would be even bigger than doing this in `denormalize`. Media is not the only thing I would use this on, so I'd end up with a big amount of various maps, which would either be pretty hard to consume in templates, or I'd put them back together in selectors, but then I'd end up with `maximum call stack exceeded` in circular references and I'd be where I started.

Maybe I'm not thinking about this right, but `denormalize` still feel like a decent place to do this, mostly because of it's ability to deal with those circular references.

**Comment by jcarbo** [comment]
I think what @paularmstrong was suggesting was to get the data into the format you want to *before* normalization. For instance:

```js
brandsSchema.define({
  media: mediaListSchema,
  people: peopleListSchema,
  avatar: mediaSchema,
});

peopleSchema.define({
  media: mediaListSchema,
  brands: brandsListSchema,
  avatar: mediaSchema,
});

const people = [{
  id: 1,
  name: 'foo person',
  media: [{
    id: 2,
    context: 'avatar',
    url: 'person.jpg'
  }],
  brands: [
    {
      id: 1,
      name: 'foo brand',
      media: [{
        id: 1,
        context: 'avatar',
        url: 'brand.jpg'
      }]
    }
  ]
}];
const processedPeople = people.map(
  (person) => ({
    ...person,
    avatar: getAvatar(person)
  })
)
const normalizedPeople = normalize(people, peopleListSchema)
```

I consider the data store of normalized data as a client-side relational DB. Ideally you put the data into the "DB" in the format you expect it upon denormalization.

**Comment by fxck** [comment]
Hm, yeah, that might work. Let me check if I'd fit the other use-cases I had for denormalize as well.

**Comment by fxck** [comment]
Let me just close this, while I still think there might be use cases for what I proposed, what @jcarbo's suggesting is perfectly valid approach as well.
