### ISSUE TITLE
normalizr is not built to work standalone in browser environments

### ISSUE THREAD

**Issue by codingnube** [paularmstrong/normalizr#249]
**Are we missing something?**

We are developing a webapp using [polymer-cli](https://github.com/Polymer/polymer-cli)

```js
<script src="../node_modules/normalizr/dist/normalizr.js"></script>
<script src="../node_modules/redux/dist/redux.js"></script>
```
normalizr is showing an error in Chrome dev. tools

```js
Uncaught ReferenceError: exports is not defined at normalizr.js:3
```

Redux works fine. Both from the local script & this [CDN](https://cdnjs.cloudflare.com/ajax/libs/redux/3.6.0/redux.js) as well.

Please help. BTW, any CDN which hosts normalizr? *(We did search, But, no luck so far :sweat_drops:)*

**Comment by paularmstrong** [comment]
Normalizr hasn't been built for use directly in browser since v2. If you'd like to have that fixed, a PR would be great!

As for CDN, that's up to the community to get it hosted somewhere.

**Comment by codingnube** [comment]
@paularmstrong Thanks for your reply & the PR suggestion. Our team has never written a node module :blush: (Hope some other community member will send you a PR soon)

**Comment by robertlagrant** [comment]
@paularmstrong if you have time, do you mind elaborating on why the in-browser normalisation feature wasn't considered worth keeping in the rewrite? My assumption when i heard about this project was that it'd be very useful in the browser, e.g. for post-hydration calls from the browser to  a son API endpoint, so I'm a bit confused!

**Comment by paularmstrong** [comment]
@robertlagrant It totally works in the browser. We use it at Twitter in the browser.

What doesn't work is that we didn't add a build step to make it work as a standalone script in the browser. The recommended way to use normalizr is in conjunction with webpack, browserify, require.js, etc.

**Comment by robertlagrant** [comment]
Gotcha. Thanks. That makes...way more sense :-)

**Comment by IamTheHttp** [comment]
@paularmstrong  I'd be willing to write a build process for this project.
I see the current build simply runs babel and creates a dist directory, would changing that to webpack be okay?

**Comment by paularmstrong** [comment]
@IamTheHttp That sounds overly complicated. We can just add an `iife` format output to the rollup config.

However, I REALLY don't recommend people use JavaScript without bundling into their application.
