### ISSUE TITLE
The example of redux does not work when not installing presets in normalizr-root directory or in global

### ISSUE THREAD

**Issue by harukaeru** [paularmstrong/normalizr#250]
# Problem
I couldn't start an example well.

**Input and Output**
```sh
$ git clone git@github.com:paularmstrong/normalizr.git
$ cd normalizr/examples/redux
$ yarn
$ npm run start
/Users/usrNeko/normalizr/examples/redux/node_modules/babel-core/lib/transformation/file/options/option-manager.js:334
        throw e;
        ^

Error: Couldn't find preset "es2015" relative to directory "/Users/usrNeko/normalizr"
```

Because of this error, I ran the command `yarn` in root directory of normalizr. It was solved.

I also watched the others but these documents are with comments `# from root directory` like the following
```sh
# from the root directory:
yarn
# from this directory:
../../node_modules/.bin/babel-node ./index.js
```
So I think it should be fixed about the example of redux as well.

**Comment by paularmstrong** [comment]
I think this is maybe a documentation issue instead. You will need to run `yarn` in the root level directory first.

**Comment by harukaeru** [comment]
Yes, that's why I suggested it has some value to be fixed.
