### ISSUE TITLE
Generate unique ids during normalization

### ISSUE THREAD

**Issue by goldhand** [paularmstrong/normalizr#256]
# Problem

I've read through #116 and #201 and haven't found a good solution for generating unique IDs during the normalization process. This would be very useful because it's sometimes impossible to generate a unique id using the entity's values (even a base64 or md5 hash of the object would return the same value in some cases). I am working with deeply nested, circular entities with no unique ids in the data. 

Is it possible to maybe assign the output of the `idAttribute` function rather than calling it multiple times (generating different uids then)?

**Desired Solution** 
```js
const header = new schema.Entity('header', {}, {idAttribute: () => cuid()});

const mySchema = new schema.Entity('module', {
  header: [header],
});

const data = {
  id: 'foo',
  header: [
    {  id: 'foo', value: 'bar' },
  ],
};
```
**Desired output of `normalize(data, mySchema)`**
```
{ entities: {
  module: {
    aaaaaaaaa: {
    id: 'foo',
    uid: 'aaaaaaaaa',
    header: [ 'bbbbbbb' ],
  } },
  header: {
    bbbbbb: {
    id: 'foo',
    value: 'bar',
    uid: 'bbbbbbb',
  } },
} };
```
**Actual output of `normalize(data, mySchema)`**
```
{ entities: {
  module: {
    aaaaaaaaa: {
    id: 'foo',
    uid: 'aaaaaaaaa',
    header: [ 'bbbbbbb' ],  <-- idAttribute called once returns this
  } },
  header: {
    ccccccc: {
    id: 'foo',
    value: 'bar',
    uid: 'cccccc',  <-- idAttribute called second time returns different value than in relationship
  } },
} };
```

My current solution works but I think it could have side effects. It is to mutate the input values, adding a `uid` attribute in the `processStrategy` callback.
The thought behind this solution is documented more [here](http://stackoverflow.com/questions/39681284/normalizr-how-to-generate-slug-id-related-to-parent-entity/43665603#43665603)

**Current Solution**
```js
import {schema} from 'normalizr';
import cuid from 'cuid';

/**
 * Mutates the entity adding a unique id if one doesnt exist
 * @param {Object} value - entity
 * @returns {string} uid
 */
const processStrategy = value => {
  if (!Object.prototype.hasOwnProperty.call(value, 'uid')) value.uid = cuid();
  return {...value};
};

const header = new schema.Entity('header', {}, {idAttribute: 'uid', processStrategy});

const composite = new schema.Entity('composite', {
  header: [header],
}, {idAttribute: 'uid', processStrategy});

const collection = new schema.Entity('collection', {
  header: [header],
}, {idAttribute: 'uid', processStrategy});

// add circular reference
composite.define({
  collection: [collection],
});

// add circular reference
collection.define({
  composite: [composite],
});

const mySchema = new schema.Entity('module', {
  header: [header],
  collection: [collection],
  composite: [composite],
}, {idAttribute: 'uid', processStrategy});

```

**Comment by paularmstrong** [comment]
Normalizr is never going to be able to generate unique IDs for you. We don't do any memoization or anything internally, as that would be unnecessary for most people.
 
Your working solution is *okay*, but will fail if you receive one of these entities again later from another API endpoint.

My recommendation would be to find something that's constant and unique on your entities and use that as something to generate unique IDs from.
