### ISSUE TITLE
Composite/Calculated ID field requires input mutation

### ISSUE THREAD

**Issue by Stenerson** [paularmstrong/normalizr#258]
# Problem

Adding a composite ID in `processStrategy` is not being transferred to the normalized entity correctly unless I mutate the `value` within `processStrategy`.

**Input**

Here's how I'm using normalizr:

```js
const myData = {
  patrons: [
    {
      id: 1,
      name: "Esther",
      guest_id: null,
      ...other fields that actually require normalization
    },
    {
      id: 1,
      name: "Tom",
      guest_id: 22,
      ...other fields that actually require normalization
    },
  ]
};

const patronProcessStrategy = (value, parent, key) => {
  // Determine composite key
  const compositeId = value.guest_id ? `${value.id}-${value.guest_id}` : value.id;
  // Return a non-mutated version of the value with the key added
  return { ...value, compositeId };
};
const patronsSchema = new schema.Entity('patrons', undefined, {
  idAttribute: 'compositeId',
  processStrategy: patronProcessStrategy,
});

normalize(myData, [patronsSchema]);
```

**Output**

Here's what I expect to see when I run the above:

```js
{
    result: [1, 1-22],
    entities: {
      patrons: {
        1: { ... },
        1-22: { ... },
      }
    }
}
```

Here's what I *actually* see when I run the above:

```js
{
    result: [undefined, undefined],
    entities: 
      patrons: { undefined: { ... } }
}
```

**Possible Solution**
If I mutate the value in `processStrategy` **I get the output I expect**. This approach was [*kind of* validated](https://github.com/paularmstrong/normalizr/issues/256#issuecomment-298128047) in #256 but generally, mutation is bad and it seems especially so here.

```js
const patronProcessStrategy = (value, parent, key) => {
  // Determine composite key
  const compositeId = value.guest_id ? `${value.id}-${value.guest_id}` : value.id;
  // Mutate!
  value.compositeId = compositeId;
  // Return copy of the (already mutated object)
  return { ...value };
};
```

Based on the [suggestions](https://github.com/paularmstrong/normalizr/blob/master/docs/api.md#entitykey-definition---options--), I'd like to avoid mutating the object. I can see from the [source](https://github.com/paularmstrong/normalizr/blob/2d60121de8810e6694a353c815f4f93a9424ef5d/src/index.js#L23) that the original input object is used to actually get the entity's ID for the normalized output. I'm not sure if this is intentional or a bug but I'd think that we should be able to use the `processedEntity` to get the key here.

**Comment by paularmstrong** [comment]
Looks like an easy change here: https://github.com/paularmstrong/normalizr/blob/a4c7e725469b9ac87c69c3daf37fc04a5c5bd76f/src/schemas/Entity.js#L61. Should be able to pass `processedEntity` instead of `input`.

**Comment by Stenerson** [comment]
I agree. My only concerns were/are:
- Is this intentional?
- (If no) Is this a common law feature at this point? (i.e. will this break people's apps counting on it continue working the way that it currently does?)

**Comment by paularmstrong** [comment]
Not intentional. If a test doesn't break, then I wouldn't expect it to break anything. Also, it really does look like a bug. I have the same expectation that you do: this should work without mutating the `input`.

**Comment by Stenerson** [comment]
I can submit a quick PR if you'd like - or I can leave it to you - lmk!

**Comment by Stenerson** [comment]
I believe this will need to change to `processedEntity` as well:
https://github.com/paularmstrong/normalizr/blob/2d60121de8810e6694a353c815f4f93a9424ef5d/src/index.js#L23

**Comment by Stenerson** [comment]
@paularmstrong, I started working on this PR and may have uncovered something else. Either that or I'm very confused and misunderstanding something.

I made the 2 changes discussed above and a handful of tests started failing. Ok, I'll take a look... here's the [first one](https://github.com/paularmstrong/normalizr/blob/master/src/schemas/__tests__/Entity.test.js#L90)

```js
    it('is run before and passed to the schema normalization', () => {
      const processStrategy = (input) => ({ ...Object.values(input)[0], type: Object.keys(input)[0] });
      const attachmentEntity = new schema.Entity('attachments');
      // If not run before, this schema would require a parent object with key "message"
      const myEntity = new schema.Entity('entries', {
        data: { attachment: attachmentEntity }
      }, { idAttribute: (input) => Object.values(input)[0].id, processStrategy });

      expect(normalize({ message: { id: '123', data: { attachment: { id: '456' } } } }, myEntity)).toMatchSnapshot();
    });
```

They key here is `idAttribute: (input) => Object.values(input)[0].id, processStrategy`
That function returns `'123'` which is the **value of the `id` not the "key"**

I tested this on my own app and sure enough, if I use a function as the `idAttribute` it expects the value of the id, not the key (or "attribute") but if I use a string, it expects the key (`compositeID` in my case).

This seems odd and different than the [documentation](https://github.com/paularmstrong/normalizr/blob/master/docs/api.md#entitykey-definition---options--) leads me to believe. Am I crazy? Are the tests wrong? Something else?

**Comment by paularmstrong** [comment]
Ah, yeah, then this would be a slightly breaking change, but not the end of the world, as it's easy to fix codebases relying on this.

The reason for this test is because I've come across some instances with objects that look like:
```
{
  myEntities: [
    { entityTypeA: { id: 123, ... },
    { entityTypeB: { id: 123, ... }
  ]
}
```

As you can guess, this is kind of a pain. We have a list of entities, but they have only a single key which denotes their entity type, then we have to go one more level deep to find the ID. The idea was to use `processStrategy` to bring everything one level up so it's a flatter structure.

What we want, after normalization:

```
{
  entities: {
    entityTypeA: [ { id: 123, ... } ],
    entityTypeB: [ { id: 123, ... } ],
  },
  result: {
    myEntities: [ { id: '123', schema: 'entityTypeA' }, { id: '123', schema: 'entityTypeB' } ]
  }
}
```

The simple solution from the normalizr user's end is to have the `idAttribute` function determine the ID based on what is output from `processStrategy`. 

So that test can be updated. I've changed the `id` key to `id_str` so that it's maybe a *little* more obvious what's happening?

```js
it('is run before and passed to the schema normalization', () => {
  const processStrategy = (input) => ({ ...Object.values(input)[0], type: Object.keys(input)[0] });
  const attachmentEntity = new schema.Entity('attachments');
  // If not run before, this schema would require a parent object with key "message"
  const myEntity = new schema.Entity('entries', {
    data: { attachment: attachmentEntity }
  }, { idAttribute: 'id_str', processStrategy });

  expect(normalize({ message: { id_str: '123', data: { attachment: { id: '456' } } } }, myEntity)).toMatchSnapshot();
});
```

**Comment by Stenerson** [comment]
Thanks Paul. I'll open a PR in the next day or two with this change and updated tests. We can discuss more if needed on that thread.

I'm also going to open another issue for the intended behavior of `idAttribute`. If it's working as intended, it's probably worth an update to the doc to explain how it works (and how it has different meanings based on the type of the prop - `string` === id key, `function` === id value).

It's (probably) worth mentioning that, using a function for `idAttribute` and knowing what I know now, I can get the data I need without mutating the input value.

```js
const calcCompositeId = value => {
  return value.guest_id ? `${value.id}-${value.guest_id}` : value.id;
}

const patronProcessStrategy = (value, parent, key) => {
  // Determine composite key
  const compositeId = calcCompositeId(value);
  // I want to access this key in the app so we still need to 
  // add it to the non-mutated return object
  return { ...value, compositeId };
};

const patronsSchema = new schema.Entity('patrons', undefined, {
  // idAttribute *functions* must return the id's **value** (not key)
  idAttribute: value => calcCompositeId(value),
  processStrategy: patronProcessStrategy,
});
```

It **does** work but effort feels duplicated vs. the [original attempt](https://github.com/paularmstrong/normalizr/issues/258#issue-227076192). If you think this is good enough, let me know and I'll close this to focus on the doc.

**Comment by paularmstrong** [comment]
Ah... this is the way it's always been, so maybe I was just confused.

Maybe the best thing to do would be a major version change that requires one of `idAttribute` or `getId` on `schema.Entity`. 

Separately, I do think it would be valuable to only use the returned object from `processEntity` once it's been run. (As we've been discussing). Maybe also valuable to be in a major release change.

**Comment by Stenerson** [comment]
I agree that splitting this into two options would be the ideal solution.
- A function that returns an ID's *value*
- A string or function that returns the ID's *key* (might not need a function option but I think it's popular to optionally provide functions for most things nowadays)

I'll open a PR in the next few days to use the `processedEntity` and let you comment on the test changes as well as decide when it's appropriate to merge it in.

I'd also be willing to take a shot at the other change. Do you have a major release timeframe in mind? Any other breaking changes on the docket to include? In the meantime, #260 would update the doc to clarify the meaning of the `idAttribute` option.

**Comment by Stenerson** [comment]
Closing due to discussion in #261
