### ISSUE TITLE
Dynamic idAttribute function not called with same arguments when denormalized

### ISSUE THREAD

**Issue by noobG** [paularmstrong/normalizr#259]
# Problem

Entities with dynamic idAttribute do not receive a parent entity when denormalized.

```js
const content = new schema.Entity('content', {}, {
	idAttribute: (entity, parent) => {
		return `${parent._id}`; // Works fine when normalizing, but parent is undefined when denormalizing
	},
});
```
I went digging a bit in the source code and I can see that the only argument given during denormalization is entity: 

https://github.com/paularmstrong/normalizr/blob/master/src/index.js#L62

As opposed to here:

https://github.com/paularmstrong/normalizr/blob/master/src/index.js#L23

**Comment by paularmstrong** [comment]
Is this really a problem? If you're denormalizing an entity that was already normalized, you should already have the `id`.

**Comment by noobG** [comment]
The denormalized entity has no ID by itself so I derive it from the parent instead. I have a page object with some content - here is a simplified version:

```
{
  id: '123456',
  name: 'mypage',
  content: {
   live: {...},
   draft: {...}
  }
}
```
I want to pull the content attribute to the root level of my store, but it has no ID, so I simply use the ID from the parent object - which works great! But then when denormalizing, I can no longer derive the ID from the parent because the function is no longer called with the parent argument.

Hope that clarifies a bit - maybe I'm going about it the wrong way; always happy to be corrected if it means I learn :-)

**Comment by alexeyraspopov** [comment]
I've got exactly the same issue.

Here is my data:

```javascript
const models = [{
  id: '1',
  metrics: {
    'FVE Poisson': { validation: 0.56269, crossValidation: 0.50166 },
    RMSE: { validation: 21.0836, crossValidation: 23.361932 }
  }
}, {
  id: '2',
  metrics: {
    'FVE Poisson': { validation: 0.76492, crossValidation: 0.48239 },
    RMSE: { validation: 18.3245, crossValidation: 22.242348 }
  }
}];
```

And here is the schema:

```javascript
const Metric = new Entity('metrics', {}, {
  idAttribute(input, parent, key) {
    // will throw on `denormalize()`
    return parent.id;
  }
});
const Model = new Entity('models', { metrics: Metric });
const ModelList = new Array(Model);
```

Here is what I do:

```javascript
const normalizedData = normalize(models, ModelList);
const denormalizedData = denormalize(normalizedData.result, ModelList, normalizedData.entities);
```

**Comment by paularmstrong** [comment]
@noobG, @alexeyraspopov: You'll need to use a separate schema for denormalizing that doesn't try to reference the `parent` for the ID, since your data has a separate shape.

```
// No `idAttribute` function necessary
const Metric = new Entity('metrics');
```

**Comment by alexeyraspopov** [comment]
@paularmstrong, I've tried suggested way, but it doesn't provide excepted result: `metrics` are not given by theirs `model` id — simply, first `metric` entity was duplicated in the second model.

**Comment by aaronschwartz** [comment]
I've hit the same issue. If I use a separate schema with no `idAttribute` then it no longer throws an exception but the denormalized results are incorrect. It duplicates the first child item for every child item.
