### ISSUE TITLE
Slow/ performance issues

### ISSUE THREAD

**Issue by gajus** [paularmstrong/normalizr#263]
# Problem

I am trying to _normalizr_ data returned from a GraphQL API.

The operation `normalize(response, schema)` is taking ~170ms to complete.

**Input**

The input object is large. It is a collection of a 2000+ entries each describing the following schema.

```js
{
  id
  movie {
    id
    name
    synopsis
    credits(first: 3) {
      edges {
        creditOrder
        character {
          id
          name
        }
        person {
          id
          name
          headshotImageUrl
        }
      }
    }
    directors {
      id
      person {
        id
        name
        headshotImageUrl
      }
    }
    posterImageUrl
    genres {
      id
      name
    }
    releaseYear
    trailerYoutubeId
  }
  venue {
    id
    name
    cinema {
      id
      name
      logo {
        svgUrl
      }
    }
    address {
      street1
      postcode
    }
  }
}

```

The raw output (when stringified) is about 2.5MB.

The same schema/ normalization is applied many times.

Are there known ways to improve performance of normalirz? (e.g. cache strategies)

**Comment by paularmstrong** [comment]
Any time you try to operate over that much data, it's going to be slow. I'm surprised it's *only* 170ms. 

Normalizr may not be right for your use case, especially since you're already using GraphQL. You should be able to normalize your data through GraphQL instead of doing it client-side. It's a bit of work on the GraphQL side, but the payoff will definitely be worthwhile.

**Comment by gajus** [comment]
> Normalizr may not be right for your use case, especially since you're already using GraphQL. You should be able to normalize your data through GraphQL instead of doing it client-side. It's a bit of work on the GraphQL side, but the payoff will definitely be worthwhile.

I did! In fact the result is awesome (and super simple):

https://github.com/gajus/graphql-deduplicator

My response size dropped to a fraction of what it was prior. :-)
