### ISSUE TITLE
Denormalization: Make resolution of undefined ids configurable

### ISSUE THREAD

**Issue by paulsonnentag** [paularmstrong/normalizr#267]
**Input**
I'm building a react application where each component defines a query which resolves the data that it requires.

A query to fetch a project with it's task and members could look like this:
```JSON
{
  "id": 2,
   "model": "project",
   "include": ["tasks", "members"] 
}
```

The response contains only the ids of the related entities:
```JSON
{
  "id": 2,
  "project": "myproject",
  "tasks": [{"id": 1}, {"id": 5}, {"id": 6}],
   "members": [{"id": 4}]
}
```
In the next step the app would check if the sub entities have been already fetched otherwise another request is triggered to load the missing entities. This leads to a state where some entities will be resolved and others are still missing. In my component I would like to never have an entity be undefined but instead receive the entities progressively added once they are loaded.

If normalizr allowed to configure how missing ids are resolved this would also make handling deletion of entities really easy. We keep the cache in sync with websockets which triggers events when ever an entity is updated or deleted. If the app receives an delete event it could just remove the entity from the cache.

**Output**

Here's what I would like to have:

```js
...

const entities = {
  project: {
      1: { 
        id: 1,
        name: 'myproject' 
        tasks: [1, 2]
      }
  },
  task: {
    1: {
      id: 1
      title: 'task 1',
    }
  }
}

denormalize({id: 1},  projectSchema, entities, {removeMissingEntities: true}) // additional parameter to configure resolution
/* would return 
{
  id: 1,
  name: 'myproject',
  tasks: [
    { id: 1, title: 'task 1' }
  ]
}
*/

```

I'd appreciate any feedback and would be willing to implement this feature if this aligns with the design of this project

**Comment by paularmstrong** [comment]
By not returning the items in the denormalized response, that would tell me that the item doesn't exist and doesn't need to be fetched. The current behavior at least lets you know that `{ id: 2 }` is a task, but that more data (`title`) is missing and therefore should be fetched.

I'd like to avoid any extra configuration like this that bloats the API. We can revisit if this becomes a major problem for others.

**Comment by jonaskello** [comment]
I have a similar problem, I want to exclude objects that are marked as deleted when denormalizing. I've found it is much easier to mark objects as deleted than to find all parents and remove them from them.

So a better API might be to pass in a function that returns true/false if the object should be included. So for the case you want to exclude undefined entities you can do this:

```
denormalize({id: 1},  projectSchema, entities, {include:  (entity) => entity !== undefined })
```

And in my case I want to check for a deleted marker:

```
denormalize({id: 1},  projectSchema, entities, {include:  (entity) => !entity.deleted})
```
