### ISSUE TITLE
Example wanted: Org Chart

### ISSUE THREAD

**Issue by dkrieger** [paularmstrong/normalizr#277]
Given the JSON at the bottom as an example, how would one go about normalizing an arbitrarily deep (recursive) org chart so that you get all people in the org at the top level (call the entity "people"), with references to their subordinates by id? Is it possible to make the schema reference itself? e.g. `const person = new schema.Entity('people', {subordinates: [this]});` ?

```JSON
{
  "id": 0,
  "name": "Boss",
  "subordinates": [
    {
      "id": 1,
      "name": "Manager1",
      "subordinates": [. . .]
    }
  ]
}
```

**Comment by paularmstrong** [comment]
Please keep Issues in Github for actual problems or issues with the source of normalizr. For help, look toward StackOverflow or others.

**Comment by dkrieger** [comment]
Sorry for opening this issue, I see you answered this already on SO. In case anyone searches issues and finds this, here's the SO link: https://stackoverflow.com/a/41509150/7940021
