### ISSUE TITLE
Identifying entities by type rather than (or in addition to) schema for Polymorphic mappings

### ISSUE THREAD

**Issue by karptonite** [paularmstrong/normalizr#281]
Apologies if this is more a StackOverflow question than a support question. I [tried StackOverflow first](https://stackoverflow.com/questions/45083510/normalizr-identifying-entities-by-type-rather-than-schema-for-polymorphic-mappi), but got no response, and this may be more of a feature request anyway.

Here's how I'm using normalizr:

I'm trying to normalize polymorphic data in a way that allows me to identify the type of the items in the normalized data without having to denormalize.

Ideally I could normalize something like this:
```json
[
  {
    "imagelinkid":175634,
    "imageid":447236,
    "item":{"type":"things", "id":"41047", "moreData": "data"}
  }, 
]
```
to something like this:
```json
{
  "result": [ 
    {
      "imagelinkid":175634,
      "imageid":447236,
      "item":{"type":"things","id":"41047"}
    }
  ], 
  "entities": {
    "things": {
      "41047": {"theItem": "goesHere"}
    }
  }
}
```
The key is that what want in my result is the _type_ and id of the item. What I get instead is the _schema_, which is great for denormalization using normalizr, but not so great for accessing the item if don't want the rest of the app to be dependent on normalizr.

My current relevant schema looks like this:
```typescript
import * as _ from 'lodash';
import { Schema, schema } from 'normalizr';

const types = [ 'things', 'people', 'companies', 'images'];

const schemas = <{[key: string]: Schema }>_.zipObject( types, types.map( itemType => {
	return new schema.Entity( itemType );
} ));

export const essentialSchema = new schema.Union( schemas , 'type' );

export const imageLinkSchema = new schema.Object({
	item: essentialSchema,
});

export const imageLinksSchema = [ imageLinkSchema ];
```
What I actually get is something very similar to the desired output, except the item is specified by `schema` and `id` instead of `type` and `id`. I've tried to work around that by giving the schema and the type the same name, but it might be more useful and cleaner if the type could be included there in addition to the schema in the normalized data.

**Comment by paularmstrong** [comment]
This is intentional and not going to change.
