### ISSUE TITLE
Depends on electricity.

### ISSUE THREAD

**Issue by mediaupstream** [paularmstrong/normalizr#284]
# Problem

![screen shot 2017-08-02 at 4 26 56 pm](https://user-images.githubusercontent.com/163243/28895830-9812d50c-779f-11e7-952f-2a15661d6360.png)

The project depends on electricity, and potentially a few other things. Let's be transparent here.

**Comment by paularmstrong** [comment]
![whooooaaaaaaaaaaaaa](https://user-images.githubusercontent.com/33297/28896690-4e33d4e8-7792-11e7-9af7-177071a0671f.gif)
