### ISSUE TITLE
getEntities gives a cryptic error message on bad user input

### ISSUE THREAD

**Issue by jandom** [paularmstrong/normalizr#285]
# Problem

This is a great library/package, thanks for putting it together! 

The `getEntities` function assumes that the schema provided by the user in `denormalize` is correct. 

```js
    return isImmutable ?
      entities.getIn([ schemaKey, entityOrId.toString() ]) :
      entities[schemaKey][entityOrId];
  };
```

**Input**

Assume that `isImmutable` is false, so we're only concerned with `entities[schemaKey][entityOrId];`

entities is typically of the form 
```js
entities: {
  typeA: {..},
  typeB: {..}
}
```
If `schemaKey = typeX` and `entityOrId = 1`, this will break with the following output

**Output**

Here's what I expect to see when I run the above:

```js
Uncaught (in promise) TypeError: Cannot read property '1' of undefined
```

This behavior is obviously correct because the user screwed up. However, the error message could be better

**Comment by SushilShrestha** [comment]
Also when I miss some entities. I get simillar cryptic error message.
`TypeError: undefined is not an object (evaluating 'entities[schemaKey][entityOrId]')`
