### ISSUE TITLE
Support idAttribute on Union

### ISSUE THREAD

**Issue by goodmind** [paularmstrong/normalizr#287]
# Problem

Define `idAttribute` on `schema.Union`

**Input**

Here's how I'm using normalizr:

```js
const document2 = new normalizr.schema.Entity('document');

const mediaDocument = new normalizr.schema.Entity('mediaDocument', {
  document: document2,
});

const media = new normalizr.schema.Union({
  messageMediaDocument: mediaDocument
}, '_', { idAttribute: (_, parent) => parent.id })

const messages = new normalizr.schema.Entity('messages', {
  media: media,
})

const slice = {
  messages: [ messages ],
}

const data = normalizr.normalize({
  messages: [{
    id: 1,
    media: { 
      _: 'messageMediaDocument',
      document: { id: 2, access_hash: 2 }
    }, 
  }]
}, slice)
console.log(data)
```

**Output**

Here's what I expect to see when I run the above:

```js
{ entities: 
   { document: { '2': [Object] },
     mediaDocument: { '1': [Object] },
     messages: { '1': [Object] } },
  result: { messages: [ 1 ] } }
```

Here's what I *actually* see when I run the above:

```js
{ entities: 
   { document: { '2': [Object] },
     mediaDocument: { undefined: [Object] },
     messages: { '1': [Object] } },
  result: { messages: [ 1 ] } }
```

**Comment by paularmstrong** [comment]
Union is meant when you have a union of multiple types of entities. If all you're needing is an array of a single type of entity, you should be using `[ messages ]` or `new schema.Array(messages)`

**Comment by goodmind** [comment]
@paularmstrong there is multiple type of `_` of course

**Comment by paularmstrong** [comment]
Ah, all you need to do is tell `mediaDocument` how to find the ID:

```
const mediaDocument = new normalizr.schema.Entity('mediaDocument', {
  document: document2,
}, { idAttribute: (value, parent) => parent.id });
```

**Comment by goodmind** [comment]
@paularmstrong also, why Union wraps data into `{ id: data, schema: 'mediaDocument' }`?

**Comment by paularmstrong** [comment]
So you know what schema the item is. Union is a *union* of multiple schema.

https://github.com/paularmstrong/normalizr/blob/master/docs/api.md#uniondefinition-schemaattribute

**Comment by goodmind** [comment]
@paularmstrong But I already have `_` in my data
