### ISSUE TITLE
Option on Polymorphic  to customize the way it generates the reference

### ISSUE THREAD

**Issue by javierfernandes** [paularmstrong/normalizr#288]
# Problem

I have a schema where all objects will have unique ids. Independently of their "type" or schema.
So when normalizing an array of Union normalizr replaces the object not by its id, but with and object that has id + schema.

Example, suppose a "User" has "belongings" which is a Union (Computer, Car, etc)
```json
{ 
  "id": 1,
  "name": "John",
  "belongings": [ { "id": 23, "schema": "computer" }, { "id": 3, "schema": "car" } ]
}
```
Now, this is not needed for me, since all objects have unique id there's no need to identify the schema (you could just by looking at that object (finding by id).

I didn't find a way to customize that.
My workaround was to subclass Union overring the normalize method

```js
class UnionWithoutClassifier extends schema.Union {
  normalizeValue(value, parent, key, visit, addEntity) {
    const schema = this.inferSchema(value, parent, key);
    if (!schema) {
      return value;
    }
    const normalizedValue = visit(value, parent, key, schema, addEntity);
    // HERE
    // return this.isSingleSchema || normalizedValue === undefined || normalizedValue === null ?
    //   normalizedValue :
    //   { id: normalizedValue, schema: this.getSchemaAttribute(value, parent, key) };
    return normalizedValue  // HERE
  }
}
```
But this is not pretty since I had to copy the original implementation :(

It would be good to be able to give "options" to Union. Like a function for creating the "reference" or replacement object.

Thanks!

**Comment by paularmstrong** [comment]
I don't want to complicate the APIs any further, which is why you're able to extend and override things like in your example. What you've got is fine for your use case.
