### ISSUE TITLE
normalizr doesn't handle empty empty entities

### ISSUE THREAD

**Issue by kaarelkivistik** [paularmstrong/normalizr#289]
# Problem

A common use-case with redux: data has not yet arrived from the server and `entities` object in the store is empty. For me this happens in a detail view where I'm trying to display a single object from a list.

**Input**

Here's how I'm using normalizr:

```js
const { denormalize, schema } = require("normalizr")

denormalize(1, new schema.Entity('foobar'), {})
```

**Output**

Here's what I expect to see when I run the above:

```js
// result should be undefined/null or something similar
```

Here's what I *actually* see when I run the above:

```js
TypeError: Cannot read property '1' of undefined
```

<img width="908" alt="screen shot 2017-09-05 at 16 31 21" src="https://user-images.githubusercontent.com/8894531/30063855-ace13892-9258-11e7-9315-b7fe883fcf00.png">

**Comment by goodmind** [comment]
same problem

**Comment by paularmstrong** [comment]
This seems like something easily solved up front. Don't try to normalize if you've got nothing to normalize.
