### ISSUE TITLE
An empty array of results should produce an empty entity

### ISSUE THREAD

**Issue by kumar303** [paularmstrong/normalizr#290]
# Problem

If the data for an entity is an empty array then the entities container is not created.

**Input**

Here's how I'm using normalizr:

```js
const { schema, normalize } = require('normalizr');

// Define a users schema
const user = new schema.Entity('users');

// Define your comments schema
const comment = new schema.Entity('comments', {
  commenter: user
});

// Define your article
const article = new schema.Entity('articles', {
  author: user,
  comments: [ comment ]
});

const data = {
  id: "123",
  author: {
    id: "1",
    name: "Paul"
  },
  title: "My awesome blog post",
  // Imagine the API returned zero comments for this article:
  comments: []
};
console.log(normalize(data, article));
```

Here's what I *actually* see when I run the above:

```js
{ 
  entities: { 
    users: { '1': [Object] }, 
    articles: { '123': [Object] },
  },
  result: '123',
}
```

Here's what I expected to see:

```js
{ 
  entities: { 
    users: { '1': [Object] }, 
    articles: { '123': [Object] },
    comments: {},
  },
  result: '123',
}
```

In other words, the `comments` entity should be initialized to an empty object since the schema specified that it should exist. Without this, the top level `entities` object would sometimes be "normalized" to an inconsistent state. This makes it hard for code that receives `entities` to know if it's working with the right object or if the caller made a mistake.

**Comment by paularmstrong** [comment]
If you don't receive any entities of a certain type, why would you expect to see that initialized in the resulting object?

Honestly, I don't think this will make it into normalizr, because:
1. Schema are only added to the result as they're found, not as they're defined
2. This will cause extra cycles in external applications (ie Twitter Lite) because we'll be forced to make a call to something like `addEntities` with an empty array of entities, which is a wasteful extra function call when there's nothing to add.

Why is this so problematic for you to add your own guard?

**Comment by kumar303** [comment]
> If you don't receive any entities of a certain type, why would you expect to see that initialized in the resulting object?

Because the schema (to me) is a definition of how the data will be normalized. It is saying you will receive `entities` and it will have a map of `comments`, even if that map is empty.

> Why is this so problematic for you to add your own guard?

If I have a function that processes the entities, there is no way to catch mistakes by callers that are not passing the correct entities object. Example:

```js
function loadEntities(entities) {
  // I can do this...
  if (!entities) {
    throw new Error('The entities parameter cannot be empty');
  }
  // ...but I cannot do this:
  if (!entities.comments) {
    throw new Error('The entities object did not contain a comments property');
  }
}
```

In an app without decent [`Flow`](https://github.com/facebook/flow/) coverage, these type of guards are really helpful in catching refactoring mistakes. For example, I had to change the nesting level for how some functions were passing `entities` and it would have been easier to debug the test failures with a clear error about the calls I needed to fix.

Anyway, feel free to close the issue. I was just really surprised that the schema wasn't enough to guarantee that I'd get a property. It seemed to me like that was the point of the schema.

**Comment by Noitidart** [comment]
I am also in this situation. I always expect the key in the `entities` but it needs to be empty. I didn't know it would be omitted and now am running into errors. I use Object.values etc so I get errors of "cannot convert undefined to object".

I have gone through and added the keys in as empty arrays if missing, but it would be nice if this was present. I always have to add custom logic to handle this case otherwise.

**Comment by jpicornell** [comment]
I am facing this error too. I use Vue.js and Vuex as store manager and the thing is, we need a consistent output of entities to ensure we introduce the correct data to the store manager without having to test if it's undefined some entity or not. In my opinion data managing always need consistent output data.

I thing that what @paularmstrong is saying is only aplicable if some entity is not present on output data:
```javascript
const item = new schema.Entity('items');
const order = new schema.Entity('orders');
const user = new schema.Entity('users', {
  items: [item],
  orders: [order],
});
{
  name: 'John',
  items: [],
}
```
Only in this case I would agree to not include the entity to entities set, although I think it's always necessary to include all entities into entities set if they're declared in the schema.

**Comment by callmetwan** [comment]
I'm also in the camp of wanting to have empty entities if there is no data present.

I wouldn't be opposed to defining this behavior myself in the schema if given the option. For instance, maybe there could be a postProcessingStrategy method that would give access to the normalized data. It would then be simple to check if the output contained the appropriate entities.

**Comment by Mosho1** [comment]
I would also like to at least have the option for this to be done by normalizr. It's a simple and clear inconsistency.

**Comment by subprime** [comment]
As said from @Noitidart i'm running also in this issue. While fetching the data from the api we normalize our data to entities and call a action for fetching completed.

**Comment by TroySchmidt** [comment]
Not sure if it helps, but TypeScript with interfaces helps to solve some of those issues for not relying on schema to define the shape of your entity, but interfaces.  So then we define things like
```
interface MyInterface{
comments?: Comment[];
}
```

**Comment by ckeeney** [comment]
I think this use case can be solved with `processStrategy`.  I do something similar to ensure I know when all my entities were last updated:

```js
const addTimeStamp = (value, parent, key) => {
    return merge(value, {last_updated: moment.now()})
};

export const categorySchema = new schema.Entity('categories', {}, {
    idAttribute: 'slug',
    processStrategy: addTimeStamp
});
```

You could adapt this to provide defaults for anything your entity might need.

**Comment by dmk255** [comment]
I solved this by wrapping `normalize` and using lodash's merge though it's not required:

```JS
const normalizeDefinition = (definition) => {
  const defaultEntityStructure = {
    dashboards: {},
    cards: {},
  };

  const { result, entities } = normalize(definition, dashboards);

  return {
    result,
    // We should always have the defaultEntityStructure keys
    entities: merge(defaultEntityStructure, entities),
  };
};
```

I only use `normalizeDefinition` in the rest of my application

**Comment by paularmstrong** [comment]
It won't cause any problems with the output to include it. No one has added a PR yet, so there's nothing to review.

**Comment by noahbornstein** [comment]
Yes, was asking because you seemed against adding it to the project earlier, and hadn't opined since. But good to know 👍 Thanks.

**Comment by dbartholomae** [comment]
Having the same problem here. I might take a shot at a PR :)

**Comment by anton6** [comment]
Hi, any update on this feature? Thanks

**Comment by paularmstrong** [comment]
> Hi, any update on this feature? Thanks

Lots of people want a thing, but no one is willing to build it. I'm going to close this issue since there hasn't been any valuable information added in some time. If anyone's looking for this, please open a PR with the functionality.
