### ISSUE TITLE
processStrategy before normalization

### ISSUE THREAD

**Issue by goodmind** [paularmstrong/normalizr#291]
# Problem

Well, if processStrategy runs before normalization why I end up with extracted data in `value`. Even if I want I can't access this data, because I can't access redux store inside of processStrategy

**Input**

Here's how I'm using normalizr:

```js
const processPhoto = (value) => {
   // here value.sizes are already normalized
   // like this
   // [{ id: 212, schema: '...' }, { ... }]
};
const photo = new schema.Entity('photos', {
  sizes: new schema.Array({...}, '_'),
}, {
  processStrategy: processPhoto,
});
```

**Output**

Here's what I expect to see when I run the above:

```js
const processPhoto = (value) => {
   // here value.sizes before normalization
   // like this
   // [{ _: '...', ... }, { _: '...', ... }]
};
```

**Comment by goodmind** [comment]
lol, it looks like this is chrome console.log issue

**Comment by mplis** [comment]
Just to clarify for anyone else who comes across this, my issue was that I had something like this:

```js
processStrategy: (value, parent, key) => {
    console.log(value);
    return value;
}
```

and changing it to this fixed my problem:

```js
processStrategy: (value, parent, key) => {
    console.log(value);
    return { ...value };
}
```

You need to return shallow copy from `processStrategy` or else you'll see the mutated, post-normalized `value` in the Chrome logs
