### ISSUE TITLE
Array denormalize

### ISSUE THREAD

**Issue by goodmind** [paularmstrong/normalizr#292]
# Problem

Why I get same array item in denormalization when it should be distinct?

**Input**

https://repl.it/KzbV/4

**Output**

Here's what I expect to see when I run the above:

```js
{ id: 4,
  images: 
   [ { _: 'cached', location: [Object] },
     { _: 'online', location: [Object] } ] }
```

Here's what I *actually* see when I run the above:

```js
{ id: 4,
  images: 
   [ { _: 'cached', location: [Object] },
     { _: 'cached', location: [Object] } ] }
```

**Comment by paularmstrong** [comment]
Use `schema.Union`, not `schema.Array` for `images` if you are normalizing an array that can have multiple types. Union is polymorphic, while Array expects only one type.

https://repl.it/KzbV/5

**Comment by goodmind** [comment]
I thought that Union is for object with multiple types, not array. Thanks

**Comment by goodmind** [comment]
@paularmstrong why entities inside array not normalized (no field in `entities` object) if I use `schema.Union` for it?

**Comment by goodmind** [comment]
@paularmstrong is this bug?

**Comment by paularmstrong** [comment]
Sorry, you were right the first time to use `schema.Union`. The problem is that you're defining the same schema key for multiple entities. You can't use `things` for multiple schema. Be more descriptive, like this:

https://repl.it/KzbV/6

```
const cached = new schema.Entity('cached', { 
  location: location2
}, { idAttribute: e => e.location.local_id })

const online = new schema.Entity('online', { 
  location: location2
}, { idAttribute: e => e.location.local_id })

const images = new schema.Array({
  cached,
  online,
}, '_')
```

**Comment by goodmind** [comment]
@paularmstrong why I can't store it in the same key?
