### ISSUE TITLE
Denormalization: depth attribute

### ISSUE THREAD

**Issue by entropitor** [paularmstrong/normalizr#293]
# Problem

I want to be able to denormalize data upto a certain depth (e.g. 3 levels deep)

**Input**

Here's how I'm using normalizr:

```js
// Add as much relevant code and input as possible.
export const chapter = new schema.Entity('chapters', {lessons: [lesson]})
export const course = new schema.Entity('courses', {chapters: [chapter]})
export const track = new schema.Entity('tracks', {courses: [course]})

export const trackWithCourses = new schema.Entity('tracks', {courses: [new schema.Entity('courses')]})

denormalize('3', track, myEntities, 2);
//equivalent to
denormalize('3', trackWithCourses, myEntities);
```

**Output**

Here's what I expect to see when I run the above:

```js
{
    id: 3,
    courses: [{
     id: ...
     chapters: [4, 5]
   }]
}
```

Here's what I *actually* see when I run the above:

```js
{
    id: 3,
    courses: [{
     id: ...
     chapters: [{id: 4, name: ...}, {id: 5, ...}]
   }]
}
```

**Comment by TroySchmidt** [comment]
One thing you can do is pass an empty entity object to the ones you don't want to load.  They will just load up with undefined where applicable.  It would be better if the default strategy was to just return something else than a potential array of undefined objects and perhaps just an empty array instead.

**Comment by paularmstrong** [comment]
This seems like a specific edge use case. I'm going to close for now. Feel free to open a PR if it's a simple non-breaking API change, otherwise you should always feel free to fork 😄
