### ISSUE TITLE
Normalizing linked ids

### ISSUE THREAD

**Issue by Noitidart** [paularmstrong/normalizr#298]
I posted on stackoverflow but got no help so thought to ask here please:

In summary there is "linked"/"related" data i want to pick into.

I have a weird set of data here.

    const data = {
        profiles: [
          	{ name: 'Joe', photos: [1, 2, 3] },
            { name: 'Ryan', photos: [2] },
            { name: 'Bob', photos: null }
        ],
        linked: {
            photos: [
              	{ id: 1, url: 'http://blah' },
                { id: 2, url: 'blah' },
                { id: 3, url: 'asdf' }
            ]
        }
    }

I get all the profiles like this:

    const { entities } = normalize(data, {
        profiles: [ Profile ]
    });

But I want to replace the `photos` id array with the entries from `linked.photos`, is this possible? Or does it require post processing? I am currently doing custom post processing.

**Comment by paularmstrong** [comment]
Your data is already normalized. You want to be using `denormalize`, but you'll have to change the shape of your data first.

**Comment by Noitidart** [comment]
Ah interesting thank you sir! I think I got it, will share on success.

**Comment by Noitidart** [comment]
Shucks I can't figure it out. May you please take a peak? I change my data shape by promoting all keys from inside `linked` to top level:

```
const { denormalize, schema } = require("normalizr")

const photo = new schema.Entity('photos');
const profile = new schema.Entity('profiles', { photos: [ photo ] });
const mySchema = { profiles: [ profile ] }
// const entities = { users: { '1': { id: 1 }, '2': { id: 2 } } };

const data = {
    profiles: [
      	{ name: 'Joe',  id: 'joe',  photos: [1, 2, 3] },
        { name: 'Ryan', id: 'ryan', photos: [2] },
        { name: 'Bob',  id: 'bob',  photos: null }
    ],
    linked: {
        photos: [
          	{ id: 1, url: 'http://blah' },
            { id: 2, url: 'blah' },
            { id: 3, url: 'asdf' }
        ]
    }
}

// promote all things in linked to top level
for (const [name, subentities] of Object.entries(data.linked)) {
    data[name] = subentities;
}
delete data.linked;


const entities = { profiles:[] }
const dataMerged = denormalize(data, mySchema, entities);

console.log('data:', data);
```
