### ISSUE TITLE
Renaming and removing data when normalizing?

### ISSUE THREAD

**Issue by gCardinal** [paularmstrong/normalizr#299]
I might just be missing something, if so, feel free to close this issue.

Say I have a response like so:

```js
{
	packages:[
		245: {
			"id": 245,
			"name_fr": "Je suis français",
			"name_en": "I'm english",
		}
	]
}
```

What I'd like to get with normalizr is an output that looks like:

```js
{
	entities: {
		245: {
			"id": 245,
			"name": {
				"en": "I'm english",
				"fr": "Je suis français",
			}
		}
	}
}
```
Notice how I put the values into a single entity. I don't think I'd seen this anywhere in the doc and it would be a really nice feature I think. Even as far as simply removing data in the output for values we don't use could be nice and allow for more streamlined data to work with.

**Comment by paularmstrong** [comment]
Use `processStrategy`: https://github.com/paularmstrong/normalizr/blob/master/docs/api.md#entitykey-definition---options--
