### ISSUE TITLE
Should id calculation use the preprocessed entity?

### ISSUE THREAD

**Issue by joearasin** [paularmstrong/normalizr#300]
Per https://github.com/paularmstrong/normalizr/blob/master/src/schemas/Entity.js#L61, getId is called on the raw entity (And the preprocessed parent), not the preprocessed entity. Is this correct behavior? It's easy to work around (by sharing code in the idAttribute and processStrategy functions), but it also feels like that should be unnecessary.

**Comment by paularmstrong** [comment]
Please follow the [issue template](https://github.com/paularmstrong/normalizr/blob/master/.github/ISSUE_TEMPLATE.md) provided. I don't know what to do with the information here.
