### ISSUE TITLE
Should id calculation use the preprocessed entity?

### ISSUE THREAD

**Issue by joearasin** [paularmstrong/normalizr#301]
Sorry about not following the format earlier -- I was attempting to frame my question as "is this a bug" rather than "I found a bug", because I'm not certain whether the current behavior is intentional.

# Problem

I am attempting to normalize a tree. The items don't have unique IDs, but they can be uniquely identified based on the concatenation of their parent's IDs.

**Input**

Here's how I'm using normalizr:

```js
// Add as much relevant code and input as possible.

const myData = {
  index: '1',
  title: 'root',
  children: [
    {
      index: '1',
      title: 'child 1',
    },
    {
      index: '2',
      title: 'child 2',
    },
  ],
};

const calculateFullHierarchy = (parent, value) =>
  parent.fullHierarchy
    ? `${parent.fullHierarchy}.${value.index}`
    : `${value.index}`;

const processTreeItem = (value, parent, key) => ({
  ...value,
  fullHierarchy: calculateFullHierarchy(parent, value),
});

const treeArray = new schema.Array();

// THIS DOES NOT WORK
const treeItem = new schema.Entity(
  'treeItems',
  { children: treeArray },
  {
    idAttribute: 'fullHierarchy',
    processStrategy: processTreeItem,
  }
);

// THIS PRODUCES DESIRED OUTPUT
// const calculateTreeId = (value, parent, key) => {
//   return calculateFullHierarchy(parent, value);
// };
//
// const treeItem = new schema.Entity(
//   'treeItems',
//   { children: treeArray },
//   {
//     idAttribute: calculateTreeId,
//     processStrategy: processTreeItem,
//   }
// );

treeArray.define(treeItem);

normalize(myData, treeItem);
```

**Output**

Here's what I expect to see when I run the above:

```js
{ entities: 
   { treeItems: 
      { '1': 
         { index: '1',
           title: 'root',
           children: [ '1.1', '1.2' ],
           fullHierarchy: '1' },
        '1.1': { index: '1', title: 'child 1', fullHierarchy: '1.1' },
        '1.2': { index: '2', title: 'child 2', fullHierarchy: '1.2' } } },
  result: '1' }
```

Here's what I *actually* see when I run the above:

```js
{ entities: { treeItems: { undefined: { index: '1', title: 'root', fullHierarchy: '1', children: [] } } },
  result: undefined }
```

As far as a bit of a dive into what's going on:
Here, https://github.com/paularmstrong/normalizr/blob/master/src/schemas/Entity.js#L61 `getId` is being passed `input`, not `processedEntity`. I'm not sure whether this is desired behavior or not -- changing it would be a breaking change, although processedEntity could be passed as an extra parameter to getId to allow for a non-breaking change with the opportunity to enhance functionality.

**Comment by paularmstrong** [comment]
Yes, this is intentional.
