### ISSUE TITLE
Is schema.Values() output format appropriate?

### ISSUE THREAD

**Issue by OzTK** [paularmstrong/normalizr#303]
# Problem

When using schema.Values(), the output is both of the same type in `output.entities` and `output.result` (a keyed object), which seems to be redundant to me as they both get accessed by the id. Wouldn't an array of ids make more sense under `output.result`?

**Input**

Here's how I'm using normalizr:

```js
const recording = new schema.Entity("recordings");

const recordings = new schema.Values(recording);

normalize({ "1": { "end": 44242 }, "2": { "end": 4256753 } }, recordings);
```

**Output**

Here's what I expect to see when I run the above:

```js
{
  "entities": {
    "recordings": {
      "1": {
        "end": 44242
      },
      "2": {
        "end": 4256753
      }
    }
  },
  "result": [
    "1",
    "2"
  ]
}
```

Here's what I *actually* see when I run the above:

```js
{
  "entities": {
    "recordings": {
      "1": {
        "end": 44242
      },
      "2": {
        "end": 4256753
      }
    }
  },
  "result": {
    "1": "1",
    "2": "2"
  }
}
```

**Comment by paularmstrong** [comment]
Yes. Your input was an object, so your result is an object.

**Comment by OzTK** [comment]
Ok I understand that this is consistent with the API. But isn't the whole purpose of `schema.Values()` to treat an object as an array? It seems implied by the name which suggests that we are dealing with a collection. I just don't see a use case for `output.result`. Is it because this kind of manipulation was not intended in the first place?
