### ISSUE TITLE
denormalize array duplicated

### ISSUE THREAD

**Issue by DragorWW** [paularmstrong/normalizr#307]
# Problem
after run `denormalize` lose my data and get duplicates

**version:** v3.2.4

**Input**
I make [demo](https://repl.it/@SierghieiAndrie/normalize-bug-array).
Here's how I'm using normalizr:

```js
var { denormalize, schema } = require('normalizr');

const company = new schema.Entity('company');
const order = new schema.Entity('order', {
  consignorId: company,
});

const orders = [
      {
        id: 'a',
        consignorId: '62de4a90e7606897eae389b69c2c2b92',
      },
      {
        id: 'b',
        consignorId: '62de4a90e7606897eae389b69c2c2b92',
      },
];

const relations = {
  company: {
      '62de4a90e7606897eae389b69c2c2b92': {
        id: '62de4a90e7606897eae389b69c2c2b92',
        shortName: 'test',
      },
    },
};

console.log('orders id list:', orders.map(i => i.id)); // > ['a', 'b']
const ordersDenormalized = denormalize(orders, [order], relations);
console.log('ordersDenormalized id list:', ordersDenormalized.map(i => i.id)); // > ['a', 'a']
```

**Output**

Here's what I expect to see when I run the above:

```js
[
  { id: 'a', consignorId: { id: 'c', shortName: 'test' } },
  { id: 'b', consignorId: { id: 'c', shortName: 'test' } }
]
```

Here's what I *actually* see when I run the above:

```js
[
  { id: 'a', consignorId: { id: 'c', shortName: 'test' } },
  { id: 'a', consignorId: { id: 'c', shortName: 'test' } }
]
```

**Comment by paularmstrong** [comment]
Please use stackoverflow for usage questions.

...

The input you're passing to `denormalize` is not in the correct format. Please re-read the documenation. https://github.com/paularmstrong/normalizr/blob/master/docs/api.md#denormalizeinput-schema-entities

**Comment by DragorWW** [comment]
@paularmstrong ok. Sorry, but in v3.2.0 it working.

**Comment by 0xsven** [comment]
@DragorWW Have you been able to resolve this?

I have just upgraded some dependencies (like webpack and babel) and my project breaks down with the same issue.

**Comment by DragorWW** [comment]
@0xsven i fix my work with api normalizer, we need pass in denormalize
```js
// bug
denormalize(orders, [order], relations);

// not bug
denormalize({orders: orders}, {orders: [order]}, relations);
```

**Comment by 0xsven** [comment]
@DragorWW 
I have solved it like so:

```
// not bug
denormalize([orderIds], mySchema, relations);
```

Passing a list of ids as a first argument. I am not sure why it stopped working I had it before...
