### ISSUE TITLE
how to implement caching? / should the library have a built-in cache system?

### ISSUE THREAD

**Issue by gre** [paularmstrong/normalizr#308]
let's take this example:

```
const user = new schema.Entity('users');
const mySchema = { users: [ user ] }
const entities = { users: { '1': { id: 1 }, '2': { id: 2 } } };
const obj1 = denormalize(1, mySchema, entities);
```

and let's say I'm doing again

```
const obj2 = denormalize(1, mySchema, entities);
```

It would be great if the library would make that `obj1 === obj2`, I don't think that's the case at the moment. meaning it would have to keep references of denormalized objects and cache them (diff strategy are possible, for instance LRU).

Similarly I would expect to have this to be true:

```
[0,1].every(i => denormalize([1,2],mySchema,entities)[i] === denormalize([1,2],mySchema,entities)[i])
```
(but not equality on Array)

more advanced usecase would be to make it work for any levels (like when you have complex schema, same references are preserved). According to current code, object are "cached per reference" but ONLY for the denormalize call lifecycle (i think it's done to implement the circular object feature) . What i'm asking is basically maybe a Schema could cache this across different denormalize calls.

This feature would be huge to improve the performance of an App i'm building with React, the idea is you could always denormalize() but you would always get the same object. Cache on your side I guess can also increase the performance, because you can just return the object instead of building a new one and entering many recursion when traversing the model.

Does that make sense? If this is out of scope of this library, how would you implement this from external user of this library? I don't see this easily possible unless implementing it IN the library..
My current ugly and non optimal approach is to use `isEqual` (deep equals) on the objects, which only work at the top level.

**Comment by paularmstrong** [comment]
You should implement a caching strategy on your own side. For example, at twitter we use [reselect](https://github.com/reactjs/reselect).

**Comment by gre** [comment]
You mean `reselect` as an alternative to normalizr or as something on top of it? I'm not sure to see how the 2 can work together, is there an example of that?
thanks

**Comment by gre** [comment]
what I understand so far is that `normalizr`'s normalize function can be used to generate entities collections but then, insread of `denormalize`, `reselect` could be used because it have better reference cache strategies, is this what you suggested @paularmstrong ?

I still don't get why not improving this library with such a mechanism? denormalize is not very useful if it does not provide a way to lazily yield the same objects. I thought the library was close to implement when i've read in the code this sort of reference cache mechanism [here](https://github.com/paularmstrong/normalizr/blob/ba1847bb859ae12a448e6175e0d0b4aca4e9249b/src/index.js#L66) but I guess it's only used for the lifecycle of a single denormalize call and just in order to handle cycles.

**Comment by gre** [comment]
this is what I had to do to make `denormalize` caching the entities : https://github.com/gre/normalizr/commit/9cf4bb2932618c650a02ed1c2a57edfc5e76dc55

what do you think? obviously it can leak, however, maybe we should provide a way for the user to implement this? e.g. an option in third parameter of Entity (like you have mergeStrategy / processStrategy, I imagine you could have a "cache strategy" or whatever extra option)

**Comment by paularmstrong** [comment]
normalizr is meant to be simple and small. there are plenty of caching solutions available that you can use on top of normalizr already, so we're not looking to bloat normalizr any more than it already is.
