### ISSUE TITLE
Ambiguous output from `normalize`

### ISSUE THREAD

**Issue by jmeas** [paularmstrong/normalizr#311]
# Problem

The output of `normalize` cannot always be interpreted without the input to the function.

**Input**

Consider the example from the README:

```js
import { normalize, schema } from 'normalizr';

// Define a users schema
const user = new schema.Entity('users');

// Define your comments schema
const comment = new schema.Entity('comments', {
  commenter: user
});

// Define your article 
const article = new schema.Entity('articles', { 
  author: user,
  comments: [ comment ]
});

const normalizedData = normalize(originalData, article);
```

**Output**

Consider the output from the example, slightly modified to show the problem:

```js
{
  result: "123",
  entities: {
    "articles": { 
      "123": { 
        id: "123",
        author: "1",
        title: "My awesome blog post",
        comments: [ "324" ]
      }
    },
    "users": {
      "123": { "id": "123", "name": "Paul" },
      "124": { "id": "124", "name": "Nicole" }
    },
    "comments": {
      "123": { id: "123", "commenter": "2" }
    }
  }
}
```

The `result` field tells you the ID of the entity, but not its type. So if we pass this into some other system that is attempting to _do_ something with this data, it cannot know if the ID in `result` was an article, user, or comment. This means that any API that consumes normalizr data must always be of the form:

```js
doSomethingWithResult(result, entity);
```

when it seems possible that it could just be:

```js
doSomethingWithResult(result);
```

I like the first form, because it is simpler for users. But it is also a nice thing if schemas are only necessary to _transform_ the data, and not for interpreting the result as well.

Put another way, it appears to me that normalizr does its job well of transforming your data in a useful way, but at the same time _discards_ some important information!

What do folks think? Thanks for reading!

**Comment by paularmstrong** [comment]
As-designed. You should know based on the schema you used.

**Comment by jmeas** [comment]
Right. It seems unexpected to me that the output format discards information _unnecessarily_. If you can restrict schemas to just being required for transformation, isn't that way more ideal?

This design decision opens up the possibility of:

`doSomethingWithResult(result, wrongSchema);` <== nonsense result

when there seems to be a straightforward solution, which is just not discarding information that the user inputs.

Imagine an alternative library that only required schemas for transformations, but not interpretation. Do you not think that that's more ideal?

**Comment by jmeas** [comment]
It's interesting to note that [`jsonapi-normalizr`](https://github.com/stevenpetryk/jsonapi-normalizer#caveats) decided to make a breaking change to their API to change this behavior. This indicates to me that others may feel similarly about `result`.

@paularmstrong , I understand that this was an intentional design decision, but I'm curious to hear more about why that is, or what the benefits are to this approach.

One cool use case I had for `normalizr` was converting an endpoint that returns non-normalized data into one that _does_ return normalized data. It'd be really rad if I could do a straight return from the returned value of normalizr, but right now a second transformation is required to put back in the primary resource's `type`.

I noticed [in the examples](https://github.com/paularmstrong/normalizr/blob/802d6d9e9af562693982f3a8b13fe522a3b1aded/examples/redux/src/redux/modules/commits.js#L30) that you tend to not use the `result` field, which makes the example look really clean. However, without that field, you lose out on server-side sorting, which many CRUD apps do need.

And anytime server-side sorting is required, then `result` is necessary. And when `result` is necessary, there's some weird code required to "normalize" the inconsistent ways that `normalizr` returns it to you.

Thanks for reading, and thanks for your awesome work! :v:
