### ISSUE TITLE
Renaming keys on normalize/denormalize

### ISSUE THREAD

**Issue by brmenchl** [paularmstrong/normalizr#315]
# Problem

This standard in my codebase is to reference another entity with a property `[entityName]Id` and to include the entity when denormalized under `[entityName]`. However, I can't figure out how to rename parent keys during `normalize` and `denormalize`. Is this currently possible, or is it something I could help implement?

The examples below are meant to clarify what I mean by "renaming keys". I expect something like this would involve the `processStrategy` option, or something else.

### Normalizing Example

**Input**

```js
const data = {
    project: {
        id: '1',
        user: {
            id: '2',
        }
    }
}

const user = new schema.Entity('user');

const project = new schema.Entity('project', {
  user: user,
});

normalize(data, {project});
```

**Output**

```js
{
    result: {project: '1'},
    entities: {
      project: {
        '1': {
          id: '1',
          user: '2' // The actual result
          userId: '2' // The result I would like
        }
      },
      user: {
        '2': {
          id: '2'
        }
      }
    }
}
```
 
### Denormalizing Example

**Input**

```js
const normalizedData = {
    project: {
        '1': {
          id: '1',
          userId: '2'
        }
    },
    user: {
        '2': {
          id: '2' 
         }
    }
}

const user = newschema.Entity('user');

const project = newschema.Entity('project', {
  user: user,
});

denormalize('1', project, normalizedData);
```

**Output**

** What I see**
```js
{
  id: '1',
  userId: '2' 
}
```
** What I want to see **
```js
{
  id: '1',
  user: {
    id: '2',
  }
}

**Comment by TroySchmidt** [comment]
We have a similar pattern.  The solution I have is to tap into ```processStrategy``` and assign the entity there.
```
processStrategy: (value, parent, key) => {
  // Value is the entity, parent is the array, and key is undefined
  return {
    ...value,
    status: value.statusId,
    user: value.userId
  };
}});
```
Of course, the reason I am doing this in processStrategy is because the status and user denormalized data is being grabbed on an initial load to the website and then getting included on denormalize everywhere entities depend on them to decrease traffic.
