### ISSUE TITLE
Denormalize the same id and origindata is not change. should be return the same object

### ISSUE THREAD

**Issue by Qquanwei** [paularmstrong/normalizr#320]
# Problem

Hi, thanks normalizr, Is a great tools for me.

Now, I want get the same object if the origindata not change. but denormalize always return the new object. This make no sense, It may return new object only the origindata changed ?

**Input**

Here's how I'm using normalizr:

```js
import { denormalize, normalize, schema } from 'normalizr';

const originalData = {
  "id": "123",
  "author": {
    "id": "1",
    "name": "Paul"
  },
  "title": "My awesome blog post",
  "comments": [
    {
      "id": "324",
      "commenter": {
        "id": "2",
        "name": "Nicole"
      }
    }
  ]
};


// Define a users schema
const user = new schema.Entity('users');

// Define your comments schema
const comment = new schema.Entity('comments', {
  commenter: user
});

// Define your article 
const article = new schema.Entity('articles', {
  author: user,
  comments: [comment]
});

const normalizedData = normalize(originalData, article);

const user1 = denormalize(1, user, normalizedData.entities);

const otheruser1 = denormalize(1, user, normalizedData.entities);

console.log( user1 === otheruser1 )
```

**Output**

Here's what I expect to see when I run the above:

```js
true
```

Here's what I *actually* see when I run the above:

```js
false
```

**Comment by paularmstrong** [comment]
You will need to write your own memoization layer for this. Normalizr does not include that for you.

**Comment by yachaka** [comment]
@Qquanwei Check out https://github.com/yachaka/denormalizr and https://github.com/gpbl/denormalizr/pull/20
