### ISSUE TITLE
TypeError: Schema is not a constructor

### ISSUE THREAD

**Issue by Awais512** [paularmstrong/normalizr#321]
server.js

var express = require('express');
var morgan = require('morgan');
var app = express();
var mongoose = require('mongoose');
var bodyParser = require('body-parser');
var User = require('./models/user');

mongoose.connect('mongodb://root:abc123@ds223738.mlab.com:23738/ecomawais', function(err){
    if(err){
    console.log(err);}
    else{
        console.log("Connected with mongodb");
    }
});
//Middleware
app.use(morgan('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended: true}));

app.post('create-user', function(req, res, next){
var user = new User();
user.profile.name = req.body.name;
user.password = req.body.password;
user.email = req.body.email;

user.save(function(err){
    if(err) next(err);
    res.json("Successfully created a new user");
});
});

app.listen(3000, function(err){
    if(err) throw err;
    console.log("Server is running on port 3000");
});

user.js
var mongoose = require('mongoose');
var bcrypt = require('bcrypt-nodejs');
var Schema = new mongoose.Schema;

/*The user schema attributes/characteristics/fields*/
var UserSchema = new Schema({
    email: {type: String, unique: true, lowercase: true },
    passwod: String,

    profile: {
        name: {type: String, default: ''},
        picture: { type: String, default:'' }
    },

    address: String,
    history: [{
      date: Date,
      paid: {type: Number, default:0},
      //item: {type: Schema.Types.ObjectId, ref: ''}
    }]
});

//hash the password
UserSchema.pre('save', function(next){
var user = this;
if(!user.isModified('password')) return next();
bcrypt.genSalt(10, function(err, salt){
    if(err) return next(err);
    bcrypt.hash(user.passwod, salt, null, function(err,hash){
        if(err) return next(err);
        user.passwod = hash;
        next();
        });
    });
});

//compare password
UserSchema.methods.comparePassword = function(passwod) {
    return bcrypt.compareSync(passwod, this.passwod);
}

module.exports = mongoose.model('User', UserSchema);

when i try to run the server then its give me the error that "TypeError: Schema is not a constructor".
Please help me to solve my issue. Any help would be appreciated

**Comment by paularmstrong** [comment]
Your error is probably here:

```
var Schema = new mongoose.Schema;

/The user schema attributes/characteristics/fields/
var UserSchema = new Schema({
```

This doesn't look like it has anything to do with normalizr.
