### ISSUE TITLE
Using Normalizr with only state data (no remote JSON)

### ISSUE THREAD

**Issue by asciifaceman** [paularmstrong/normalizr#339]
A lot of the documentation focuses on normalizing inbound data from an API/JSON. 

I want to be able to build out schemas with normalizr for some complex datasets that will only ever be processed internally (lists of objects, etc). I can't really find anything on using normalizr just for internal state data (redux targeted) with reducers etc. 

I'm just looking to be pointed in a direction, and I may just be dense and not seeing something obvious.

I briefly scraped through StackOverflow but questions go largely unanswered.

**Comment by paularmstrong** [comment]
JSON is just another way of representing objects in JavaScript. How you implement what you need is up to you.
