### ISSUE TITLE
Docs: How to import a Schema from another module

### ISSUE THREAD

**Issue by machour** [paularmstrong/normalizr#342]
# Problem

I just spent a *lot* of hours trying to figure out why `denormalize()` stopped working after I extracted my schemas into a separate module in my app.

Thankfully, I came across https://github.com/paularmstrong/normalizr/issues/177 that made me understand that normalizr was "instance aware".

# Solution

Add some documentation (in the README.md file if possible) to warn users about this edge-case, and invite them to export what they need from normalizr from their module.

**Comment by whawker** [comment]
I have a similar issue, I found a workaround using [`webpack.resolve.alias`](https://webpack.js.org/configuration/resolve/#resolvealias). This ensures your external module uses the same instance of normalizr.

```js
// webpack.config.js
const APP_DIRECTORY = fs.realpathSync(process.cwd())

module.exports = {
  //...
  resolve: {
    alias: {
      'normalizr': path.resolve(APP_DIRECTORY, 'node_modules/normalizr')
    }
  }
}
```
