### ISSUE TITLE
Make new release to distribute as ES module

### ISSUE THREAD

**Issue by jlesquembre** [paularmstrong/normalizr#344]
There is a commit (https://github.com/paularmstrong/normalizr/commit/a097346932afe63341a3b74223315d41d87e9e15) from January to distribute normalizr as an ES module, but no new release has been created after it. Could be possible to create a new release?

**Comment by garyvh2** [comment]
@paularmstrong Any update on this?

A dev release on npm would work like a charm, at least from that commit.

Regards.

**Comment by paularmstrong** [comment]
Done: https://github.com/paularmstrong/normalizr/blob/master/CHANGELOG.md#v330
