### ISSUE TITLE
Feature request: Normalize data using Swagger/OpenAPI definition

### ISSUE THREAD

**Issue by tmkasun** [paularmstrong/normalizr#352]
# Problem

Most of the API Creators/Publishers use [OpenAPI specification](https://swagger.io/specification/)(AKA [Swagger](https://swagger.io/)) to define their APIs, This is a well know common standard and it basically covers all most all the aspects of an API. If I want to normalize the response of an API which has a swagger definition, Can I use the swagger definition as the schema when normalizing or denormalizing the API Request/ Response?

# Solution

Since Swagger definition describes the response object of an API, Use swagger definition(swagger yaml or swagger JSON) object directly as the schema when normalizing API response.

**Comment by paularmstrong** [comment]
> Most of the API Creators/Publishers

I've never seen this before, so this might be a hyperbole...

> Since Swagger definition describes the response object of an API, Use swagger definition(swagger yaml or swagger JSON) object directly as the schema when normalizing API response.

Can you propose how this would work? From a quick glance, it looks like too much and too specific to build into Normalizr and would be better suited as its own library. 

For example, in Normalizr, we only care about entities and their IDs (and where they appear). The rest of the fields (string, int, boolean, and all of the various fields) are passive data that Normalizr doesn't touch.

**Comment by tmkasun** [comment]
> Can you propose how this would work? From a quick glance, it looks like too much and too specific to build into Normalizr and would be better suited as its own library.

How swagger definitions works is , You can specify a model and reference it in a response object as a single entity or array of it, So what I'm proposing is, use that reference information to normalize the API response. It doesn't mean to do any data conversion or validation or what so ever.

BTW I found this library https://github.com/eightcard/openapi-to-normalizr which does similar work using normalizr internally. But it goes boyond what i;m suggesting here and generate reducers as well.

**Comment by paularmstrong** [comment]
It looks like what you want is to generate the normalizr schema from Swagger? That's provided as a separate binary: https://github.com/eightcard/openapi-to-normalizr/blob/master/bin/generateschemas

I don't think it's feasible to add that weight to normalizr and makes more sense to keep that step as a separate library.
