### ISSUE TITLE
Add processStrategy equivalent for denormalize

### ISSUE THREAD

**Issue by matt-way** [paularmstrong/normalizr#356]
# Problem

It seems strange that there is a `processStrategy` function explicitly described for use to:

> completely change the entity before normalization is complete

and yet there is no equivalent function to undo these changes with `denormalize`. I would have thought it logical to assume you would be able to get out what you put in, so to speak.

If you are interested in my use case, I am dealing with json configs that are ideally human readable/editable (and need to be saved that way), yet need to be modified on load to work well with the client. I can add a separate layer of data manipulation between the de/normalizing stages, but it would be nice to be able to handle it all with normalizr.

# Solution

I think the API solution is fairly straightforward. Add an option to entity that acts as the `processStrategy` for denormalize. I haven't looked into any technical difficulties with this though.

**Comment by paularmstrong** [comment]
> I would have thought it logical to assume you would be able to get out what you put in, so to speak.

What you put in is the result of the `processStrategy`, so that is true.

> I think the API solution is fairly straightforward. Add an option to entity that acts as the processStrategy for denormalize. I haven't looked into any technical difficulties with this though.

There's a lot to consider. `denormalize` is much more simplistic than `normalize` is. `normalize` receives the `parent` and the `key` that maps the value on the parent.

I'm not opposed to this, but it seems like a pretty specialized use-case and I don't want to see it make normalizr too much more complex.

**Comment by matt-way** [comment]
Thanks for replying. If I get some time I'll look into the technical implications, but for now I think I'll stay out of `processStrategy`, and use my own data modifications layers around normalizr.

**Comment by paularmstrong** [comment]
@matt-way just doing some cleanup. This issue has been stale for some time, so I'm closing for now. Please reopen if you're still intending to address this.
