### ISSUE TITLE
Updating "releases" as much as CHANGELOG.md

### ISSUE THREAD

**Issue by kud** [paularmstrong/normalizr#358]
Hello,

Could you update the releases page as much as you do for CHANGELOG.md?

I usually go to the _releases_ page to see if there's any change of the API.

**Comment by paularmstrong** [comment]
There's a lot of manual process involved. Please forgive me for being strapped for time.

**Comment by kud** [comment]
Don't know use `npm version {major|minor|patch}`? It'll create a commit with a new version for `package.json` + a git tag.

**Comment by paularmstrong** [comment]
Pushing tags requires a separate flag. Creating a release on GitHub is manual. Condescending comments like yours make it hard to want to continue supporting open source.
