### ISSUE TITLE
Help with Denormalizer Function

### ISSUE THREAD

**Issue by brandondtran** [paularmstrong/normalizr#368]
I am a bit confused about how to use denormalize.

I have an object that looks like the following normalized data:

```
{
  layers: {
    byId: {
       '1': {
         id: 1,
         features: [3]
       }
    },
    allIds: [1]
  }
  features: {
    byId: {
      '3': {
         id: 3,
         name: 'blah'
       }
    },
    allIds: [3]
  }
}
```

I want to transform it to this unnormalized form:

```
{
  layers: [{
    id: 1,
    features: [{
      id: 3,
      name: 'blah'
    }]
  }]
}
```

My code that does not work:

```
      const normalizedData = {...see first example of normalized data}
      const feature = new schema.Entity('features');
      const layer = new schema.Entity('layers', {
        features: [feature]
      });
      const denormalizedData = denormalize(
        {features: normalizedData.features.allIds},
        layer,
        {layers: normalizedData.layers.byId}
      );
```
The result:

```
{
features: undefined
}
```

I've tried a number of different ways, but perhaps I just don't understand what denormalize is actually supposed to do.  I see examples where it's used to denormalize a single object, but never an array of objects.

**Comment by paularmstrong** [comment]
Issues on GitHub are intended to be related to problems with Normalizr itself. You are not likely to receive support with how to use it here 😁.

---

If you have a support request or question please submit them to one of this resources:

* StackOverflow: https://stackoverflow.com/questions/tagged/normalizr using the tag `normalizr`
* Also have a look at the docs for more information on how to get do many things: https://github.com/paularmstrong/normalizr/tree/master/docs
