### ISSUE TITLE
Required detailed documentation on the library fo beginners

### ISSUE THREAD

**Issue by budarin** [paularmstrong/normalizr#370]
# Problem
I am a developer with more then 20 years in software development, but  the third day in a row I'm trying to understand how the library works and I still can't
it is not clear what the procedure is designed? 
scheme of what is or what will happen ?
how's the conversion going?
 how to specify normalizr what to take from the current schema and put in the result

The tiny issue in main page doesnt give understand how to write your own schemas to process my own

# Solution
write detailed documentation about the philosophy of the library and step by step to describe what and how to do in order to get the desired result

**Comment by paularmstrong** [comment]
Feel free to open a PR.
