### ISSUE TITLE
Error in the arguments order for normalize function

### ISSUE THREAD

**Issue by MathieuGi** [paularmstrong/normalizr#372]
Hello, 

Sorry in advance if I'm wrong but it seems that the order of the arguments you put in normalize function in you documentation if wrong. You wrote:

`const normalizedData = normalize(originalData, article);`

But apparently it should be:

`const normalizedData = normalize(article, originalData);`

(It took me a while to find out what was the problem as my error message wasn't really explicit ^^)

**Comment by paularmstrong** [comment]
PR?

**Comment by paularmstrong** [comment]
Also, no. `normalize` takes raw data as the first argument and a schema as the second.
