### ISSUE TITLE
How to retain sort order from the server?

### ISSUE THREAD

**Issue by shehi** [paularmstrong/normalizr#376]
I have exactly the same problem which was mentioned in #9 :

Server Output:
![image](https://user-images.githubusercontent.com/653569/58382082-e774ff00-7fc5-11e9-9fe8-2ddbda2a98cf.png)

As you can see id = 1 is followed by id = 3.

After data passes through normalizr however:
![image](https://user-images.githubusercontent.com/653569/58382092-168b7080-7fc6-11e9-8aff-d54dfda26bcb.png)

Here data was re-ordered. What can be done to retain server ordering? Thanks.

**Comment by paularmstrong** [comment]
Please use one of the [templates provided](https://github.com/paularmstrong/normalizr/tree/master/.github/ISSUE_TEMPLATE) for issues.

Cannot help without code that is runnable. Also prefer to leave Github Issues as pure "issues" with the project, and not issues with your integrations. If you have usage questions or difficulty figuring something out, please use something else, like [StackOverflow](https://stackoverflow.com/questions/tagged/normalizr).
