### ISSUE TITLE
Option to replace nested entity properties with ones suffixed with _id / _ids

### ISSUE THREAD

**Issue by tlrobinson** [paularmstrong/normalizr#423]
# Problem

I want to use a mix of normalized/flat objects and denormalized/nested objects in my application. It's confusing having the same properties sometimes being a numeric IDs and sometimes being nested objects.

# Solution

I'd like an option (probably on `schema. Entity`?) to suffix the replaced "id" properties with `_id` and `_ids` for arrays, .e.x

```json
{
  "id": "123",
  "author": {
    "id": "1",
    "name": "Paul"
  },
  "title": "My awesome blog post",
  "comments": [
    {
      "id": "324",
      "commenter": {
        "id": "2",
        "name": "Nicole"
      }
    }
  ]
}
```

becomes 

```json
{
  "result": "123",
  "entities": {
    "articles": {
      "123": {
        "id": "123",
        "author_id": "1",
        "title": "My awesome blog post",
        "comments_ids": [ "324" ]
      }
    },
    "users": {
      "1": { "id": "1", "name": "Paul" },
      "2": { "id": "2", "name": "Nicole" }
    },
    "comments": {
      "324": { "id": "324", "commenter_id": "2" }
    }
  }
}
```

Note the `author` became `author_id`, `comments` became `comments_ids`, and `commenter` became `commenter_id`.

**Comment by paularmstrong** [comment]
This sounds like a good option for a fork of normalizr. I'm not interested in confusing the API and bringing this into the current core.
