### ISSUE TITLE
How deep does normalizing go?

### ISSUE THREAD

**Issue by rosspace** [paularmstrong/normalizr#426]
I have the following schema:
const field = schema.Entity('fields');
const def = schema.Entity('defs', {
  fields: [field]
});
const item = schema.Entity('items', {
  def: def
};
const mySchema = schema.Entity('myObjs', {
  items: [item]
}
const n = normalize(myData, mySchema);

in my normalized data fields has not been normalized and remains intact on the def object. Does normalizr only go so deep? Do I have to normalize the def object manually?

**Comment by paularmstrong** [comment]
Please follow the issue template or use stackoverflow for help. As it stands, there's not enough information for anyone to help you.

**Comment by rosspace** [comment]
Or you could answer my question of whether this is even a problem or expected behavior. Is there a limit of how many layers of child objects normalizr will travel? If I knew that normalizr will only travel down to the nth level of child relationships I can change my code in response to that knowledge. I don't see any mention of that in your docs though. I'm just trying to determine if I've run into a problem or not.

**Comment by paularmstrong** [comment]
There is no limit. Something with your code is wrong, but you didn't provide enough information, like sample data, to determine what you're doing wrong.
