### ISSUE TITLE
Using "module" as schema variable breaks app

### ISSUE THREAD

**Issue by CPoncet** [paularmstrong/normalizr#437]
# Problem

When using Normalizr in Create React App environment, the following schema declaration breaks the app:

`const module = new schema.Entity('modules', {})`

No errors popping on the terminal when starting the app.

On the browser, the app is blank and console logs this:
`SyntaxError: redeclaration of formal parameter module main.chunk.js:316:6 note: Previously declared at line 271, column 16main.chunk.js:271:16`

I suggest either fixing the issue or at least put a warning on the readme.

**Comment by paularmstrong** [comment]
This looks like an issue with your setup. Since the normalizr documentation never uses that as an example, this seems like something that should be handled by webpack or babel or something else.
