### ISSUE TITLE
Id generation for child schema not working in normalizr 3.5.x or higher

### ISSUE THREAD

**Issue by shiv1490** [paularmstrong/normalizr#464]
I have a parent schema inside which has a child schema and child schema doesn't have any uique Id, so I was generating the same in schema and it was working fine until normalizr 3.4.0. 

After upgrading to latest or version after 3.4.0... I am getting id of child as undefined in parent response. 

Non -working code 
https://codesandbox.io/s/dawn-hooks-qw9fi 

Working code in 3.40 verison 
https://codesandbox.io/s/blazing-voice-0s4fr

Note: I can still generate id in child response before passing data to normalizr to make it work , still wanted to confirm if there is any other way

**Comment by paularmstrong** [comment]
Both of those links work for me, as far as I can tell. Am I missing something?

3.4.0 version:
<img width="368" alt="Screen Shot 2021-02-15 at 4 59 22 PM" src="https://user-images.githubusercontent.com/33297/108006055-3b502480-6faf-11eb-9f26-ef55966b29bf.png">

Your "non-working code" version:
<img width="366" alt="Screen Shot 2021-02-15 at 4 58 29 PM" src="https://user-images.githubusercontent.com/33297/108006025-24113700-6faf-11eb-9342-892abe51587b.png">

It would help if you could maybe generate a test case that uses an assertion for what you expect to appear to show what's wrong?

**Comment by shiv1490** [comment]
![image](https://user-images.githubusercontent.com/15919645/108006273-1e6b2e00-704f-11eb-8ee4-07be25e254af.png)
 issue is with users as its not mapping the id of adresses

**Comment by paularmstrong** [comment]
Your code for ID generation isn't quite right for >= 3.5. `idAttribute` can be a function that returns the ID:

```
const address = new schema.Entity(
    "addresses", {}, {
        idAttribute: () => shortid.generate(),
        processStrategy: (input) => {
            return input;
        },
    }
);
```

**Comment by shiv1490** [comment]
Yes I tried that , but in that case mapping will not be correct as it will generate two different id in customer and address not pointing to same response. 

![Uploading image.png…]()

**Comment by paularmstrong** [comment]
You can't use an ID generator that is not idempotent – it must return the same value every time it is run for the given circumstances in which it is run because it may be run more than once.

I would suggest making your API set IDs on these, not making them entities, or using some known data inside the address as a unique ID. 

This is by design
