### ISSUE TITLE
Value is not normalized but when denormalizing the fallbackStrategy does run.

### ISSUE THREAD

**Issue by R4VANG3R** [paularmstrong/normalizr#465]
# Problem

I'm trying to normalize a number value away as an array of numbers `processStrategy: v => [v]`

https://codesandbox.io/s/youthful-hill-55j03?file=/index.test.js

When normalizing this isn't picked up, the value will just remain. However when denormalizing the entities, it will then run through the `fallbackStrategy`.

**Input**

Here's how I'm using normalizr:

```js
// Add as much relevant code and input as possible.
const myData = {
  id: 1, positionY: 150
};
const positionYSchema = new schema.Entity("positions", {}, {
    processStrategy: (value) => [0, value, 0],
    fallbackStrategy: () => [0, 0, 0],
    idAttribute: (value, parent) => parent.id
});
const mySchema = new schema.Entity('myschema', {
  positionY: positionYSchema,
});
normalize(myData, mySchema);
```

**Output**

Here's what I expect to see when I run the above:

```js
{
      entities: {
        myschema: {
          1: { id: 1, positionY: 1 }
        },
        positions: {
          1: [0, 150, 0]
        }
      },
      result: 1
    }
```

Here's what I _actually_ see when I run the above:

```js
{
    "entities": {
        "myschema": {
            "1": {
                "id": 1,
                "positionY": 150
            }
        }
    },
    "result": 1
}
```

**Comment by paularmstrong** [comment]
Numbers are not normalize-able objects, so what you're trying to do is not possible. if `positionY` were an `Object` or `Array` in your input data, it would work.

**Comment by R4VANG3R** [comment]
Alright then I'll convert the values before normalizing them. I believe the fallbackStrategy thing is related to #394 so closing this issue, thanks for the quick response.
