### ISSUE TITLE
Mutation of source object after normalization

### ISSUE THREAD

**Issue by dimkaufo** [paularmstrong/normalizr#469]
**Issue:** 
Normalization of an object with the schema that has `processStrategy` in it - mutates source object.

Version: normalizr@3.6.1

**Example:** 
Let's consider following example:

_Schema:_ 
```
const lessonsSchema = new schema.Entity('lessons')

const chaptersSchema = new schema.Entity(
  'chapters',
  {
    items: [lessonsSchema],
  },
  {
    processStrategy: (chapter) => {
      return chapter;
    },
  }
);

const courseSchema = new schema.Entity(
  'course',
  {
    chapters: [chaptersSchema],
  }
);
```

_Source object before normalization:_
```
const course = {
  id: 10,
  chapters: [{
    id: 20,
    items: [{
      id: 30,
    }]
  }, {
    id: 21,
    items: [{
      id: 31,
    }, {
      id: 32,
    }]
  }]
}
```

_Do normalization:_
```
normalize(course, courseSchema);
```

_Source object(course) after normalization:_
```
{
   id: 10,
   chapters: [{
     id: 20,
     items: [
       30
     ]
   }, {
     id: 21,
     items: [
        31,
        32
     ]
  }]
}
```

As you see, `items` is now **array of strings**, but it was **array of objects** before. 
As I understand normalization should not touch the source object, but only provide normalized version of data no matter how we define the schema.

**Comment by paularmstrong** [comment]
This is up to your implementation.

From docs https://github.com/paularmstrong/normalizr/blob/master/docs/api.md#entitykey-definition---options--

> Note: It is recommended to always return a copy of your input and not modify the original.
