### ISSUE TITLE
When using typescript, provide a way not to have to process the entire nested structure in `processStrategy`

### ISSUE THREAD

**Issue by grandivory** [paularmstrong/normalizr#471]
# Problem

The type given for `processStrategy` for `Schema.Entity<T>` is `StrategyFunction<T>`, where `T` is the type of the result. When the type of the result is not the same as the type of the input (for example, key names change), and the object contains nested entities that are ALSO a different type, this strict typing forces the end-user to process the entire nested structure in order to fit the given type definition.

```ts
interface PlayerInput {
  playerId: string
  characters: CharacterInput[]
}

interface CharacterInput {
  characterId: string
  name: string
}

interface PlayerOutput {
  id: string // The key for this has changed
  characters: CharacterOutput[]
}
interface CharacterOutput {
  id: string // The key for this has also changed
  name: string
}

// no processStrategy is needed here, because the characters already have to be processed by the schema below
const characterSchema = new schema.Entity<CharacterOutput>('characters') 
const playersSchema = new schema.Entity<PlayerOutput>(
  'players',
  {
    'characters': characterSchema
  },
  {
    'processStrategy': (entity: PlayerInput) => ({
      'id': entity.playerId,
      'characters': entity.characters.map(character => ({ // This is required, because otherwise the output of `processStrategy` wouldn't match `PlayerOutput`
        'id': character.characterId
        'name': character.name
      }))
    })
  }
);
```

# Solution

The most ideal solution would be to have a much more descriptive type system, where the type of the definition could be used to filter the input and output types, overriding keys where needed:

The given `definition` type below is intentionally specific since I don't have time to fully solve the problem on my own right now.
```ts
...

export type StrategyFunction<Input = any, Output = any> = (value: Input, parent: any, key: string) => Output

export interface EntityOptions<Input = any, Output = any, Median = any> {
  ...
  processStrategy?: StrategyFunction<Input, Median>
}

type DefinitionType = {'characters': Schema.Entity<CharacterInput, CharacterOutput>}
export class Entity<Input = any, Output = any> {
  
  constructor(key: string | symbol, definition?: DefinitionType, options?: EntityOptions<Input, Output, Omit<Output, keyof DefinitionType> & Pick<Input, keyof DefinitionType>
}
```

An easier solution to code up might be just to let the end user define a median type for `processStrategy` rather than automatically inferring it.

**Comment by paularmstrong** [comment]
Normalizr is not written with typescript, so this is not possible, nor is it something that we need to get into.

Might be a good use case for a fork of normalizr.
