### ISSUE TITLE
README update

### ISSUE THREAD

**Issue by dodiego** [paularmstrong/normalizr#478]
The readme is as follows:

`Using data in this kind of structure is often very difficult for JavaScript applications`

It would be nice to support this with some good data and explaining further, like:
- why is this kind of structure often very difficult?
- why does this happen in javascript in particular?
- does it mean we should always use this?
- why should we use this and how does it solve the problem that generated the motivation?

We can always go further, but I believe is simple enough to motivate more people to use the library

**Comment by paularmstrong** [comment]
PRs welcome, though if you need to be convinced, you probably don't need to use normalizr yet.

**Comment by dodiego** [comment]
It's true, but some people simply don't realize they need this because they are not sure how this can solve their problem. It's not about convincing, it's about explaining better!
