### ISSUE TITLE
Allow denormalizing entities with prototypes

### ISSUE THREAD

**Issue by guncha** [paularmstrong/normalizr#482]
# Problem

We're using ES6 classes for our entities and would like `denormalize` to use exactly what `processStrategy` returns for any child entities. Currently, the `unvisitEntity` function will create a copy using `{...entity}` which will break the prototype chain. If the contract is that the `mergeStrategy` method returns a copy, denormalize should be free to modify it in place.  

This is how we're using it currently:
```ts
const barSchema = new schema.Entity('bar', {}, {
  processStrategy: entity => new Bar(entity),
});

const fooSchema = new schema.Entity('foo', {
  bar: barSchema,
}, {
  processStrategy: entity => new Foo(entity),
});
```

When denormalizing `foo`, we'd like `foo.bar` to be `instanceof Bar`, instead it's a POJO currently.

# Solution

A few options:
1) Remove the copy. Depending on the details that I'm not familiar with, this may or may not be a breaking change.
2) Remove the copy, but only when we know that a mergeStrategy was used.
3) Allow providing a custom `clone()` method to the schema that knows how to copy custom values.

**Comment by paularmstrong** [comment]
Normalizr is intended to be used on JSON-like objects. Something like this would take an invasive refactor of most of the library and doesn't seem like there's enough need for it. Perhaps a fork of normalizr would better suit the need.
