### ISSUE TITLE
Remove missing entities during denormalize

### ISSUE THREAD

**Issue by georeith** [paularmstrong/normalizr#483]
# Problem

When denormalizing sometimes an entity can't be found by `id`. In that case I would rather remove it than have it be `undefined` which creates invalid data for my use case.

I am aware that `fallbackStrategy` exists but my schema does not have a blank item and `fallbackStrategy` has no way of not putting some data there. Instead I would like the entity to be skipped entirely.

# Solution

A solution was proposed here: https://github.com/paularmstrong/normalizr/pull/461 but was rejected as I believe someone may want the inverse (to keep `undefined` in their data).

Instead perhaps the library could expose a symbol that `fallbackStrategy` can return to signal the item should be ignored (if you also added this to `processStrategy` it would work for https://github.com/paularmstrong/normalizr/issues/267 and cases where people want to ignore soft deleted items).

**Comment by paularmstrong** [comment]
Yes, #461 was closed because `undefined` is intentional.

**Comment by georeith** [comment]
@paularmstrong I understood why #461 was closed but I and others have run into the issue where we would rather remove items, is it not worth a discussion?

E.g. why is `fallbackStrategy` that lets you replace it with any old object any more kosher than removing it entirely?
