### ISSUE TITLE
Normalize to any value, not just string

### ISSUE THREAD

**Issue by jancama2** [paularmstrong/normalizr#485]
# Problem
I've got a lot of lists of articles, each list has `mention` field which differs based on the list it is in. I would like to normalize the common parts of the article and leave `mention` in the `result`. 

## Input
````
[{ id: 1, title: 'Article 1', mention: 'A' }, { id: 2, title: 'Article 2', mention: 'B' }]
````
## Output
```
{
   entities: {
      articles: {
         1: { id: 1, title: 'Article 1' }
         2: { id: 2, title: 'Article 2' }
      }
   },
   result: [{ id: 1, mention: 'A' }, { id: 2, mention: 'B' }]
}
```

Doing this on the input array level is doable even without any change of `normalizr`, in `processStrategy` you omit `mention` and then you iterate `result` and create the new array with picked `mention` field. The problem comes if you want to do it on the schema level. 

# Solution
The solution looks quite simple but I'm not sure how to implement it in normalizr. The only change is to add a new option to be able to normalize not only into string but into any value. 

I would add an option to `Entity` schema, something like `normalizedValue` which would be a function that accepts the entity itself and returns any value.

Without `normalizedValue`, everything would work the same and the `idAttribute` would be used to replace the entity. With `normalizedValue`, the function would be called to get the value to replace the entity with.

## Solution for the example
```
new schema.Entity('articles', {} {
   normalizedValue: (entity) =>( { id: entity.id, mention: entity.mention }) 
   processStrategy: (entity) =>  omit(entity, 'mention'),
});
```

**Comment by YuanRuQian** [comment]
But I assume that the purpose of `normalizr` is to [return nested entities with their IDs, gathered in dictionaries](https://github.com/paularmstrong/normalizr/blob/master/docs/introduction.md)?

So maybe this`normalizedValue` idea is not consistent with the motivation of this library?

PS You will also have greater leeway to handle `entities` or convert it to your desired format by yourself ٩(｡・ω・｡)و
```typescript
import { omit } from "lodash-es";

import { data } from "./data";

const article = new schema.Entity(
  "articles",
  {},
  {
    idAttribute: "id"
  }
);

const articles = [article];

const normalizedData = normalize(data, articles);

console.log("normalizedData:", normalizedData);

// normalizedData:
// {entities: Object, result: Array(2)}
// entities: Object
// articles: Object
// 1: Object
// id: 1
// title: "Article 1"
// mention: "A"
// 2: Object
// id: 2
// title: "Article 2"
// mention: "B"
// result: Array(2)
// 0: 1
// 1: 2

console.log(
  "desired results:",
  Object.values(normalizedData.entities.articles).map((article) =>
    omit(article, "title")
  )
);

// desired results:
// (2) [Object, Object]
// 0: Object
// id: 1
// mention: "A"
// 1: Object
// id: 2
// mention: "B"
```

**Comment by paularmstrong** [comment]
As @YuanRuQian said, that is not how the library was designed or intended to work. Such an option would warrant a fork of the lib.
