### ISSUE TITLE
Items are referenced as null after 3.5.0

### ISSUE THREAD

**Issue by georeith** [paularmstrong/normalizr#487]
# Problem

An issue was introduced in 3.5.0 (works fine in 3.4.0) where items are being referenced as `null` in their parent.

See: https://codesandbox.io/s/normalizr-forked-gn1hn?file=/index.js

**Input**

See: https://codesandbox.io/s/normalizr-forked-gn1hn?file=/index.js

**Output**

Here's what I expect to see when I run the above:

```js
{
  "root": {
    "id": "5033920488605078601",
    "className": "Canvas",
    "children": [
      "88e19d12-13b9-4272-aa55-0c4b66357d9f"
    ]
  },
  "items": {
    "88e19d12-13b9-4272-aa55-0c4b66357d9f": {
      "a": 1,
      "className": "Shape",
      "id": "88e19d12-13b9-4272-aa55-0c4b66357d9f",
      "parentId": null
    }
  },
  "tokens": {},
  "data": {}
}
```

Here's what I _actually_ see when I run the above:

```js
{
  "root": {
    "id": "5033920488605078601",
    "className": "Canvas",
    "children": [
      null
    ]
  },
  "items": {
    "88e19d12-13b9-4272-aa55-0c4b66357d9f": {
      "a": 1,
      "className": "Shape",
      "id": "88e19d12-13b9-4272-aa55-0c4b66357d9f",
      "parentId": null
    }
  },
  "tokens": {},
  "data": {}
}
```

**Comment by georeith** [comment]
@paularmstrong this is my API generating the ID.

**Comment by paularmstrong** [comment]
This is the code you linked, which includes uuid to generate IDs:

```js
    processStrategy: (entity, parent) => {
      // have to mutate this as normalizr looks at the original object for an id :(
      Object.assign(entity, {
        id: entity.id || uuidv4(),
        parentId: parent.id && parent.className !== "Canvas" ? parent.id : null
      });

      return { ...entity };
    },
```

**Comment by georeith** [comment]
@paularmstrong I am aware. This code forms my API

**Comment by paularmstrong** [comment]
Yes, and assigning it to a completely random value will also not work. `idAttribute` accepts a function to generate an ID from the data you've received. https://github.com/paularmstrong/normalizr/blob/master/docs/api.md#entitykey-definition---options--

**Comment by georeith** [comment]
@paularmstrong I know about `idAttribute` in this case I have an old normalized database without IDs attached to these items, now needs IDs attached to them.

This has been working absolutely fine prior to 3.5.0.

The issue it seems is that `idAttribute` is now called before `processStrategy`.
