### ISSUE TITLE
Remove classes and rewrite on typescipt

### ISSUE THREAD

**Issue by Gentlee** [paularmstrong/normalizr#496]
# Problem

1. Using classes is a bad architectural solution, forces to use inheritance which is an antipattern and should be avioded, and makes code less reusable due to "monkey and banana" problem. Summing up - classes make code more complex with no pros.

2. Using typescript makes code easier to maintain, less bug prone and automatically generates up to date definition files.

# Solution

It is pretty straightforward.

**Comment by paularmstrong** [comment]
> It is pretty straightforward.

Ok. Open a PR.
