### ISSUE TITLE
Cannot use latest features

### ISSUE THREAD

**Issue by downsider** [paularmstrong/normalizr#88]
I am very interested in using the new `mappedBy` feature in one of my projects. Unfortunately, this isn't included in any release as yet.
However, even though I can install the master branch using npm, I am unable to use it due to normalizr's package.json pointing to lib/index.js, which is only created during the build process. I would like to avoid having to manually build normalizr, as this isn't something that is easily automated; I have tried several approaches, none of which are suitable.

The easiest solution I can think of would be for you to release a new version of normalizr which contains `mappedBy`. If for some reason you don't want to do this, could you advise me how I can use npm to install a working version of the master branch please?

**Comment by gaearon** [comment]
Yes, this is why we shouldn’t merge docs to master if we don’t intend to publish an update immediately afterwards. :smile:

**Comment by jnatherley** [comment]
Same here. I tried to use it by trying to obtain the latest package from github, but there seems to be issues around using github packages with NPM.

Any idea on a timeframe as this could be pretty key to my project? 🎱

**Comment by paularmstrong** [comment]
@gaearon We might consider moving the docs to a sub-folder and having the README link to the latest version instead of the master branch.
