### ISSUE TITLE
How to handle same object in different parent has different value?

### ISSUE THREAD

**Issue by zation** [paularmstrong/normalizr#94]
Say we have two shema: Article, Platform. A same article can be uploaded to different platform, and have different "like" number. For example:
```js
GET platforms
[{
  id: 1,
  articles: [{
    id: 1,
    like: 200
  }]
}, {
  id: 2,
  articles: [{
    id: 1,
    like: 300
  }]
}]
```

If I use normalizr to handle this directly, article 1 will always only have one like number, the first one. So how can I keep all the information include the like number? Should I create an extra shema for the like number? How to do this?

**Comment by paularmstrong** [comment]
You're going to get a merge error in cases like this. [src/index.js:66-69](https://github.com/gaearon/normalizr/blob/master/src/index.js#L66-L69). You can pass your own `mergeIntoEntity` function to handle this from the `normalize` function:

```js
normalize(platforms, { mergeIntoEntity: myMergeFunction });
```

**Comment by pgilad** [comment]
I have the same problem, and it sums up to basically having non-unique entities with the same id. I don't think there is a standard solution to this, but an end result could look like:

```js
entities: {
  platforms: {
    1: {
      articles: [1]
    },
    2: {
      articles: [1]
    }
  }
  articles: {
    1: {
       likeByPlatform: {
         1: 200,
         2: 300
       }
     }
  }
}
```

This might cause a merge headache... But the only other solution I see is creating new unique ids (i.e be combining the article and platform id) with the like count, but that is a problem depending on your ids...

I'm interested in a solution as well, running into the same challenge
