### ISSUE TITLE
Different key between response and normalized response

### ISSUE THREAD

**Issue by exciton** [paularmstrong/normalizr#96]
I'd like to be able to define a schema which uses a different key from what the server sends for the list of IDs. I'm fairly sure this is not currently possible.

E.g. server response like this:
```javascript
{
  id: 1,
  categories: [{ id: 10, name: 'Test'}]
}
```
into a normalized response like this
```javascript
{ result: 1,
  entities { 
    events {
      1: { category_ids: [10] }
    },
    categories {
      10: { name: 'Test' }
    }
  }
}
```
Note that the server returned a categories, but I want to represent it as category_ids in the normalized response. 

Currently I have a schema like this:
```javascript
const category = new Schema('categories')
const event = new Schema('events')
event.define({ categories: arrayOf(category) })
```

Is it possible to add an option to specify what key to use when assigning the normalized data? I don't believe the assignEntity function can do this (since it can't be set on a per-schema basis). schemaAttribute also isn't right. 
Perhaps the best way would be to allow assignEntity to be used in arrayOf etc.

e.g. 
```javascript
event.define({ 
  categories: arrayOf(category, { assignEntity: (obj, key, val) => obj['category_ids'] = val }) 
})
```

**Comment by joewood** [comment]
How would this work for a many-to-one relationship? For example, articles to an auhor if you wanted the result (as above) to use `author_id` on `article`. Currently there's no way to pass an **options** argument:

```javascript
article.define({
  author: user,
});
```

Maybe if we had a `oneOf` function then we could pass an **options** object to it:
```javascript
article.define({
  author: oneOf(user,{ assignEntity: (obj,key,val)=> obj["author_id"]=val; })
});
```

**Comment by frankwallis** [comment]
I think that https://github.com/paularmstrong/normalizr/pull/89 will solve this as you will be able to specify the new id on the schema and override assignEntity.

**Comment by joewood** [comment]
@frankwallis how do you specify `assignEntity` as an option for a many-to-one relationship as above?

**Comment by frankwallis** [comment]
```assignEntity``` is specified on the ```normalize``` call, and called for each entity which is normalized

**Comment by exciton** [comment]
I think that #89 doesn't solve my case where I specifically want to specify assignEntities inside the schema definition. This is much more useful than specifying it when calling normalize since you don't need to know the details of the full schema and the code where normalize is called doesn't need to know anything about the specific schema or is normalizing. 

The assignEntities function is much more likely to be specific to a schema (or sub-schema) than it is to a normalize call.

**Comment by exciton** [comment]
Actually, looking closer at the PR from #89 it would be possible to do this by assigning a meta attribute which can be used to define a new key to use, rather than specifying a function. This would ultimately be more terse.

I'll test it out and write up a quick demo showing the use and we can then close this issue.

**Comment by frankwallis** [comment]
here's what I have:

```
  it('can override key name of array of entities', function () {
    const category = new Schema('categories');
    const event = new Schema('events', { meta: { overrideIds: { categories: 'category_ids' }}})
    event.define({ categories: arrayOf(category) })
    
    var input = {
      id: 1,
      categories: [{ id: 10, name: 'Test'}]
    }

    var options = {
      assignEntity: function (obj, key, val, originalInput, schema) {
        key = schema.getMeta && schema.getMeta('overrideIds') && schema.getMeta('overrideIds')[key] || key;
        obj[key] = val;
      }
    };

    normalize(input, event, options).should.eql({ 
      result: 1,
      entities :{ 
        events: {
          1: { 
             id: 1,
             category_ids: [10] 
          }
        },
        categories: {
          10: {
             id: 10, 
             name: 'Test' 
          }
        }
      }
    });
  });
```

**Comment by exciton** [comment]
Nice. That'll work for me!

**Comment by frankwallis** [comment]
I'm hopeful that PR will get merged fairly soon, but in the meantime if you want to use this feature it is published on npm as ```tmp__nrmlzr``` https://www.npmjs.com/package/tmp__nrmlzr.

Obviously the implementation may change when/if it gets merged into normalizr.

**Comment by paularmstrong** [comment]
Closing, as #89 was merged. Please reopen if there's still a problem.
